// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var amuletOfAssertivenessTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type AmuletOfAssertivenessYellow struct{}

func (AmuletOfAssertivenessYellow) ID() ids.CardID           { return ids.AmuletOfAssertivenessYellow }
func (AmuletOfAssertivenessYellow) Name() string             { return "Amulet of Assertiveness" }
func (AmuletOfAssertivenessYellow) DisplayName() string      { return "Amulet of Assertiveness [Y]" }
func (AmuletOfAssertivenessYellow) Cost(card.GameEngine) int { return 0 }
func (AmuletOfAssertivenessYellow) Pitch() int               { return 2 }
func (AmuletOfAssertivenessYellow) Attack() int              { return 0 }
func (AmuletOfAssertivenessYellow) Defense() int             { return 0 }
func (AmuletOfAssertivenessYellow) Types(card.GameEngine) card.TypeSet {
	return amuletOfAssertivenessTypes
}
func (AmuletOfAssertivenessYellow) GoAgain(card.GameEngine) bool { return true }
func (AmuletOfAssertivenessYellow) Unplayable()                  {}
