// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var healingPotionTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type HealingPotionBlue struct{}

func (HealingPotionBlue) ID() ids.CardID                     { return ids.HealingPotionBlue }
func (HealingPotionBlue) Name() string                       { return "Healing Potion" }
func (HealingPotionBlue) DisplayName() string                { return "Healing Potion [B]" }
func (HealingPotionBlue) Cost(card.GameEngine) int           { return 0 }
func (HealingPotionBlue) Pitch() int                         { return 3 }
func (HealingPotionBlue) Attack() int                        { return 0 }
func (HealingPotionBlue) Defense() int                       { return 0 }
func (HealingPotionBlue) Types(card.GameEngine) card.TypeSet { return healingPotionTypes }
func (HealingPotionBlue) GoAgain(card.GameEngine) bool       { return false }
func (HealingPotionBlue) Unplayable()                        {}
