// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var potionOfLuckTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type PotionOfLuckBlue struct{}

func (PotionOfLuckBlue) ID() ids.CardID                     { return ids.PotionOfLuckBlue }
func (PotionOfLuckBlue) Name() string                       { return "Potion of Luck" }
func (PotionOfLuckBlue) DisplayName() string                { return "Potion of Luck [B]" }
func (PotionOfLuckBlue) Cost(card.GameEngine) int           { return 0 }
func (PotionOfLuckBlue) Pitch() int                         { return 3 }
func (PotionOfLuckBlue) Attack() int                        { return 0 }
func (PotionOfLuckBlue) Defense() int                       { return 0 }
func (PotionOfLuckBlue) Types(card.GameEngine) card.TypeSet { return potionOfLuckTypes }
func (PotionOfLuckBlue) GoAgain(card.GameEngine) bool       { return false }
func (PotionOfLuckBlue) Unplayable()                        {}
