// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var backAlleyBreaklineTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type BackAlleyBreaklineRed struct{}

func (BackAlleyBreaklineRed) ID() ids.CardID                     { return ids.BackAlleyBreaklineRed }
func (BackAlleyBreaklineRed) Name() string                       { return "Back Alley Breakline" }
func (BackAlleyBreaklineRed) DisplayName() string                { return "Back Alley Breakline [R]" }
func (BackAlleyBreaklineRed) Cost(card.GameEngine) int           { return 1 }
func (BackAlleyBreaklineRed) Pitch() int                         { return 1 }
func (BackAlleyBreaklineRed) Attack() int                        { return 5 }
func (BackAlleyBreaklineRed) Defense() int                       { return 2 }
func (BackAlleyBreaklineRed) Types(card.GameEngine) card.TypeSet { return backAlleyBreaklineTypes }
func (BackAlleyBreaklineRed) GoAgain(card.GameEngine) bool       { return false }
func (BackAlleyBreaklineRed) NotImplemented()                    {}

type BackAlleyBreaklineYellow struct{}

func (BackAlleyBreaklineYellow) ID() ids.CardID                     { return ids.BackAlleyBreaklineYellow }
func (BackAlleyBreaklineYellow) Name() string                       { return "Back Alley Breakline" }
func (BackAlleyBreaklineYellow) DisplayName() string                { return "Back Alley Breakline [Y]" }
func (BackAlleyBreaklineYellow) Cost(card.GameEngine) int           { return 1 }
func (BackAlleyBreaklineYellow) Pitch() int                         { return 2 }
func (BackAlleyBreaklineYellow) Attack() int                        { return 4 }
func (BackAlleyBreaklineYellow) Defense() int                       { return 2 }
func (BackAlleyBreaklineYellow) Types(card.GameEngine) card.TypeSet { return backAlleyBreaklineTypes }
func (BackAlleyBreaklineYellow) GoAgain(card.GameEngine) bool       { return false }
func (BackAlleyBreaklineYellow) NotImplemented()                    {}

type BackAlleyBreaklineBlue struct{}

func (BackAlleyBreaklineBlue) ID() ids.CardID                     { return ids.BackAlleyBreaklineBlue }
func (BackAlleyBreaklineBlue) Name() string                       { return "Back Alley Breakline" }
func (BackAlleyBreaklineBlue) DisplayName() string                { return "Back Alley Breakline [B]" }
func (BackAlleyBreaklineBlue) Cost(card.GameEngine) int           { return 1 }
func (BackAlleyBreaklineBlue) Pitch() int                         { return 3 }
func (BackAlleyBreaklineBlue) Attack() int                        { return 3 }
func (BackAlleyBreaklineBlue) Defense() int                       { return 2 }
func (BackAlleyBreaklineBlue) Types(card.GameEngine) card.TypeSet { return backAlleyBreaklineTypes }
func (BackAlleyBreaklineBlue) GoAgain(card.GameEngine) bool       { return false }
func (BackAlleyBreaklineBlue) NotImplemented()                    {}
