// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var blanchTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type BlanchRed struct{}

func (BlanchRed) ID() ids.CardID          { return ids.BlanchRed }
func (BlanchRed) Name() string            { return "Blanch" }
func (BlanchRed) DisplayName() string     { return "Blanch [R]" }
func (BlanchRed) Cost(*sim.TurnState) int { return 3 }
func (BlanchRed) Pitch() int              { return 1 }
func (BlanchRed) Attack() int             { return 7 }
func (BlanchRed) Defense() int            { return 2 }
func (BlanchRed) Types() card.TypeSet     { return blanchTypes }
func (BlanchRed) GoAgain() bool           { return false }
func (BlanchRed) NotImplemented()         {}

type BlanchYellow struct{}

func (BlanchYellow) ID() ids.CardID          { return ids.BlanchYellow }
func (BlanchYellow) Name() string            { return "Blanch" }
func (BlanchYellow) DisplayName() string     { return "Blanch [Y]" }
func (BlanchYellow) Cost(*sim.TurnState) int { return 3 }
func (BlanchYellow) Pitch() int              { return 2 }
func (BlanchYellow) Attack() int             { return 6 }
func (BlanchYellow) Defense() int            { return 2 }
func (BlanchYellow) Types() card.TypeSet     { return blanchTypes }
func (BlanchYellow) GoAgain() bool           { return false }
func (BlanchYellow) NotImplemented()         {}

type BlanchBlue struct{}

func (BlanchBlue) ID() ids.CardID          { return ids.BlanchBlue }
func (BlanchBlue) Name() string            { return "Blanch" }
func (BlanchBlue) DisplayName() string     { return "Blanch [B]" }
func (BlanchBlue) Cost(*sim.TurnState) int { return 3 }
func (BlanchBlue) Pitch() int              { return 3 }
func (BlanchBlue) Attack() int             { return 5 }
func (BlanchBlue) Defense() int            { return 2 }
func (BlanchBlue) Types() card.TypeSet     { return blanchTypes }
func (BlanchBlue) GoAgain() bool           { return false }
func (BlanchBlue) NotImplemented()         {}
