// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var crashDownTheGatesTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type CrashDownTheGatesRed struct{}

func (CrashDownTheGatesRed) ID() ids.CardID          { return ids.CrashDownTheGatesRed }
func (CrashDownTheGatesRed) Name() string            { return "Crash Down the Gates" }
func (CrashDownTheGatesRed) DisplayName() string     { return "Crash Down the Gates [R]" }
func (CrashDownTheGatesRed) Cost(*sim.TurnState) int { return 3 }
func (CrashDownTheGatesRed) Pitch() int              { return 1 }
func (CrashDownTheGatesRed) Attack() int             { return 6 }
func (CrashDownTheGatesRed) Defense() int            { return 2 }
func (CrashDownTheGatesRed) Types() card.TypeSet     { return crashDownTheGatesTypes }
func (CrashDownTheGatesRed) GoAgain() bool           { return false }
func (CrashDownTheGatesRed) NotImplemented()         {}

type CrashDownTheGatesYellow struct{}

func (CrashDownTheGatesYellow) ID() ids.CardID          { return ids.CrashDownTheGatesYellow }
func (CrashDownTheGatesYellow) Name() string            { return "Crash Down the Gates" }
func (CrashDownTheGatesYellow) DisplayName() string     { return "Crash Down the Gates [Y]" }
func (CrashDownTheGatesYellow) Cost(*sim.TurnState) int { return 3 }
func (CrashDownTheGatesYellow) Pitch() int              { return 2 }
func (CrashDownTheGatesYellow) Attack() int             { return 5 }
func (CrashDownTheGatesYellow) Defense() int            { return 2 }
func (CrashDownTheGatesYellow) Types() card.TypeSet     { return crashDownTheGatesTypes }
func (CrashDownTheGatesYellow) GoAgain() bool           { return false }
func (CrashDownTheGatesYellow) NotImplemented()         {}

type CrashDownTheGatesBlue struct{}

func (CrashDownTheGatesBlue) ID() ids.CardID          { return ids.CrashDownTheGatesBlue }
func (CrashDownTheGatesBlue) Name() string            { return "Crash Down the Gates" }
func (CrashDownTheGatesBlue) DisplayName() string     { return "Crash Down the Gates [B]" }
func (CrashDownTheGatesBlue) Cost(*sim.TurnState) int { return 3 }
func (CrashDownTheGatesBlue) Pitch() int              { return 3 }
func (CrashDownTheGatesBlue) Attack() int             { return 4 }
func (CrashDownTheGatesBlue) Defense() int            { return 2 }
func (CrashDownTheGatesBlue) Types() card.TypeSet     { return crashDownTheGatesTypes }
func (CrashDownTheGatesBlue) GoAgain() bool           { return false }
func (CrashDownTheGatesBlue) NotImplemented()         {}
