// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var pickACardAnyCardTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type PickACardAnyCardRed struct{}

func (PickACardAnyCardRed) ID() ids.CardID          { return ids.PickACardAnyCardRed }
func (PickACardAnyCardRed) Name() string            { return "Pick a Card, Any Card" }
func (PickACardAnyCardRed) DisplayName() string     { return "Pick a Card, Any Card [R]" }
func (PickACardAnyCardRed) Cost(*sim.TurnState) int { return 0 }
func (PickACardAnyCardRed) Pitch() int              { return 1 }
func (PickACardAnyCardRed) Attack() int             { return 0 }
func (PickACardAnyCardRed) Defense() int            { return 2 }
func (PickACardAnyCardRed) Types() card.TypeSet     { return pickACardAnyCardTypes }
func (PickACardAnyCardRed) GoAgain() bool           { return true }
func (PickACardAnyCardRed) NotImplemented()         {}

type PickACardAnyCardYellow struct{}

func (PickACardAnyCardYellow) ID() ids.CardID          { return ids.PickACardAnyCardYellow }
func (PickACardAnyCardYellow) Name() string            { return "Pick a Card, Any Card" }
func (PickACardAnyCardYellow) DisplayName() string     { return "Pick a Card, Any Card [Y]" }
func (PickACardAnyCardYellow) Cost(*sim.TurnState) int { return 0 }
func (PickACardAnyCardYellow) Pitch() int              { return 2 }
func (PickACardAnyCardYellow) Attack() int             { return 0 }
func (PickACardAnyCardYellow) Defense() int            { return 2 }
func (PickACardAnyCardYellow) Types() card.TypeSet     { return pickACardAnyCardTypes }
func (PickACardAnyCardYellow) GoAgain() bool           { return true }
func (PickACardAnyCardYellow) NotImplemented()         {}

type PickACardAnyCardBlue struct{}

func (PickACardAnyCardBlue) ID() ids.CardID          { return ids.PickACardAnyCardBlue }
func (PickACardAnyCardBlue) Name() string            { return "Pick a Card, Any Card" }
func (PickACardAnyCardBlue) DisplayName() string     { return "Pick a Card, Any Card [B]" }
func (PickACardAnyCardBlue) Cost(*sim.TurnState) int { return 0 }
func (PickACardAnyCardBlue) Pitch() int              { return 3 }
func (PickACardAnyCardBlue) Attack() int             { return 0 }
func (PickACardAnyCardBlue) Defense() int            { return 2 }
func (PickACardAnyCardBlue) Types() card.TypeSet     { return pickACardAnyCardTypes }
func (PickACardAnyCardBlue) GoAgain() bool           { return true }
func (PickACardAnyCardBlue) NotImplemented()         {}
