// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var putInContextTypes = card.NewTypeSet()

type PutInContextBlue struct{}

func (PutInContextBlue) ID() ids.CardID          { return ids.PutInContextBlue }
func (PutInContextBlue) Name() string            { return "Put in Context" }
func (PutInContextBlue) DisplayName() string     { return "Put in Context [B]" }
func (PutInContextBlue) Cost(*sim.TurnState) int { return 0 }
func (PutInContextBlue) Pitch() int              { return 3 }
func (PutInContextBlue) Attack() int             { return 0 }
func (PutInContextBlue) Defense() int            { return 3 }
func (PutInContextBlue) Types() card.TypeSet     { return putInContextTypes }
func (PutInContextBlue) GoAgain() bool           { return false }
func (PutInContextBlue) NotImplemented()         {}
