// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var ransackAndRazeTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type RansackAndRazeBlue struct{}

func (RansackAndRazeBlue) ID() ids.CardID           { return ids.RansackAndRazeBlue }
func (RansackAndRazeBlue) Name() string             { return "Ransack and Raze" }
func (RansackAndRazeBlue) DisplayName() string      { return "Ransack and Raze [B]" }
func (RansackAndRazeBlue) Cost(card.GameEngine) int { return 0 }
func (RansackAndRazeBlue) Pitch() int               { return 3 }
func (RansackAndRazeBlue) Attack() int              { return 0 }
func (RansackAndRazeBlue) Defense() int             { return 3 }
func (RansackAndRazeBlue) Types() card.TypeSet      { return ransackAndRazeTypes }
func (RansackAndRazeBlue) GoAgain() bool            { return true }
func (RansackAndRazeBlue) NotImplemented()          {}
