// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var siftTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type SiftRed struct{}

func (SiftRed) ID() ids.CardID          { return ids.SiftRed }
func (SiftRed) Name() string            { return "Sift" }
func (SiftRed) DisplayName() string     { return "Sift [R]" }
func (SiftRed) Cost(sim.GameEngine) int { return 0 }
func (SiftRed) Pitch() int              { return 1 }
func (SiftRed) Attack() int             { return 0 }
func (SiftRed) Defense() int            { return 3 }
func (SiftRed) Types() card.TypeSet     { return siftTypes }
func (SiftRed) GoAgain() bool           { return true }
func (SiftRed) NotImplemented()         {}

type SiftYellow struct{}

func (SiftYellow) ID() ids.CardID          { return ids.SiftYellow }
func (SiftYellow) Name() string            { return "Sift" }
func (SiftYellow) DisplayName() string     { return "Sift [Y]" }
func (SiftYellow) Cost(sim.GameEngine) int { return 0 }
func (SiftYellow) Pitch() int              { return 2 }
func (SiftYellow) Attack() int             { return 0 }
func (SiftYellow) Defense() int            { return 3 }
func (SiftYellow) Types() card.TypeSet     { return siftTypes }
func (SiftYellow) GoAgain() bool           { return true }
func (SiftYellow) NotImplemented()         {}

type SiftBlue struct{}

func (SiftBlue) ID() ids.CardID          { return ids.SiftBlue }
func (SiftBlue) Name() string            { return "Sift" }
func (SiftBlue) DisplayName() string     { return "Sift [B]" }
func (SiftBlue) Cost(sim.GameEngine) int { return 0 }
func (SiftBlue) Pitch() int              { return 3 }
func (SiftBlue) Attack() int             { return 0 }
func (SiftBlue) Defense() int            { return 3 }
func (SiftBlue) Types() card.TypeSet     { return siftTypes }
func (SiftBlue) GoAgain() bool           { return true }
func (SiftBlue) NotImplemented()         {}
