// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var sigilOfCyclesTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAura)

type SigilOfCyclesBlue struct{}

func (SigilOfCyclesBlue) ID() ids.CardID                     { return ids.SigilOfCyclesBlue }
func (SigilOfCyclesBlue) Name() string                       { return "Sigil of Cycles" }
func (SigilOfCyclesBlue) DisplayName() string                { return "Sigil of Cycles [B]" }
func (SigilOfCyclesBlue) Cost(card.GameEngine) int           { return 0 }
func (SigilOfCyclesBlue) Pitch() int                         { return 3 }
func (SigilOfCyclesBlue) Attack() int                        { return 0 }
func (SigilOfCyclesBlue) Defense() int                       { return 2 }
func (SigilOfCyclesBlue) Types(card.GameEngine) card.TypeSet { return sigilOfCyclesTypes }
func (SigilOfCyclesBlue) GoAgain(card.GameEngine) bool       { return true }
func (SigilOfCyclesBlue) NotImplemented()                    {}
