// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var splinteringDeadwoodTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction, card.TypeAttack)

type SplinteringDeadwoodRed struct{}

func (SplinteringDeadwoodRed) ID() ids.CardID           { return ids.SplinteringDeadwoodRed }
func (SplinteringDeadwoodRed) Name() string             { return "Splintering Deadwood" }
func (SplinteringDeadwoodRed) DisplayName() string      { return "Splintering Deadwood [R]" }
func (SplinteringDeadwoodRed) Cost(card.GameEngine) int { return 3 }
func (SplinteringDeadwoodRed) Pitch() int               { return 1 }
func (SplinteringDeadwoodRed) Attack() int              { return 7 }
func (SplinteringDeadwoodRed) Defense() int             { return 3 }
func (SplinteringDeadwoodRed) Types() card.TypeSet      { return splinteringDeadwoodTypes }
func (SplinteringDeadwoodRed) GoAgain() bool            { return false }
func (SplinteringDeadwoodRed) NotImplemented()          {}

type SplinteringDeadwoodYellow struct{}

func (SplinteringDeadwoodYellow) ID() ids.CardID           { return ids.SplinteringDeadwoodYellow }
func (SplinteringDeadwoodYellow) Name() string             { return "Splintering Deadwood" }
func (SplinteringDeadwoodYellow) DisplayName() string      { return "Splintering Deadwood [Y]" }
func (SplinteringDeadwoodYellow) Cost(card.GameEngine) int { return 3 }
func (SplinteringDeadwoodYellow) Pitch() int               { return 2 }
func (SplinteringDeadwoodYellow) Attack() int              { return 6 }
func (SplinteringDeadwoodYellow) Defense() int             { return 3 }
func (SplinteringDeadwoodYellow) Types() card.TypeSet      { return splinteringDeadwoodTypes }
func (SplinteringDeadwoodYellow) GoAgain() bool            { return false }
func (SplinteringDeadwoodYellow) NotImplemented()          {}

type SplinteringDeadwoodBlue struct{}

func (SplinteringDeadwoodBlue) ID() ids.CardID           { return ids.SplinteringDeadwoodBlue }
func (SplinteringDeadwoodBlue) Name() string             { return "Splintering Deadwood" }
func (SplinteringDeadwoodBlue) DisplayName() string      { return "Splintering Deadwood [B]" }
func (SplinteringDeadwoodBlue) Cost(card.GameEngine) int { return 3 }
func (SplinteringDeadwoodBlue) Pitch() int               { return 3 }
func (SplinteringDeadwoodBlue) Attack() int              { return 5 }
func (SplinteringDeadwoodBlue) Defense() int             { return 3 }
func (SplinteringDeadwoodBlue) Types() card.TypeSet      { return splinteringDeadwoodTypes }
func (SplinteringDeadwoodBlue) GoAgain() bool            { return false }
func (SplinteringDeadwoodBlue) NotImplemented()          {}
