// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var titForTatTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type TitForTatBlue struct{}

func (TitForTatBlue) ID() ids.CardID                     { return ids.TitForTatBlue }
func (TitForTatBlue) Name() string                       { return "Tit for Tat" }
func (TitForTatBlue) DisplayName() string                { return "Tit for Tat [B]" }
func (TitForTatBlue) Cost(card.GameEngine) int           { return 0 }
func (TitForTatBlue) Pitch() int                         { return 3 }
func (TitForTatBlue) Attack() int                        { return 0 }
func (TitForTatBlue) Defense() int                       { return 2 }
func (TitForTatBlue) Types(card.GameEngine) card.TypeSet { return titForTatTypes }
func (TitForTatBlue) GoAgain() bool                      { return true }
func (TitForTatBlue) NotImplemented()                    {}
