// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var adrenalineRushTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type AdrenalineRushRed struct{}

func (AdrenalineRushRed) ID() ids.CardID                     { return ids.AdrenalineRushRed }
func (AdrenalineRushRed) Name() string                       { return "Adrenaline Rush" }
func (AdrenalineRushRed) DisplayName() string                { return "Adrenaline Rush [R]" }
func (AdrenalineRushRed) Rarity() string                     { return "Common" }
func (AdrenalineRushRed) Cost() int                          { return 2 }
func (AdrenalineRushRed) Pitch() int                         { return 1 }
func (AdrenalineRushRed) Attack() int                        { return 4 }
func (AdrenalineRushRed) Defense() int                       { return 2 }
func (AdrenalineRushRed) Types(card.GameEngine) card.TypeSet { return adrenalineRushTypes }
func (AdrenalineRushRed) GoAgain(card.GameEngine) bool       { return false }

type AdrenalineRushYellow struct{}

func (AdrenalineRushYellow) ID() ids.CardID                     { return ids.AdrenalineRushYellow }
func (AdrenalineRushYellow) Name() string                       { return "Adrenaline Rush" }
func (AdrenalineRushYellow) DisplayName() string                { return "Adrenaline Rush [Y]" }
func (AdrenalineRushYellow) Rarity() string                     { return "Common" }
func (AdrenalineRushYellow) Cost() int                          { return 2 }
func (AdrenalineRushYellow) Pitch() int                         { return 2 }
func (AdrenalineRushYellow) Attack() int                        { return 3 }
func (AdrenalineRushYellow) Defense() int                       { return 2 }
func (AdrenalineRushYellow) Types(card.GameEngine) card.TypeSet { return adrenalineRushTypes }
func (AdrenalineRushYellow) GoAgain(card.GameEngine) bool       { return false }

type AdrenalineRushBlue struct{}

func (AdrenalineRushBlue) ID() ids.CardID                     { return ids.AdrenalineRushBlue }
func (AdrenalineRushBlue) Name() string                       { return "Adrenaline Rush" }
func (AdrenalineRushBlue) DisplayName() string                { return "Adrenaline Rush [B]" }
func (AdrenalineRushBlue) Rarity() string                     { return "Common" }
func (AdrenalineRushBlue) Cost() int                          { return 2 }
func (AdrenalineRushBlue) Pitch() int                         { return 3 }
func (AdrenalineRushBlue) Attack() int                        { return 2 }
func (AdrenalineRushBlue) Defense() int                       { return 2 }
func (AdrenalineRushBlue) Types(card.GameEngine) card.TypeSet { return adrenalineRushTypes }
func (AdrenalineRushBlue) GoAgain(card.GameEngine) bool       { return false }
