// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var amuletOfLightningTypes = card.NewTypeSet(card.TypeLightning, card.TypeAction, card.TypeItem)

type AmuletOfLightningBlue struct{}

func (AmuletOfLightningBlue) ID() ids.CardID                     { return ids.AmuletOfLightningBlue }
func (AmuletOfLightningBlue) Name() string                       { return "Amulet of Lightning" }
func (AmuletOfLightningBlue) DisplayName() string                { return "Amulet of Lightning [B]" }
func (AmuletOfLightningBlue) Rarity() string                     { return "Common" }
func (AmuletOfLightningBlue) Cost() int                          { return 0 }
func (AmuletOfLightningBlue) Pitch() int                         { return 3 }
func (AmuletOfLightningBlue) Attack() int                        { return 0 }
func (AmuletOfLightningBlue) Defense() int                       { return 0 }
func (AmuletOfLightningBlue) Types(card.GameEngine) card.TypeSet { return amuletOfLightningTypes }
func (AmuletOfLightningBlue) GoAgain(card.GameEngine) bool       { return true }
