// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var arcanicCrackleTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction, card.TypeAttack)

type ArcanicCrackleRed struct{}

func (ArcanicCrackleRed) ID() ids.CardID                     { return ids.ArcanicCrackleRed }
func (ArcanicCrackleRed) Name() string                       { return "Arcanic Crackle" }
func (ArcanicCrackleRed) DisplayName() string                { return "Arcanic Crackle [R]" }
func (ArcanicCrackleRed) Rarity() string                     { return "Common" }
func (ArcanicCrackleRed) Cost() int                          { return 0 }
func (ArcanicCrackleRed) Pitch() int                         { return 1 }
func (ArcanicCrackleRed) Attack() int                        { return 3 }
func (ArcanicCrackleRed) Defense() int                       { return 3 }
func (ArcanicCrackleRed) Types(card.GameEngine) card.TypeSet { return arcanicCrackleTypes }
func (ArcanicCrackleRed) GoAgain(card.GameEngine) bool       { return false }

type ArcanicCrackleYellow struct{}

func (ArcanicCrackleYellow) ID() ids.CardID                     { return ids.ArcanicCrackleYellow }
func (ArcanicCrackleYellow) Name() string                       { return "Arcanic Crackle" }
func (ArcanicCrackleYellow) DisplayName() string                { return "Arcanic Crackle [Y]" }
func (ArcanicCrackleYellow) Rarity() string                     { return "Common" }
func (ArcanicCrackleYellow) Cost() int                          { return 0 }
func (ArcanicCrackleYellow) Pitch() int                         { return 2 }
func (ArcanicCrackleYellow) Attack() int                        { return 2 }
func (ArcanicCrackleYellow) Defense() int                       { return 3 }
func (ArcanicCrackleYellow) Types(card.GameEngine) card.TypeSet { return arcanicCrackleTypes }
func (ArcanicCrackleYellow) GoAgain(card.GameEngine) bool       { return false }

type ArcanicCrackleBlue struct{}

func (ArcanicCrackleBlue) ID() ids.CardID                     { return ids.ArcanicCrackleBlue }
func (ArcanicCrackleBlue) Name() string                       { return "Arcanic Crackle" }
func (ArcanicCrackleBlue) DisplayName() string                { return "Arcanic Crackle [B]" }
func (ArcanicCrackleBlue) Rarity() string                     { return "Common" }
func (ArcanicCrackleBlue) Cost() int                          { return 0 }
func (ArcanicCrackleBlue) Pitch() int                         { return 3 }
func (ArcanicCrackleBlue) Attack() int                        { return 1 }
func (ArcanicCrackleBlue) Defense() int                       { return 3 }
func (ArcanicCrackleBlue) Types(card.GameEngine) card.TypeSet { return arcanicCrackleTypes }
func (ArcanicCrackleBlue) GoAgain(card.GameEngine) bool       { return false }
