// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var arcanePolarityTypes = card.NewTypeSet(card.TypeGeneric, card.TypeInstant)

type ArcanePolarityRed struct{}

func (ArcanePolarityRed) ID() ids.CardID                     { return ids.ArcanePolarityRed }
func (ArcanePolarityRed) Name() string                       { return "Arcane Polarity" }
func (ArcanePolarityRed) DisplayName() string                { return "Arcane Polarity [R]" }
func (ArcanePolarityRed) Rarity() string                     { return "Common" }
func (ArcanePolarityRed) Cost() int                          { return 0 }
func (ArcanePolarityRed) Pitch() int                         { return 1 }
func (ArcanePolarityRed) Attack() int                        { return 0 }
func (ArcanePolarityRed) Defense() int                       { return 0 }
func (ArcanePolarityRed) Types(card.GameEngine) card.TypeSet { return arcanePolarityTypes }
func (ArcanePolarityRed) GoAgain(card.GameEngine) bool       { return false }

type ArcanePolarityYellow struct{}

func (ArcanePolarityYellow) ID() ids.CardID                     { return ids.ArcanePolarityYellow }
func (ArcanePolarityYellow) Name() string                       { return "Arcane Polarity" }
func (ArcanePolarityYellow) DisplayName() string                { return "Arcane Polarity [Y]" }
func (ArcanePolarityYellow) Rarity() string                     { return "Common" }
func (ArcanePolarityYellow) Cost() int                          { return 0 }
func (ArcanePolarityYellow) Pitch() int                         { return 2 }
func (ArcanePolarityYellow) Attack() int                        { return 0 }
func (ArcanePolarityYellow) Defense() int                       { return 0 }
func (ArcanePolarityYellow) Types(card.GameEngine) card.TypeSet { return arcanePolarityTypes }
func (ArcanePolarityYellow) GoAgain(card.GameEngine) bool       { return false }

type ArcanePolarityBlue struct{}

func (ArcanePolarityBlue) ID() ids.CardID                     { return ids.ArcanePolarityBlue }
func (ArcanePolarityBlue) Name() string                       { return "Arcane Polarity" }
func (ArcanePolarityBlue) DisplayName() string                { return "Arcane Polarity [B]" }
func (ArcanePolarityBlue) Rarity() string                     { return "Common" }
func (ArcanePolarityBlue) Cost() int                          { return 0 }
func (ArcanePolarityBlue) Pitch() int                         { return 3 }
func (ArcanePolarityBlue) Attack() int                        { return 0 }
func (ArcanePolarityBlue) Defense() int                       { return 0 }
func (ArcanePolarityBlue) Types(card.GameEngine) card.TypeSet { return arcanePolarityTypes }
func (ArcanePolarityBlue) GoAgain(card.GameEngine) bool       { return false }
