// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var bladeFlashTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAttackReaction)

type BladeFlashBlue struct{}

func (BladeFlashBlue) ID() ids.CardID                     { return ids.BladeFlashBlue }
func (BladeFlashBlue) Name() string                       { return "Blade Flash" }
func (BladeFlashBlue) DisplayName() string                { return "Blade Flash [B]" }
func (BladeFlashBlue) Rarity() string                     { return "Common" }
func (BladeFlashBlue) Cost() int                          { return 1 }
func (BladeFlashBlue) Pitch() int                         { return 3 }
func (BladeFlashBlue) Attack() int                        { return 0 }
func (BladeFlashBlue) Defense() int                       { return 2 }
func (BladeFlashBlue) Types(card.GameEngine) card.TypeSet { return bladeFlashTypes }
func (BladeFlashBlue) GoAgain(card.GameEngine) bool       { return false }
