// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var clearwaterElixirTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type ClearwaterElixirRed struct{}

func (ClearwaterElixirRed) ID() ids.CardID                     { return ids.ClearwaterElixirRed }
func (ClearwaterElixirRed) Name() string                       { return "Clearwater Elixir" }
func (ClearwaterElixirRed) DisplayName() string                { return "Clearwater Elixir [R]" }
func (ClearwaterElixirRed) Cost(card.GameEngine) int           { return 1 }
func (ClearwaterElixirRed) Pitch() int                         { return 1 }
func (ClearwaterElixirRed) Attack() int                        { return 0 }
func (ClearwaterElixirRed) Defense() int                       { return 3 }
func (ClearwaterElixirRed) Types(card.GameEngine) card.TypeSet { return clearwaterElixirTypes }
func (ClearwaterElixirRed) GoAgain(card.GameEngine) bool       { return true }
