// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var drawnToTheDarkDimensionTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction, card.TypeAttack)

type DrawnToTheDarkDimensionRed struct{}

func (DrawnToTheDarkDimensionRed) ID() ids.CardID      { return ids.DrawnToTheDarkDimensionRed }
func (DrawnToTheDarkDimensionRed) Name() string        { return "Drawn to the Dark Dimension" }
func (DrawnToTheDarkDimensionRed) DisplayName() string { return "Drawn to the Dark Dimension [R]" }
func (DrawnToTheDarkDimensionRed) Cost() int           { return 2 }
func (DrawnToTheDarkDimensionRed) Pitch() int          { return 1 }
func (DrawnToTheDarkDimensionRed) Attack() int         { return 3 }
func (DrawnToTheDarkDimensionRed) Defense() int        { return 3 }
func (DrawnToTheDarkDimensionRed) Types(card.GameEngine) card.TypeSet {
	return drawnToTheDarkDimensionTypes
}
func (DrawnToTheDarkDimensionRed) GoAgain(card.GameEngine) bool { return false }

type DrawnToTheDarkDimensionYellow struct{}

func (DrawnToTheDarkDimensionYellow) ID() ids.CardID      { return ids.DrawnToTheDarkDimensionYellow }
func (DrawnToTheDarkDimensionYellow) Name() string        { return "Drawn to the Dark Dimension" }
func (DrawnToTheDarkDimensionYellow) DisplayName() string { return "Drawn to the Dark Dimension [Y]" }
func (DrawnToTheDarkDimensionYellow) Cost() int           { return 2 }
func (DrawnToTheDarkDimensionYellow) Pitch() int          { return 2 }
func (DrawnToTheDarkDimensionYellow) Attack() int         { return 2 }
func (DrawnToTheDarkDimensionYellow) Defense() int        { return 3 }
func (DrawnToTheDarkDimensionYellow) Types(card.GameEngine) card.TypeSet {
	return drawnToTheDarkDimensionTypes
}
func (DrawnToTheDarkDimensionYellow) GoAgain(card.GameEngine) bool { return false }

type DrawnToTheDarkDimensionBlue struct{}

func (DrawnToTheDarkDimensionBlue) ID() ids.CardID      { return ids.DrawnToTheDarkDimensionBlue }
func (DrawnToTheDarkDimensionBlue) Name() string        { return "Drawn to the Dark Dimension" }
func (DrawnToTheDarkDimensionBlue) DisplayName() string { return "Drawn to the Dark Dimension [B]" }
func (DrawnToTheDarkDimensionBlue) Cost() int           { return 2 }
func (DrawnToTheDarkDimensionBlue) Pitch() int          { return 3 }
func (DrawnToTheDarkDimensionBlue) Attack() int         { return 1 }
func (DrawnToTheDarkDimensionBlue) Defense() int        { return 3 }
func (DrawnToTheDarkDimensionBlue) Types(card.GameEngine) card.TypeSet {
	return drawnToTheDarkDimensionTypes
}
func (DrawnToTheDarkDimensionBlue) GoAgain(card.GameEngine) bool { return false }
