// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var drowningDireTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction, card.TypeAttack)

type DrowningDireRed struct{}

func (DrowningDireRed) ID() ids.CardID                     { return ids.DrowningDireRed }
func (DrowningDireRed) Name() string                       { return "Drowning Dire" }
func (DrowningDireRed) DisplayName() string                { return "Drowning Dire [R]" }
func (DrowningDireRed) Cost() int                          { return 2 }
func (DrowningDireRed) Pitch() int                         { return 1 }
func (DrowningDireRed) Attack() int                        { return 5 }
func (DrowningDireRed) Defense() int                       { return 3 }
func (DrowningDireRed) Types(card.GameEngine) card.TypeSet { return drowningDireTypes }
func (DrowningDireRed) GoAgain(card.GameEngine) bool       { return false }

type DrowningDireYellow struct{}

func (DrowningDireYellow) ID() ids.CardID                     { return ids.DrowningDireYellow }
func (DrowningDireYellow) Name() string                       { return "Drowning Dire" }
func (DrowningDireYellow) DisplayName() string                { return "Drowning Dire [Y]" }
func (DrowningDireYellow) Cost() int                          { return 2 }
func (DrowningDireYellow) Pitch() int                         { return 2 }
func (DrowningDireYellow) Attack() int                        { return 4 }
func (DrowningDireYellow) Defense() int                       { return 3 }
func (DrowningDireYellow) Types(card.GameEngine) card.TypeSet { return drowningDireTypes }
func (DrowningDireYellow) GoAgain(card.GameEngine) bool       { return false }

type DrowningDireBlue struct{}

func (DrowningDireBlue) ID() ids.CardID                     { return ids.DrowningDireBlue }
func (DrowningDireBlue) Name() string                       { return "Drowning Dire" }
func (DrowningDireBlue) DisplayName() string                { return "Drowning Dire [B]" }
func (DrowningDireBlue) Cost() int                          { return 2 }
func (DrowningDireBlue) Pitch() int                         { return 3 }
func (DrowningDireBlue) Attack() int                        { return 3 }
func (DrowningDireBlue) Defense() int                       { return 3 }
func (DrowningDireBlue) Types(card.GameEngine) card.TypeSet { return drowningDireTypes }
func (DrowningDireBlue) GoAgain(card.GameEngine) bool       { return false }
