// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var emissaryOfWindTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type EmissaryOfWindRed struct{}

func (EmissaryOfWindRed) ID() ids.CardID                     { return ids.EmissaryOfWindRed }
func (EmissaryOfWindRed) Name() string                       { return "Emissary of Wind" }
func (EmissaryOfWindRed) DisplayName() string                { return "Emissary of Wind [R]" }
func (EmissaryOfWindRed) Cost() int                          { return 0 }
func (EmissaryOfWindRed) Pitch() int                         { return 1 }
func (EmissaryOfWindRed) Attack() int                        { return 4 }
func (EmissaryOfWindRed) Defense() int                       { return 2 }
func (EmissaryOfWindRed) Types(card.GameEngine) card.TypeSet { return emissaryOfWindTypes }
func (EmissaryOfWindRed) GoAgain(card.GameEngine) bool       { return false }
