// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var fateForeseenTypes = card.NewTypeSet(card.TypeGeneric, card.TypeDefenseReaction)

type FateForeseenRed struct{}

func (FateForeseenRed) ID() ids.CardID                     { return ids.FateForeseenRed }
func (FateForeseenRed) Name() string                       { return "Fate Foreseen" }
func (FateForeseenRed) DisplayName() string                { return "Fate Foreseen [R]" }
func (FateForeseenRed) Cost(card.GameEngine) int           { return 0 }
func (FateForeseenRed) Pitch() int                         { return 1 }
func (FateForeseenRed) Attack() int                        { return 0 }
func (FateForeseenRed) Defense() int                       { return 4 }
func (FateForeseenRed) Types(card.GameEngine) card.TypeSet { return fateForeseenTypes }
func (FateForeseenRed) GoAgain(card.GameEngine) bool       { return false }
func (FateForeseenRed) NotSilverAgeLegal()                 {}

type FateForeseenYellow struct{}

func (FateForeseenYellow) ID() ids.CardID                     { return ids.FateForeseenYellow }
func (FateForeseenYellow) Name() string                       { return "Fate Foreseen" }
func (FateForeseenYellow) DisplayName() string                { return "Fate Foreseen [Y]" }
func (FateForeseenYellow) Cost(card.GameEngine) int           { return 0 }
func (FateForeseenYellow) Pitch() int                         { return 2 }
func (FateForeseenYellow) Attack() int                        { return 0 }
func (FateForeseenYellow) Defense() int                       { return 3 }
func (FateForeseenYellow) Types(card.GameEngine) card.TypeSet { return fateForeseenTypes }
func (FateForeseenYellow) GoAgain(card.GameEngine) bool       { return false }
func (FateForeseenYellow) NotSilverAgeLegal()                 {}

type FateForeseenBlue struct{}

func (FateForeseenBlue) ID() ids.CardID                     { return ids.FateForeseenBlue }
func (FateForeseenBlue) Name() string                       { return "Fate Foreseen" }
func (FateForeseenBlue) DisplayName() string                { return "Fate Foreseen [B]" }
func (FateForeseenBlue) Cost(card.GameEngine) int           { return 0 }
func (FateForeseenBlue) Pitch() int                         { return 3 }
func (FateForeseenBlue) Attack() int                        { return 0 }
func (FateForeseenBlue) Defense() int                       { return 2 }
func (FateForeseenBlue) Types(card.GameEngine) card.TypeSet { return fateForeseenTypes }
func (FateForeseenBlue) GoAgain(card.GameEngine) bool       { return false }
func (FateForeseenBlue) NotSilverAgeLegal()                 {}
