// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var freewheelingRenegadesTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type FreewheelingRenegadesRed struct{}

func (FreewheelingRenegadesRed) ID() ids.CardID      { return ids.FreewheelingRenegadesRed }
func (FreewheelingRenegadesRed) Name() string        { return "Freewheeling Renegades" }
func (FreewheelingRenegadesRed) DisplayName() string { return "Freewheeling Renegades [R]" }
func (FreewheelingRenegadesRed) Rarity() string      { return "Common" }
func (FreewheelingRenegadesRed) Cost() int           { return 1 }
func (FreewheelingRenegadesRed) Pitch() int          { return 1 }
func (FreewheelingRenegadesRed) Attack() int         { return 6 }
func (FreewheelingRenegadesRed) Defense() int        { return 2 }
func (FreewheelingRenegadesRed) Types(card.GameEngine) card.TypeSet {
	return freewheelingRenegadesTypes
}
func (FreewheelingRenegadesRed) GoAgain(card.GameEngine) bool { return false }

type FreewheelingRenegadesYellow struct{}

func (FreewheelingRenegadesYellow) ID() ids.CardID      { return ids.FreewheelingRenegadesYellow }
func (FreewheelingRenegadesYellow) Name() string        { return "Freewheeling Renegades" }
func (FreewheelingRenegadesYellow) DisplayName() string { return "Freewheeling Renegades [Y]" }
func (FreewheelingRenegadesYellow) Rarity() string      { return "Common" }
func (FreewheelingRenegadesYellow) Cost() int           { return 1 }
func (FreewheelingRenegadesYellow) Pitch() int          { return 2 }
func (FreewheelingRenegadesYellow) Attack() int         { return 5 }
func (FreewheelingRenegadesYellow) Defense() int        { return 2 }
func (FreewheelingRenegadesYellow) Types(card.GameEngine) card.TypeSet {
	return freewheelingRenegadesTypes
}
func (FreewheelingRenegadesYellow) GoAgain(card.GameEngine) bool { return false }

type FreewheelingRenegadesBlue struct{}

func (FreewheelingRenegadesBlue) ID() ids.CardID      { return ids.FreewheelingRenegadesBlue }
func (FreewheelingRenegadesBlue) Name() string        { return "Freewheeling Renegades" }
func (FreewheelingRenegadesBlue) DisplayName() string { return "Freewheeling Renegades [B]" }
func (FreewheelingRenegadesBlue) Rarity() string      { return "Common" }
func (FreewheelingRenegadesBlue) Cost() int           { return 1 }
func (FreewheelingRenegadesBlue) Pitch() int          { return 3 }
func (FreewheelingRenegadesBlue) Attack() int         { return 4 }
func (FreewheelingRenegadesBlue) Defense() int        { return 2 }
func (FreewheelingRenegadesBlue) Types(card.GameEngine) card.TypeSet {
	return freewheelingRenegadesTypes
}
func (FreewheelingRenegadesBlue) GoAgain(card.GameEngine) bool { return false }
