// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var handBehindThePenTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type HandBehindThePenRed struct{}

func (HandBehindThePenRed) ID() ids.CardID                     { return ids.HandBehindThePenRed }
func (HandBehindThePenRed) Name() string                       { return "Hand Behind the Pen" }
func (HandBehindThePenRed) DisplayName() string                { return "Hand Behind the Pen [R]" }
func (HandBehindThePenRed) Rarity() string                     { return "Rare" }
func (HandBehindThePenRed) Cost() int                          { return 2 }
func (HandBehindThePenRed) Pitch() int                         { return 1 }
func (HandBehindThePenRed) Attack() int                        { return 6 }
func (HandBehindThePenRed) Defense() int                       { return 2 }
func (HandBehindThePenRed) Types(card.GameEngine) card.TypeSet { return handBehindThePenTypes }
func (HandBehindThePenRed) GoAgain(card.GameEngine) bool       { return false }
