// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var imperialSealOfCommandTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type ImperialSealOfCommandRed struct{}

func (ImperialSealOfCommandRed) ID() ids.CardID      { return ids.ImperialSealOfCommandRed }
func (ImperialSealOfCommandRed) Name() string        { return "Imperial Seal of Command" }
func (ImperialSealOfCommandRed) DisplayName() string { return "Imperial Seal of Command [R]" }
func (ImperialSealOfCommandRed) Cost() int           { return 0 }
func (ImperialSealOfCommandRed) Pitch() int          { return 1 }
func (ImperialSealOfCommandRed) Attack() int         { return 0 }
func (ImperialSealOfCommandRed) Defense() int        { return 0 }
func (ImperialSealOfCommandRed) Types(card.GameEngine) card.TypeSet {
	return imperialSealOfCommandTypes
}
func (ImperialSealOfCommandRed) GoAgain(card.GameEngine) bool { return false }
func (ImperialSealOfCommandRed) Legendary()                   {}
