// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var infectiousHostTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type InfectiousHostRed struct{}

func (InfectiousHostRed) ID() ids.CardID                     { return ids.InfectiousHostRed }
func (InfectiousHostRed) Name() string                       { return "Infectious Host" }
func (InfectiousHostRed) DisplayName() string                { return "Infectious Host [R]" }
func (InfectiousHostRed) Cost() int                          { return 0 }
func (InfectiousHostRed) Pitch() int                         { return 1 }
func (InfectiousHostRed) Attack() int                        { return 4 }
func (InfectiousHostRed) Defense() int                       { return 2 }
func (InfectiousHostRed) Types(card.GameEngine) card.TypeSet { return infectiousHostTypes }
func (InfectiousHostRed) GoAgain(card.GameEngine) bool       { return false }

type InfectiousHostYellow struct{}

func (InfectiousHostYellow) ID() ids.CardID                     { return ids.InfectiousHostYellow }
func (InfectiousHostYellow) Name() string                       { return "Infectious Host" }
func (InfectiousHostYellow) DisplayName() string                { return "Infectious Host [Y]" }
func (InfectiousHostYellow) Cost() int                          { return 0 }
func (InfectiousHostYellow) Pitch() int                         { return 2 }
func (InfectiousHostYellow) Attack() int                        { return 3 }
func (InfectiousHostYellow) Defense() int                       { return 2 }
func (InfectiousHostYellow) Types(card.GameEngine) card.TypeSet { return infectiousHostTypes }
func (InfectiousHostYellow) GoAgain(card.GameEngine) bool       { return false }

type InfectiousHostBlue struct{}

func (InfectiousHostBlue) ID() ids.CardID                     { return ids.InfectiousHostBlue }
func (InfectiousHostBlue) Name() string                       { return "Infectious Host" }
func (InfectiousHostBlue) DisplayName() string                { return "Infectious Host [B]" }
func (InfectiousHostBlue) Cost() int                          { return 0 }
func (InfectiousHostBlue) Pitch() int                         { return 3 }
func (InfectiousHostBlue) Attack() int                        { return 2 }
func (InfectiousHostBlue) Defense() int                       { return 2 }
func (InfectiousHostBlue) Types(card.GameEngine) card.TypeSet { return infectiousHostTypes }
func (InfectiousHostBlue) GoAgain(card.GameEngine) bool       { return false }
