// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var layLowTypes = card.NewTypeSet(card.TypeGeneric, card.TypeDefenseReaction)

type LayLowYellow struct{}

func (LayLowYellow) ID() ids.CardID                     { return ids.LayLowYellow }
func (LayLowYellow) Name() string                       { return "Lay Low" }
func (LayLowYellow) DisplayName() string                { return "Lay Low [Y]" }
func (LayLowYellow) Cost() int                          { return 0 }
func (LayLowYellow) Pitch() int                         { return 2 }
func (LayLowYellow) Attack() int                        { return 0 }
func (LayLowYellow) Defense() int                       { return 3 }
func (LayLowYellow) Types(card.GameEngine) card.TypeSet { return layLowTypes }
func (LayLowYellow) GoAgain(card.GameEngine) bool       { return false }
