// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var lifeForALifeTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type LifeForALifeRed struct{}

func (LifeForALifeRed) ID() ids.CardID                     { return ids.LifeForALifeRed }
func (LifeForALifeRed) Name() string                       { return "Life for a Life" }
func (LifeForALifeRed) DisplayName() string                { return "Life for a Life [R]" }
func (LifeForALifeRed) Cost(card.GameEngine) int           { return 1 }
func (LifeForALifeRed) Pitch() int                         { return 1 }
func (LifeForALifeRed) Attack() int                        { return 4 }
func (LifeForALifeRed) Defense() int                       { return 2 }
func (LifeForALifeRed) Types(card.GameEngine) card.TypeSet { return lifeForALifeTypes }

type LifeForALifeYellow struct{}

func (LifeForALifeYellow) ID() ids.CardID                     { return ids.LifeForALifeYellow }
func (LifeForALifeYellow) Name() string                       { return "Life for a Life" }
func (LifeForALifeYellow) DisplayName() string                { return "Life for a Life [Y]" }
func (LifeForALifeYellow) Cost(card.GameEngine) int           { return 1 }
func (LifeForALifeYellow) Pitch() int                         { return 2 }
func (LifeForALifeYellow) Attack() int                        { return 3 }
func (LifeForALifeYellow) Defense() int                       { return 2 }
func (LifeForALifeYellow) Types(card.GameEngine) card.TypeSet { return lifeForALifeTypes }

type LifeForALifeBlue struct{}

func (LifeForALifeBlue) ID() ids.CardID                     { return ids.LifeForALifeBlue }
func (LifeForALifeBlue) Name() string                       { return "Life for a Life" }
func (LifeForALifeBlue) DisplayName() string                { return "Life for a Life [B]" }
func (LifeForALifeBlue) Cost(card.GameEngine) int           { return 1 }
func (LifeForALifeBlue) Pitch() int                         { return 3 }
func (LifeForALifeBlue) Attack() int                        { return 2 }
func (LifeForALifeBlue) Defense() int                       { return 2 }
func (LifeForALifeBlue) Types(card.GameEngine) card.TypeSet { return lifeForALifeTypes }
