// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var lungingPressTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAttackReaction)

type LungingPressBlue struct{}

func (LungingPressBlue) ID() ids.CardID                     { return ids.LungingPressBlue }
func (LungingPressBlue) Name() string                       { return "Lunging Press" }
func (LungingPressBlue) DisplayName() string                { return "Lunging Press [B]" }
func (LungingPressBlue) Rarity() string                     { return "Common" }
func (LungingPressBlue) Cost() int                          { return 0 }
func (LungingPressBlue) Pitch() int                         { return 3 }
func (LungingPressBlue) Attack() int                        { return 0 }
func (LungingPressBlue) Defense() int                       { return 2 }
func (LungingPressBlue) Types(card.GameEngine) card.TypeSet { return lungingPressTypes }
func (LungingPressBlue) GoAgain(card.GameEngine) bool       { return false }
