// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var mauvrionSkiesTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction)

type MauvrionSkiesRed struct{}

func (MauvrionSkiesRed) ID() ids.CardID                     { return ids.MauvrionSkiesRed }
func (MauvrionSkiesRed) Name() string                       { return "Mauvrion Skies" }
func (MauvrionSkiesRed) DisplayName() string                { return "Mauvrion Skies [R]" }
func (MauvrionSkiesRed) Cost(card.GameEngine) int           { return 0 }
func (MauvrionSkiesRed) Pitch() int                         { return 1 }
func (MauvrionSkiesRed) Attack() int                        { return 0 }
func (MauvrionSkiesRed) Defense() int                       { return 2 }
func (MauvrionSkiesRed) Types(card.GameEngine) card.TypeSet { return mauvrionSkiesTypes }
func (MauvrionSkiesRed) GoAgain(card.GameEngine) bool       { return true }

type MauvrionSkiesYellow struct{}

func (MauvrionSkiesYellow) ID() ids.CardID                     { return ids.MauvrionSkiesYellow }
func (MauvrionSkiesYellow) Name() string                       { return "Mauvrion Skies" }
func (MauvrionSkiesYellow) DisplayName() string                { return "Mauvrion Skies [Y]" }
func (MauvrionSkiesYellow) Cost(card.GameEngine) int           { return 0 }
func (MauvrionSkiesYellow) Pitch() int                         { return 2 }
func (MauvrionSkiesYellow) Attack() int                        { return 0 }
func (MauvrionSkiesYellow) Defense() int                       { return 2 }
func (MauvrionSkiesYellow) Types(card.GameEngine) card.TypeSet { return mauvrionSkiesTypes }
func (MauvrionSkiesYellow) GoAgain(card.GameEngine) bool       { return true }

type MauvrionSkiesBlue struct{}

func (MauvrionSkiesBlue) ID() ids.CardID                     { return ids.MauvrionSkiesBlue }
func (MauvrionSkiesBlue) Name() string                       { return "Mauvrion Skies" }
func (MauvrionSkiesBlue) DisplayName() string                { return "Mauvrion Skies [B]" }
func (MauvrionSkiesBlue) Cost(card.GameEngine) int           { return 0 }
func (MauvrionSkiesBlue) Pitch() int                         { return 3 }
func (MauvrionSkiesBlue) Attack() int                        { return 0 }
func (MauvrionSkiesBlue) Defense() int                       { return 2 }
func (MauvrionSkiesBlue) Types(card.GameEngine) card.TypeSet { return mauvrionSkiesTypes }
func (MauvrionSkiesBlue) GoAgain(card.GameEngine) bool       { return true }
