// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var moneyOrYourLifeTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type MoneyOrYourLifeRed struct{}

func (MoneyOrYourLifeRed) ID() ids.CardID                     { return ids.MoneyOrYourLifeRed }
func (MoneyOrYourLifeRed) Name() string                       { return "Money or Your Life?" }
func (MoneyOrYourLifeRed) DisplayName() string                { return "Money or Your Life? [R]" }
func (MoneyOrYourLifeRed) Cost() int                          { return 3 }
func (MoneyOrYourLifeRed) Pitch() int                         { return 1 }
func (MoneyOrYourLifeRed) Attack() int                        { return 6 }
func (MoneyOrYourLifeRed) Defense() int                       { return 2 }
func (MoneyOrYourLifeRed) Types(card.GameEngine) card.TypeSet { return moneyOrYourLifeTypes }
func (MoneyOrYourLifeRed) GoAgain(card.GameEngine) bool       { return false }

type MoneyOrYourLifeYellow struct{}

func (MoneyOrYourLifeYellow) ID() ids.CardID                     { return ids.MoneyOrYourLifeYellow }
func (MoneyOrYourLifeYellow) Name() string                       { return "Money or Your Life?" }
func (MoneyOrYourLifeYellow) DisplayName() string                { return "Money or Your Life? [Y]" }
func (MoneyOrYourLifeYellow) Cost() int                          { return 3 }
func (MoneyOrYourLifeYellow) Pitch() int                         { return 2 }
func (MoneyOrYourLifeYellow) Attack() int                        { return 5 }
func (MoneyOrYourLifeYellow) Defense() int                       { return 2 }
func (MoneyOrYourLifeYellow) Types(card.GameEngine) card.TypeSet { return moneyOrYourLifeTypes }
func (MoneyOrYourLifeYellow) GoAgain(card.GameEngine) bool       { return false }

type MoneyOrYourLifeBlue struct{}

func (MoneyOrYourLifeBlue) ID() ids.CardID                     { return ids.MoneyOrYourLifeBlue }
func (MoneyOrYourLifeBlue) Name() string                       { return "Money or Your Life?" }
func (MoneyOrYourLifeBlue) DisplayName() string                { return "Money or Your Life? [B]" }
func (MoneyOrYourLifeBlue) Cost() int                          { return 3 }
func (MoneyOrYourLifeBlue) Pitch() int                         { return 3 }
func (MoneyOrYourLifeBlue) Attack() int                        { return 4 }
func (MoneyOrYourLifeBlue) Defense() int                       { return 2 }
func (MoneyOrYourLifeBlue) Types(card.GameEngine) card.TypeSet { return moneyOrYourLifeTypes }
func (MoneyOrYourLifeBlue) GoAgain(card.GameEngine) bool       { return false }
