// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var publicBountyTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type PublicBountyRed struct{}

func (PublicBountyRed) ID() ids.CardID                     { return ids.PublicBountyRed }
func (PublicBountyRed) Name() string                       { return "Public Bounty" }
func (PublicBountyRed) DisplayName() string                { return "Public Bounty [R]" }
func (PublicBountyRed) Rarity() string                     { return "Common" }
func (PublicBountyRed) Cost() int                          { return 1 }
func (PublicBountyRed) Pitch() int                         { return 1 }
func (PublicBountyRed) Attack() int                        { return 0 }
func (PublicBountyRed) Defense() int                       { return 2 }
func (PublicBountyRed) Types(card.GameEngine) card.TypeSet { return publicBountyTypes }
func (PublicBountyRed) GoAgain(card.GameEngine) bool       { return true }

type PublicBountyYellow struct{}

func (PublicBountyYellow) ID() ids.CardID                     { return ids.PublicBountyYellow }
func (PublicBountyYellow) Name() string                       { return "Public Bounty" }
func (PublicBountyYellow) DisplayName() string                { return "Public Bounty [Y]" }
func (PublicBountyYellow) Rarity() string                     { return "Common" }
func (PublicBountyYellow) Cost() int                          { return 1 }
func (PublicBountyYellow) Pitch() int                         { return 2 }
func (PublicBountyYellow) Attack() int                        { return 0 }
func (PublicBountyYellow) Defense() int                       { return 2 }
func (PublicBountyYellow) Types(card.GameEngine) card.TypeSet { return publicBountyTypes }
func (PublicBountyYellow) GoAgain(card.GameEngine) bool       { return true }

type PublicBountyBlue struct{}

func (PublicBountyBlue) ID() ids.CardID                     { return ids.PublicBountyBlue }
func (PublicBountyBlue) Name() string                       { return "Public Bounty" }
func (PublicBountyBlue) DisplayName() string                { return "Public Bounty [B]" }
func (PublicBountyBlue) Rarity() string                     { return "Common" }
func (PublicBountyBlue) Cost() int                          { return 1 }
func (PublicBountyBlue) Pitch() int                         { return 3 }
func (PublicBountyBlue) Attack() int                        { return 0 }
func (PublicBountyBlue) Defense() int                       { return 2 }
func (PublicBountyBlue) Types(card.GameEngine) card.TypeSet { return publicBountyTypes }
func (PublicBountyBlue) GoAgain(card.GameEngine) bool       { return true }
