// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var punchAboveYourWeightTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type PunchAboveYourWeightRed struct{}

func (PunchAboveYourWeightRed) ID() ids.CardID                     { return ids.PunchAboveYourWeightRed }
func (PunchAboveYourWeightRed) Name() string                       { return "Punch Above Your Weight" }
func (PunchAboveYourWeightRed) DisplayName() string                { return "Punch Above Your Weight [R]" }
func (PunchAboveYourWeightRed) Rarity() string                     { return "Rare" }
func (PunchAboveYourWeightRed) Cost() int                          { return 0 }
func (PunchAboveYourWeightRed) Pitch() int                         { return 1 }
func (PunchAboveYourWeightRed) Attack() int                        { return 2 }
func (PunchAboveYourWeightRed) Defense() int                       { return 2 }
func (PunchAboveYourWeightRed) Types(card.GameEngine) card.TypeSet { return punchAboveYourWeightTypes }
func (PunchAboveYourWeightRed) GoAgain(card.GameEngine) bool       { return false }

type PunchAboveYourWeightYellow struct{}

func (PunchAboveYourWeightYellow) ID() ids.CardID      { return ids.PunchAboveYourWeightYellow }
func (PunchAboveYourWeightYellow) Name() string        { return "Punch Above Your Weight" }
func (PunchAboveYourWeightYellow) DisplayName() string { return "Punch Above Your Weight [Y]" }
func (PunchAboveYourWeightYellow) Rarity() string      { return "Rare" }
func (PunchAboveYourWeightYellow) Cost() int           { return 0 }
func (PunchAboveYourWeightYellow) Pitch() int          { return 2 }
func (PunchAboveYourWeightYellow) Attack() int         { return 2 }
func (PunchAboveYourWeightYellow) Defense() int        { return 2 }
func (PunchAboveYourWeightYellow) Types(card.GameEngine) card.TypeSet {
	return punchAboveYourWeightTypes
}
func (PunchAboveYourWeightYellow) GoAgain(card.GameEngine) bool { return false }

type PunchAboveYourWeightBlue struct{}

func (PunchAboveYourWeightBlue) ID() ids.CardID                     { return ids.PunchAboveYourWeightBlue }
func (PunchAboveYourWeightBlue) Name() string                       { return "Punch Above Your Weight" }
func (PunchAboveYourWeightBlue) DisplayName() string                { return "Punch Above Your Weight [B]" }
func (PunchAboveYourWeightBlue) Rarity() string                     { return "Rare" }
func (PunchAboveYourWeightBlue) Cost() int                          { return 0 }
func (PunchAboveYourWeightBlue) Pitch() int                         { return 3 }
func (PunchAboveYourWeightBlue) Attack() int                        { return 2 }
func (PunchAboveYourWeightBlue) Defense() int                       { return 2 }
func (PunchAboveYourWeightBlue) Types(card.GameEngine) card.TypeSet { return punchAboveYourWeightTypes }
func (PunchAboveYourWeightBlue) GoAgain(card.GameEngine) bool       { return false }
