// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var rallyTheRearguardTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type RallyTheRearguardRed struct{}

func (RallyTheRearguardRed) ID() ids.CardID                     { return ids.RallyTheRearguardRed }
func (RallyTheRearguardRed) Name() string                       { return "Rally the Rearguard" }
func (RallyTheRearguardRed) DisplayName() string                { return "Rally the Rearguard [R]" }
func (RallyTheRearguardRed) Rarity() string                     { return "Common" }
func (RallyTheRearguardRed) Cost() int                          { return 2 }
func (RallyTheRearguardRed) Pitch() int                         { return 1 }
func (RallyTheRearguardRed) Attack() int                        { return 6 }
func (RallyTheRearguardRed) Defense() int                       { return 2 }
func (RallyTheRearguardRed) Types(card.GameEngine) card.TypeSet { return rallyTheRearguardTypes }
func (RallyTheRearguardRed) GoAgain(card.GameEngine) bool       { return false }

type RallyTheRearguardYellow struct{}

func (RallyTheRearguardYellow) ID() ids.CardID                     { return ids.RallyTheRearguardYellow }
func (RallyTheRearguardYellow) Name() string                       { return "Rally the Rearguard" }
func (RallyTheRearguardYellow) DisplayName() string                { return "Rally the Rearguard [Y]" }
func (RallyTheRearguardYellow) Rarity() string                     { return "Common" }
func (RallyTheRearguardYellow) Cost() int                          { return 2 }
func (RallyTheRearguardYellow) Pitch() int                         { return 2 }
func (RallyTheRearguardYellow) Attack() int                        { return 5 }
func (RallyTheRearguardYellow) Defense() int                       { return 2 }
func (RallyTheRearguardYellow) Types(card.GameEngine) card.TypeSet { return rallyTheRearguardTypes }
func (RallyTheRearguardYellow) GoAgain(card.GameEngine) bool       { return false }

type RallyTheRearguardBlue struct{}

func (RallyTheRearguardBlue) ID() ids.CardID                     { return ids.RallyTheRearguardBlue }
func (RallyTheRearguardBlue) Name() string                       { return "Rally the Rearguard" }
func (RallyTheRearguardBlue) DisplayName() string                { return "Rally the Rearguard [B]" }
func (RallyTheRearguardBlue) Rarity() string                     { return "Common" }
func (RallyTheRearguardBlue) Cost() int                          { return 2 }
func (RallyTheRearguardBlue) Pitch() int                         { return 3 }
func (RallyTheRearguardBlue) Attack() int                        { return 4 }
func (RallyTheRearguardBlue) Defense() int                       { return 2 }
func (RallyTheRearguardBlue) Types(card.GameEngine) card.TypeSet { return rallyTheRearguardTypes }
func (RallyTheRearguardBlue) GoAgain(card.GameEngine) bool       { return false }
