// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var readTheRunesTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction)

type ReadTheRunesRed struct{}

func (ReadTheRunesRed) ID() ids.CardID                     { return ids.ReadTheRunesRed }
func (ReadTheRunesRed) Name() string                       { return "Read the Runes" }
func (ReadTheRunesRed) DisplayName() string                { return "Read the Runes [R]" }
func (ReadTheRunesRed) Rarity() string                     { return "Common" }
func (ReadTheRunesRed) Cost() int                          { return 0 }
func (ReadTheRunesRed) Pitch() int                         { return 1 }
func (ReadTheRunesRed) Attack() int                        { return 0 }
func (ReadTheRunesRed) Defense() int                       { return 2 }
func (ReadTheRunesRed) Types(card.GameEngine) card.TypeSet { return readTheRunesTypes }
func (ReadTheRunesRed) GoAgain(card.GameEngine) bool       { return false }

type ReadTheRunesYellow struct{}

func (ReadTheRunesYellow) ID() ids.CardID                     { return ids.ReadTheRunesYellow }
func (ReadTheRunesYellow) Name() string                       { return "Read the Runes" }
func (ReadTheRunesYellow) DisplayName() string                { return "Read the Runes [Y]" }
func (ReadTheRunesYellow) Rarity() string                     { return "Common" }
func (ReadTheRunesYellow) Cost() int                          { return 0 }
func (ReadTheRunesYellow) Pitch() int                         { return 2 }
func (ReadTheRunesYellow) Attack() int                        { return 0 }
func (ReadTheRunesYellow) Defense() int                       { return 2 }
func (ReadTheRunesYellow) Types(card.GameEngine) card.TypeSet { return readTheRunesTypes }
func (ReadTheRunesYellow) GoAgain(card.GameEngine) bool       { return false }

type ReadTheRunesBlue struct{}

func (ReadTheRunesBlue) ID() ids.CardID                     { return ids.ReadTheRunesBlue }
func (ReadTheRunesBlue) Name() string                       { return "Read the Runes" }
func (ReadTheRunesBlue) DisplayName() string                { return "Read the Runes [B]" }
func (ReadTheRunesBlue) Rarity() string                     { return "Common" }
func (ReadTheRunesBlue) Cost() int                          { return 0 }
func (ReadTheRunesBlue) Pitch() int                         { return 3 }
func (ReadTheRunesBlue) Attack() int                        { return 0 }
func (ReadTheRunesBlue) Defense() int                       { return 2 }
func (ReadTheRunesBlue) Types(card.GameEngine) card.TypeSet { return readTheRunesTypes }
func (ReadTheRunesBlue) GoAgain(card.GameEngine) bool       { return false }
