// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var restvineElixirTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type RestvineElixirRed struct{}

func (RestvineElixirRed) ID() ids.CardID                     { return ids.RestvineElixirRed }
func (RestvineElixirRed) Name() string                       { return "Restvine Elixir" }
func (RestvineElixirRed) DisplayName() string                { return "Restvine Elixir [R]" }
func (RestvineElixirRed) Cost(card.GameEngine) int           { return 1 }
func (RestvineElixirRed) Pitch() int                         { return 1 }
func (RestvineElixirRed) Attack() int                        { return 0 }
func (RestvineElixirRed) Defense() int                       { return 3 }
func (RestvineElixirRed) Types(card.GameEngine) card.TypeSet { return restvineElixirTypes }
func (RestvineElixirRed) GoAgain(card.GameEngine) bool       { return true }
