// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var spellbladeAssaultTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction, card.TypeAttack)

type SpellbladeAssaultRed struct{}

func (SpellbladeAssaultRed) ID() ids.CardID                     { return ids.SpellbladeAssaultRed }
func (SpellbladeAssaultRed) Name() string                       { return "Spellblade Assault" }
func (SpellbladeAssaultRed) DisplayName() string                { return "Spellblade Assault [R]" }
func (SpellbladeAssaultRed) Rarity() string                     { return "Rare" }
func (SpellbladeAssaultRed) Cost() int                          { return 2 }
func (SpellbladeAssaultRed) Pitch() int                         { return 1 }
func (SpellbladeAssaultRed) Attack() int                        { return 4 }
func (SpellbladeAssaultRed) Defense() int                       { return 3 }
func (SpellbladeAssaultRed) Types(card.GameEngine) card.TypeSet { return spellbladeAssaultTypes }
func (SpellbladeAssaultRed) GoAgain(card.GameEngine) bool       { return false }

type SpellbladeAssaultYellow struct{}

func (SpellbladeAssaultYellow) ID() ids.CardID                     { return ids.SpellbladeAssaultYellow }
func (SpellbladeAssaultYellow) Name() string                       { return "Spellblade Assault" }
func (SpellbladeAssaultYellow) DisplayName() string                { return "Spellblade Assault [Y]" }
func (SpellbladeAssaultYellow) Rarity() string                     { return "Rare" }
func (SpellbladeAssaultYellow) Cost() int                          { return 2 }
func (SpellbladeAssaultYellow) Pitch() int                         { return 2 }
func (SpellbladeAssaultYellow) Attack() int                        { return 3 }
func (SpellbladeAssaultYellow) Defense() int                       { return 3 }
func (SpellbladeAssaultYellow) Types(card.GameEngine) card.TypeSet { return spellbladeAssaultTypes }
func (SpellbladeAssaultYellow) GoAgain(card.GameEngine) bool       { return false }

type SpellbladeAssaultBlue struct{}

func (SpellbladeAssaultBlue) ID() ids.CardID                     { return ids.SpellbladeAssaultBlue }
func (SpellbladeAssaultBlue) Name() string                       { return "Spellblade Assault" }
func (SpellbladeAssaultBlue) DisplayName() string                { return "Spellblade Assault [B]" }
func (SpellbladeAssaultBlue) Rarity() string                     { return "Rare" }
func (SpellbladeAssaultBlue) Cost() int                          { return 2 }
func (SpellbladeAssaultBlue) Pitch() int                         { return 3 }
func (SpellbladeAssaultBlue) Attack() int                        { return 2 }
func (SpellbladeAssaultBlue) Defense() int                       { return 3 }
func (SpellbladeAssaultBlue) Types(card.GameEngine) card.TypeSet { return spellbladeAssaultTypes }
func (SpellbladeAssaultBlue) GoAgain(card.GameEngine) bool       { return false }
