// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var springboardSomersaultTypes = card.NewTypeSet(card.TypeGeneric, card.TypeDefenseReaction)

type SpringboardSomersaultYellow struct{}

func (SpringboardSomersaultYellow) ID() ids.CardID      { return ids.SpringboardSomersaultYellow }
func (SpringboardSomersaultYellow) Name() string        { return "Springboard Somersault" }
func (SpringboardSomersaultYellow) DisplayName() string { return "Springboard Somersault [Y]" }
func (SpringboardSomersaultYellow) Cost() int           { return 0 }
func (SpringboardSomersaultYellow) Pitch() int          { return 2 }
func (SpringboardSomersaultYellow) Attack() int         { return 0 }
func (SpringboardSomersaultYellow) Defense() int        { return 2 }
func (SpringboardSomersaultYellow) Types(card.GameEngine) card.TypeSet {
	return springboardSomersaultTypes
}
func (SpringboardSomersaultYellow) GoAgain(card.GameEngine) bool { return false }
