// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var stonyWoottonhogTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type StonyWoottonhogRed struct{}

func (StonyWoottonhogRed) ID() ids.CardID                     { return ids.StonyWoottonhogRed }
func (StonyWoottonhogRed) Name() string                       { return "Stony Woottonhog" }
func (StonyWoottonhogRed) DisplayName() string                { return "Stony Woottonhog [R]" }
func (StonyWoottonhogRed) Rarity() string                     { return "Common" }
func (StonyWoottonhogRed) Cost() int                          { return 2 }
func (StonyWoottonhogRed) Pitch() int                         { return 1 }
func (StonyWoottonhogRed) Attack() int                        { return 6 }
func (StonyWoottonhogRed) Defense() int                       { return 2 }
func (StonyWoottonhogRed) Types(card.GameEngine) card.TypeSet { return stonyWoottonhogTypes }
func (StonyWoottonhogRed) GoAgain(card.GameEngine) bool       { return false }

type StonyWoottonhogYellow struct{}

func (StonyWoottonhogYellow) ID() ids.CardID                     { return ids.StonyWoottonhogYellow }
func (StonyWoottonhogYellow) Name() string                       { return "Stony Woottonhog" }
func (StonyWoottonhogYellow) DisplayName() string                { return "Stony Woottonhog [Y]" }
func (StonyWoottonhogYellow) Rarity() string                     { return "Common" }
func (StonyWoottonhogYellow) Cost() int                          { return 2 }
func (StonyWoottonhogYellow) Pitch() int                         { return 2 }
func (StonyWoottonhogYellow) Attack() int                        { return 5 }
func (StonyWoottonhogYellow) Defense() int                       { return 2 }
func (StonyWoottonhogYellow) Types(card.GameEngine) card.TypeSet { return stonyWoottonhogTypes }
func (StonyWoottonhogYellow) GoAgain(card.GameEngine) bool       { return false }

type StonyWoottonhogBlue struct{}

func (StonyWoottonhogBlue) ID() ids.CardID                     { return ids.StonyWoottonhogBlue }
func (StonyWoottonhogBlue) Name() string                       { return "Stony Woottonhog" }
func (StonyWoottonhogBlue) DisplayName() string                { return "Stony Woottonhog [B]" }
func (StonyWoottonhogBlue) Rarity() string                     { return "Common" }
func (StonyWoottonhogBlue) Cost() int                          { return 2 }
func (StonyWoottonhogBlue) Pitch() int                         { return 3 }
func (StonyWoottonhogBlue) Attack() int                        { return 4 }
func (StonyWoottonhogBlue) Defense() int                       { return 2 }
func (StonyWoottonhogBlue) Types(card.GameEngine) card.TypeSet { return stonyWoottonhogTypes }
func (StonyWoottonhogBlue) GoAgain(card.GameEngine) bool       { return false }
