// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var talismanOfRecompenseTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type TalismanOfRecompenseYellow struct{}

func (TalismanOfRecompenseYellow) ID() ids.CardID      { return ids.TalismanOfRecompenseYellow }
func (TalismanOfRecompenseYellow) Name() string        { return "Talisman of Recompense" }
func (TalismanOfRecompenseYellow) DisplayName() string { return "Talisman of Recompense [Y]" }
func (TalismanOfRecompenseYellow) Rarity() string      { return "Rare" }
func (TalismanOfRecompenseYellow) Cost() int           { return 0 }
func (TalismanOfRecompenseYellow) Pitch() int          { return 2 }
func (TalismanOfRecompenseYellow) Attack() int         { return 0 }
func (TalismanOfRecompenseYellow) Defense() int        { return 0 }
func (TalismanOfRecompenseYellow) Types(card.GameEngine) card.TypeSet {
	return talismanOfRecompenseTypes
}
func (TalismanOfRecompenseYellow) GoAgain(card.GameEngine) bool { return true }
