// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var thrustTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAttackReaction)

type ThrustRed struct{}

func (ThrustRed) ID() ids.CardID                     { return ids.ThrustRed }
func (ThrustRed) Name() string                       { return "Thrust" }
func (ThrustRed) DisplayName() string                { return "Thrust [R]" }
func (ThrustRed) Rarity() string                     { return "Common" }
func (ThrustRed) Cost() int                          { return 1 }
func (ThrustRed) Pitch() int                         { return 1 }
func (ThrustRed) Attack() int                        { return 0 }
func (ThrustRed) Defense() int                       { return 2 }
func (ThrustRed) Types(card.GameEngine) card.TypeSet { return thrustTypes }
func (ThrustRed) GoAgain(card.GameEngine) bool       { return false }
