// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var tipOffTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type TipOffRed struct{}

func (TipOffRed) ID() ids.CardID                     { return ids.TipOffRed }
func (TipOffRed) Name() string                       { return "Tip-Off" }
func (TipOffRed) DisplayName() string                { return "Tip-Off [R]" }
func (TipOffRed) Rarity() string                     { return "Common" }
func (TipOffRed) Cost() int                          { return 1 }
func (TipOffRed) Pitch() int                         { return 1 }
func (TipOffRed) Attack() int                        { return 5 }
func (TipOffRed) Defense() int                       { return 2 }
func (TipOffRed) Types(card.GameEngine) card.TypeSet { return tipOffTypes }
func (TipOffRed) GoAgain(card.GameEngine) bool       { return false }

type TipOffYellow struct{}

func (TipOffYellow) ID() ids.CardID                     { return ids.TipOffYellow }
func (TipOffYellow) Name() string                       { return "Tip-Off" }
func (TipOffYellow) DisplayName() string                { return "Tip-Off [Y]" }
func (TipOffYellow) Rarity() string                     { return "Common" }
func (TipOffYellow) Cost() int                          { return 1 }
func (TipOffYellow) Pitch() int                         { return 2 }
func (TipOffYellow) Attack() int                        { return 4 }
func (TipOffYellow) Defense() int                       { return 2 }
func (TipOffYellow) Types(card.GameEngine) card.TypeSet { return tipOffTypes }
func (TipOffYellow) GoAgain(card.GameEngine) bool       { return false }

type TipOffBlue struct{}

func (TipOffBlue) ID() ids.CardID                     { return ids.TipOffBlue }
func (TipOffBlue) Name() string                       { return "Tip-Off" }
func (TipOffBlue) DisplayName() string                { return "Tip-Off [B]" }
func (TipOffBlue) Rarity() string                     { return "Common" }
func (TipOffBlue) Cost() int                          { return 1 }
func (TipOffBlue) Pitch() int                         { return 3 }
func (TipOffBlue) Attack() int                        { return 3 }
func (TipOffBlue) Defense() int                       { return 2 }
func (TipOffBlue) Types(card.GameEngine) card.TypeSet { return tipOffTypes }
func (TipOffBlue) GoAgain(card.GameEngine) bool       { return false }
