// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var titForTatTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type TitForTatBlue struct{}

func (TitForTatBlue) ID() ids.CardID                     { return ids.TitForTatBlue }
func (TitForTatBlue) Name() string                       { return "Tit for Tat" }
func (TitForTatBlue) DisplayName() string                { return "Tit for Tat [B]" }
func (TitForTatBlue) Cost() int                          { return 0 }
func (TitForTatBlue) Pitch() int                         { return 3 }
func (TitForTatBlue) Attack() int                        { return 0 }
func (TitForTatBlue) Defense() int                       { return 2 }
func (TitForTatBlue) Types(card.GameEngine) card.TypeSet { return titForTatTypes }
func (TitForTatBlue) GoAgain(card.GameEngine) bool       { return true }
