// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var tremorOfArathaelTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type TremorOfIArathaelRed struct{}

func (TremorOfIArathaelRed) ID() ids.CardID                     { return ids.TremorOfIArathaelRed }
func (TremorOfIArathaelRed) Name() string                       { return "Tremor of íArathael" }
func (TremorOfIArathaelRed) DisplayName() string                { return "Tremor of íArathael [R]" }
func (TremorOfIArathaelRed) Rarity() string                     { return "Rare" }
func (TremorOfIArathaelRed) Cost() int                          { return 1 }
func (TremorOfIArathaelRed) Pitch() int                         { return 1 }
func (TremorOfIArathaelRed) Attack() int                        { return 4 }
func (TremorOfIArathaelRed) Defense() int                       { return 2 }
func (TremorOfIArathaelRed) Types(card.GameEngine) card.TypeSet { return tremorOfArathaelTypes }
func (TremorOfIArathaelRed) GoAgain(card.GameEngine) bool       { return false }

type TremorOfIArathaelYellow struct{}

func (TremorOfIArathaelYellow) ID() ids.CardID                     { return ids.TremorOfIArathaelYellow }
func (TremorOfIArathaelYellow) Name() string                       { return "Tremor of íArathael" }
func (TremorOfIArathaelYellow) DisplayName() string                { return "Tremor of íArathael [Y]" }
func (TremorOfIArathaelYellow) Rarity() string                     { return "Rare" }
func (TremorOfIArathaelYellow) Cost() int                          { return 1 }
func (TremorOfIArathaelYellow) Pitch() int                         { return 2 }
func (TremorOfIArathaelYellow) Attack() int                        { return 3 }
func (TremorOfIArathaelYellow) Defense() int                       { return 2 }
func (TremorOfIArathaelYellow) Types(card.GameEngine) card.TypeSet { return tremorOfArathaelTypes }
func (TremorOfIArathaelYellow) GoAgain(card.GameEngine) bool       { return false }

type TremorOfIArathaelBlue struct{}

func (TremorOfIArathaelBlue) ID() ids.CardID                     { return ids.TremorOfIArathaelBlue }
func (TremorOfIArathaelBlue) Name() string                       { return "Tremor of íArathael" }
func (TremorOfIArathaelBlue) DisplayName() string                { return "Tremor of íArathael [B]" }
func (TremorOfIArathaelBlue) Rarity() string                     { return "Rare" }
func (TremorOfIArathaelBlue) Cost() int                          { return 1 }
func (TremorOfIArathaelBlue) Pitch() int                         { return 3 }
func (TremorOfIArathaelBlue) Attack() int                        { return 2 }
func (TremorOfIArathaelBlue) Defense() int                       { return 2 }
func (TremorOfIArathaelBlue) Types(card.GameEngine) card.TypeSet { return tremorOfArathaelTypes }
func (TremorOfIArathaelBlue) GoAgain(card.GameEngine) bool       { return false }
