// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var vantagePointTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction, card.TypeAttack)

type VantagePointRed struct{}

func (VantagePointRed) ID() ids.CardID                     { return ids.VantagePointRed }
func (VantagePointRed) Name() string                       { return "Vantage Point" }
func (VantagePointRed) DisplayName() string                { return "Vantage Point [R]" }
func (VantagePointRed) Cost() int                          { return 3 }
func (VantagePointRed) Pitch() int                         { return 1 }
func (VantagePointRed) Attack() int                        { return 7 }
func (VantagePointRed) Defense() int                       { return 3 }
func (VantagePointRed) Types(card.GameEngine) card.TypeSet { return vantagePointTypes }
func (VantagePointRed) GoAgain(card.GameEngine) bool       { return false }

type VantagePointYellow struct{}

func (VantagePointYellow) ID() ids.CardID                     { return ids.VantagePointYellow }
func (VantagePointYellow) Name() string                       { return "Vantage Point" }
func (VantagePointYellow) DisplayName() string                { return "Vantage Point [Y]" }
func (VantagePointYellow) Cost() int                          { return 3 }
func (VantagePointYellow) Pitch() int                         { return 2 }
func (VantagePointYellow) Attack() int                        { return 6 }
func (VantagePointYellow) Defense() int                       { return 3 }
func (VantagePointYellow) Types(card.GameEngine) card.TypeSet { return vantagePointTypes }
func (VantagePointYellow) GoAgain(card.GameEngine) bool       { return false }

type VantagePointBlue struct{}

func (VantagePointBlue) ID() ids.CardID                     { return ids.VantagePointBlue }
func (VantagePointBlue) Name() string                       { return "Vantage Point" }
func (VantagePointBlue) DisplayName() string                { return "Vantage Point [B]" }
func (VantagePointBlue) Cost() int                          { return 3 }
func (VantagePointBlue) Pitch() int                         { return 3 }
func (VantagePointBlue) Attack() int                        { return 5 }
func (VantagePointBlue) Defense() int                       { return 3 }
func (VantagePointBlue) Types(card.GameEngine) card.TypeSet { return vantagePointTypes }
func (VantagePointBlue) GoAgain(card.GameEngine) bool       { return false }
