// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var vigorRushTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type VigorRushRed struct{}

func (VigorRushRed) ID() ids.CardID                     { return ids.VigorRushRed }
func (VigorRushRed) Name() string                       { return "Vigor Rush" }
func (VigorRushRed) DisplayName() string                { return "Vigor Rush [R]" }
func (VigorRushRed) Rarity() string                     { return "Common" }
func (VigorRushRed) Cost() int                          { return 1 }
func (VigorRushRed) Pitch() int                         { return 1 }
func (VigorRushRed) Attack() int                        { return 4 }
func (VigorRushRed) Defense() int                       { return 2 }
func (VigorRushRed) Types(card.GameEngine) card.TypeSet { return vigorRushTypes }
func (VigorRushRed) GoAgain(card.GameEngine) bool       { return false }

type VigorRushYellow struct{}

func (VigorRushYellow) ID() ids.CardID                     { return ids.VigorRushYellow }
func (VigorRushYellow) Name() string                       { return "Vigor Rush" }
func (VigorRushYellow) DisplayName() string                { return "Vigor Rush [Y]" }
func (VigorRushYellow) Rarity() string                     { return "Common" }
func (VigorRushYellow) Cost() int                          { return 1 }
func (VigorRushYellow) Pitch() int                         { return 2 }
func (VigorRushYellow) Attack() int                        { return 3 }
func (VigorRushYellow) Defense() int                       { return 2 }
func (VigorRushYellow) Types(card.GameEngine) card.TypeSet { return vigorRushTypes }
func (VigorRushYellow) GoAgain(card.GameEngine) bool       { return false }

type VigorRushBlue struct{}

func (VigorRushBlue) ID() ids.CardID                     { return ids.VigorRushBlue }
func (VigorRushBlue) Name() string                       { return "Vigor Rush" }
func (VigorRushBlue) DisplayName() string                { return "Vigor Rush [B]" }
func (VigorRushBlue) Rarity() string                     { return "Common" }
func (VigorRushBlue) Cost() int                          { return 1 }
func (VigorRushBlue) Pitch() int                         { return 3 }
func (VigorRushBlue) Attack() int                        { return 2 }
func (VigorRushBlue) Defense() int                       { return 2 }
func (VigorRushBlue) Types(card.GameEngine) card.TypeSet { return vigorRushTypes }
func (VigorRushBlue) GoAgain(card.GameEngine) bool       { return false }
