// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var volatileFluxorTypes = card.NewTypeSet(card.TypeLightning, card.TypeAction, card.TypeAttack)

type VolatileFluxorRed struct{}

func (VolatileFluxorRed) ID() ids.CardID                     { return ids.VolatileFluxorRed }
func (VolatileFluxorRed) Name() string                       { return "Volatile Fluxor" }
func (VolatileFluxorRed) DisplayName() string                { return "Volatile Fluxor [R]" }
func (VolatileFluxorRed) Rarity() string                     { return "Common" }
func (VolatileFluxorRed) Cost() int                          { return 0 }
func (VolatileFluxorRed) Pitch() int                         { return 1 }
func (VolatileFluxorRed) Attack() int                        { return 0 }
func (VolatileFluxorRed) Defense() int                       { return 3 }
func (VolatileFluxorRed) Types(card.GameEngine) card.TypeSet { return volatileFluxorTypes }
func (VolatileFluxorRed) GoAgain(card.GameEngine) bool       { return true }

type VolatileFluxorYellow struct{}

func (VolatileFluxorYellow) ID() ids.CardID                     { return ids.VolatileFluxorYellow }
func (VolatileFluxorYellow) Name() string                       { return "Volatile Fluxor" }
func (VolatileFluxorYellow) DisplayName() string                { return "Volatile Fluxor [Y]" }
func (VolatileFluxorYellow) Rarity() string                     { return "Common" }
func (VolatileFluxorYellow) Cost() int                          { return 0 }
func (VolatileFluxorYellow) Pitch() int                         { return 2 }
func (VolatileFluxorYellow) Attack() int                        { return 0 }
func (VolatileFluxorYellow) Defense() int                       { return 3 }
func (VolatileFluxorYellow) Types(card.GameEngine) card.TypeSet { return volatileFluxorTypes }
func (VolatileFluxorYellow) GoAgain(card.GameEngine) bool       { return true }

type VolatileFluxorBlue struct{}

func (VolatileFluxorBlue) ID() ids.CardID                     { return ids.VolatileFluxorBlue }
func (VolatileFluxorBlue) Name() string                       { return "Volatile Fluxor" }
func (VolatileFluxorBlue) DisplayName() string                { return "Volatile Fluxor [B]" }
func (VolatileFluxorBlue) Rarity() string                     { return "Common" }
func (VolatileFluxorBlue) Cost() int                          { return 0 }
func (VolatileFluxorBlue) Pitch() int                         { return 3 }
func (VolatileFluxorBlue) Attack() int                        { return 0 }
func (VolatileFluxorBlue) Defense() int                       { return 3 }
func (VolatileFluxorBlue) Types(card.GameEngine) card.TypeSet { return volatileFluxorTypes }
func (VolatileFluxorBlue) GoAgain(card.GameEngine) bool       { return true }
