// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var wageGoldTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type WageGoldRed struct{}

func (WageGoldRed) ID() ids.CardID      { return ids.WageGoldRed }
func (WageGoldRed) Name() string        { return "Wage Gold" }
func (WageGoldRed) DisplayName() string { return "Wage Gold [R]" }
func (WageGoldRed) Cost() int           { return 3 }
func (WageGoldRed) Pitch() int          { return 1 }
func (WageGoldRed) Attack() int         { return 7 }
func (WageGoldRed) Defense() int        { return 2 }
func (WageGoldRed) Types(ge card.GameEngine) card.TypeSet {
	if ge == nil {
		return wageGoldTypes
	}
	return wageGoldTypes | card.NewTypeSet(ge.CurrentHeroClass())
}
func (WageGoldRed) Universal()                   {}
func (WageGoldRed) GoAgain(card.GameEngine) bool { return false }

type WageGoldYellow struct{}

func (WageGoldYellow) ID() ids.CardID      { return ids.WageGoldYellow }
func (WageGoldYellow) Name() string        { return "Wage Gold" }
func (WageGoldYellow) DisplayName() string { return "Wage Gold [Y]" }
func (WageGoldYellow) Cost() int           { return 3 }
func (WageGoldYellow) Pitch() int          { return 2 }
func (WageGoldYellow) Attack() int         { return 6 }
func (WageGoldYellow) Defense() int        { return 2 }
func (WageGoldYellow) Types(ge card.GameEngine) card.TypeSet {
	if ge == nil {
		return wageGoldTypes
	}
	return wageGoldTypes | card.NewTypeSet(ge.CurrentHeroClass())
}
func (WageGoldYellow) Universal()                   {}
func (WageGoldYellow) GoAgain(card.GameEngine) bool { return false }

type WageGoldBlue struct{}

func (WageGoldBlue) ID() ids.CardID      { return ids.WageGoldBlue }
func (WageGoldBlue) Name() string        { return "Wage Gold" }
func (WageGoldBlue) DisplayName() string { return "Wage Gold [B]" }
func (WageGoldBlue) Cost() int           { return 3 }
func (WageGoldBlue) Pitch() int          { return 3 }
func (WageGoldBlue) Attack() int         { return 5 }
func (WageGoldBlue) Defense() int        { return 2 }
func (WageGoldBlue) Types(ge card.GameEngine) card.TypeSet {
	if ge == nil {
		return wageGoldTypes
	}
	return wageGoldTypes | card.NewTypeSet(ge.CurrentHeroClass())
}
func (WageGoldBlue) Universal()                   {}
func (WageGoldBlue) GoAgain(card.GameEngine) bool { return false }
