// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var woundedBullTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type WoundedBullRed struct{}

func (WoundedBullRed) ID() ids.CardID                     { return ids.WoundedBullRed }
func (WoundedBullRed) Name() string                       { return "Wounded Bull" }
func (WoundedBullRed) DisplayName() string                { return "Wounded Bull [R]" }
func (WoundedBullRed) Cost() int                          { return 3 }
func (WoundedBullRed) Pitch() int                         { return 1 }
func (WoundedBullRed) Attack() int                        { return 7 }
func (WoundedBullRed) Defense() int                       { return 2 }
func (WoundedBullRed) Types(card.GameEngine) card.TypeSet { return woundedBullTypes }
func (WoundedBullRed) GoAgain(card.GameEngine) bool       { return false }

type WoundedBullYellow struct{}

func (WoundedBullYellow) ID() ids.CardID                     { return ids.WoundedBullYellow }
func (WoundedBullYellow) Name() string                       { return "Wounded Bull" }
func (WoundedBullYellow) DisplayName() string                { return "Wounded Bull [Y]" }
func (WoundedBullYellow) Cost() int                          { return 3 }
func (WoundedBullYellow) Pitch() int                         { return 2 }
func (WoundedBullYellow) Attack() int                        { return 6 }
func (WoundedBullYellow) Defense() int                       { return 2 }
func (WoundedBullYellow) Types(card.GameEngine) card.TypeSet { return woundedBullTypes }
func (WoundedBullYellow) GoAgain(card.GameEngine) bool       { return false }

type WoundedBullBlue struct{}

func (WoundedBullBlue) ID() ids.CardID                     { return ids.WoundedBullBlue }
func (WoundedBullBlue) Name() string                       { return "Wounded Bull" }
func (WoundedBullBlue) DisplayName() string                { return "Wounded Bull [B]" }
func (WoundedBullBlue) Cost() int                          { return 3 }
func (WoundedBullBlue) Pitch() int                         { return 3 }
func (WoundedBullBlue) Attack() int                        { return 5 }
func (WoundedBullBlue) Defense() int                       { return 2 }
func (WoundedBullBlue) Types(card.GameEngine) card.TypeSet { return woundedBullTypes }
func (WoundedBullBlue) GoAgain(card.GameEngine) bool       { return false }
