// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var zealousBeltingTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type ZealousBeltingRed struct{}

func (ZealousBeltingRed) ID() ids.CardID                     { return ids.ZealousBeltingRed }
func (ZealousBeltingRed) Name() string                       { return "Zealous Belting" }
func (ZealousBeltingRed) DisplayName() string                { return "Zealous Belting [R]" }
func (ZealousBeltingRed) Rarity() string                     { return "Common" }
func (ZealousBeltingRed) Cost() int                          { return 2 }
func (ZealousBeltingRed) Pitch() int                         { return 1 }
func (ZealousBeltingRed) Attack() int                        { return 5 }
func (ZealousBeltingRed) Defense() int                       { return 2 }
func (ZealousBeltingRed) Types(card.GameEngine) card.TypeSet { return zealousBeltingTypes }
func (ZealousBeltingRed) GoAgain(card.GameEngine) bool       { return false }

type ZealousBeltingYellow struct{}

func (ZealousBeltingYellow) ID() ids.CardID                     { return ids.ZealousBeltingYellow }
func (ZealousBeltingYellow) Name() string                       { return "Zealous Belting" }
func (ZealousBeltingYellow) DisplayName() string                { return "Zealous Belting [Y]" }
func (ZealousBeltingYellow) Rarity() string                     { return "Common" }
func (ZealousBeltingYellow) Cost() int                          { return 2 }
func (ZealousBeltingYellow) Pitch() int                         { return 2 }
func (ZealousBeltingYellow) Attack() int                        { return 4 }
func (ZealousBeltingYellow) Defense() int                       { return 2 }
func (ZealousBeltingYellow) Types(card.GameEngine) card.TypeSet { return zealousBeltingTypes }
func (ZealousBeltingYellow) GoAgain(card.GameEngine) bool       { return false }

type ZealousBeltingBlue struct{}

func (ZealousBeltingBlue) ID() ids.CardID                     { return ids.ZealousBeltingBlue }
func (ZealousBeltingBlue) Name() string                       { return "Zealous Belting" }
func (ZealousBeltingBlue) DisplayName() string                { return "Zealous Belting [B]" }
func (ZealousBeltingBlue) Rarity() string                     { return "Common" }
func (ZealousBeltingBlue) Cost() int                          { return 2 }
func (ZealousBeltingBlue) Pitch() int                         { return 3 }
func (ZealousBeltingBlue) Attack() int                        { return 3 }
func (ZealousBeltingBlue) Defense() int                       { return 2 }
func (ZealousBeltingBlue) Types(card.GameEngine) card.TypeSet { return zealousBeltingTypes }
func (ZealousBeltingBlue) GoAgain(card.GameEngine) bool       { return false }
