// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var amuletOfEchoesTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type AmuletOfEchoesBlue struct{}

func (AmuletOfEchoesBlue) ID() ids.CardID          { return ids.AmuletOfEchoesBlue }
func (AmuletOfEchoesBlue) Name() string            { return "Amulet of Echoes" }
func (AmuletOfEchoesBlue) DisplayName() string     { return "Amulet of Echoes [B]" }
func (AmuletOfEchoesBlue) Cost(sim.GameEngine) int { return 0 }
func (AmuletOfEchoesBlue) Pitch() int              { return 3 }
func (AmuletOfEchoesBlue) Attack() int             { return 0 }
func (AmuletOfEchoesBlue) Defense() int            { return 0 }
func (AmuletOfEchoesBlue) Types() card.TypeSet     { return amuletOfEchoesTypes }
func (AmuletOfEchoesBlue) GoAgain() bool           { return true }
func (AmuletOfEchoesBlue) Unplayable()             {}
