// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var destructiveTendenciesTypes = card.NewTypeSet(card.TypeGeneric, card.TypeInstant)

type DestructiveTendenciesBlue struct{}

func (DestructiveTendenciesBlue) ID() ids.CardID           { return ids.DestructiveTendenciesBlue }
func (DestructiveTendenciesBlue) Name() string             { return "Destructive Tendencies" }
func (DestructiveTendenciesBlue) DisplayName() string      { return "Destructive Tendencies [B]" }
func (DestructiveTendenciesBlue) Cost(card.GameEngine) int { return 0 }
func (DestructiveTendenciesBlue) Pitch() int               { return 3 }
func (DestructiveTendenciesBlue) Attack() int              { return 0 }
func (DestructiveTendenciesBlue) Defense() int             { return 0 }
func (DestructiveTendenciesBlue) Types(card.GameEngine) card.TypeSet {
	return destructiveTendenciesTypes
}
func (DestructiveTendenciesBlue) GoAgain() bool { return false }
func (DestructiveTendenciesBlue) Unplayable()   {}
