// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var droneOfBrutalityTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type DroneOfBrutalityRed struct{}

func (DroneOfBrutalityRed) ID() ids.CardID           { return ids.DroneOfBrutalityRed }
func (DroneOfBrutalityRed) Name() string             { return "Drone of Brutality" }
func (DroneOfBrutalityRed) DisplayName() string      { return "Drone of Brutality [R]" }
func (DroneOfBrutalityRed) Cost(card.GameEngine) int { return 2 }
func (DroneOfBrutalityRed) Pitch() int               { return 1 }
func (DroneOfBrutalityRed) Attack() int              { return 6 }
func (DroneOfBrutalityRed) Defense() int             { return 2 }
func (DroneOfBrutalityRed) Types() card.TypeSet      { return droneOfBrutalityTypes }
func (DroneOfBrutalityRed) GoAgain() bool            { return false }
func (DroneOfBrutalityRed) NotSilverAgeLegal()       {}
func (DroneOfBrutalityRed) Unplayable()              {}

type DroneOfBrutalityYellow struct{}

func (DroneOfBrutalityYellow) ID() ids.CardID           { return ids.DroneOfBrutalityYellow }
func (DroneOfBrutalityYellow) Name() string             { return "Drone of Brutality" }
func (DroneOfBrutalityYellow) DisplayName() string      { return "Drone of Brutality [Y]" }
func (DroneOfBrutalityYellow) Cost(card.GameEngine) int { return 2 }
func (DroneOfBrutalityYellow) Pitch() int               { return 2 }
func (DroneOfBrutalityYellow) Attack() int              { return 5 }
func (DroneOfBrutalityYellow) Defense() int             { return 2 }
func (DroneOfBrutalityYellow) Types() card.TypeSet      { return droneOfBrutalityTypes }
func (DroneOfBrutalityYellow) GoAgain() bool            { return false }
func (DroneOfBrutalityYellow) NotSilverAgeLegal()       {}
func (DroneOfBrutalityYellow) Unplayable()              {}

type DroneOfBrutalityBlue struct{}

func (DroneOfBrutalityBlue) ID() ids.CardID           { return ids.DroneOfBrutalityBlue }
func (DroneOfBrutalityBlue) Name() string             { return "Drone of Brutality" }
func (DroneOfBrutalityBlue) DisplayName() string      { return "Drone of Brutality [B]" }
func (DroneOfBrutalityBlue) Cost(card.GameEngine) int { return 2 }
func (DroneOfBrutalityBlue) Pitch() int               { return 3 }
func (DroneOfBrutalityBlue) Attack() int              { return 4 }
func (DroneOfBrutalityBlue) Defense() int             { return 2 }
func (DroneOfBrutalityBlue) Types() card.TypeSet      { return droneOfBrutalityTypes }
func (DroneOfBrutalityBlue) GoAgain() bool            { return false }
func (DroneOfBrutalityBlue) NotSilverAgeLegal()       {}
func (DroneOfBrutalityBlue) Unplayable()              {}
