// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var nimbyTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type NimbyRed struct{}

func (NimbyRed) ID() ids.CardID           { return ids.NimbyRed }
func (NimbyRed) Name() string             { return "Nimby" }
func (NimbyRed) DisplayName() string      { return "Nimby [R]" }
func (NimbyRed) Cost(card.GameEngine) int { return 0 }
func (NimbyRed) Pitch() int               { return 1 }
func (NimbyRed) Attack() int              { return 3 }
func (NimbyRed) Defense() int             { return 2 }
func (NimbyRed) Types() card.TypeSet      { return nimbyTypes }
func (NimbyRed) GoAgain() bool            { return false }
func (NimbyRed) NotSilverAgeLegal()       {}
func (NimbyRed) Unplayable()              {}

type NimbyYellow struct{}

func (NimbyYellow) ID() ids.CardID           { return ids.NimbyYellow }
func (NimbyYellow) Name() string             { return "Nimby" }
func (NimbyYellow) DisplayName() string      { return "Nimby [Y]" }
func (NimbyYellow) Cost(card.GameEngine) int { return 0 }
func (NimbyYellow) Pitch() int               { return 2 }
func (NimbyYellow) Attack() int              { return 2 }
func (NimbyYellow) Defense() int             { return 2 }
func (NimbyYellow) Types() card.TypeSet      { return nimbyTypes }
func (NimbyYellow) GoAgain() bool            { return false }
func (NimbyYellow) NotSilverAgeLegal()       {}
func (NimbyYellow) Unplayable()              {}

type NimbyBlue struct{}

func (NimbyBlue) ID() ids.CardID           { return ids.NimbyBlue }
func (NimbyBlue) Name() string             { return "Nimby" }
func (NimbyBlue) DisplayName() string      { return "Nimby [B]" }
func (NimbyBlue) Cost(card.GameEngine) int { return 0 }
func (NimbyBlue) Pitch() int               { return 3 }
func (NimbyBlue) Attack() int              { return 1 }
func (NimbyBlue) Defense() int             { return 2 }
func (NimbyBlue) Types() card.TypeSet      { return nimbyTypes }
func (NimbyBlue) GoAgain() bool            { return false }
func (NimbyBlue) NotSilverAgeLegal()       {}
func (NimbyBlue) Unplayable()              {}
