// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var shatterSorceryTypes = card.NewTypeSet(card.TypeGeneric, card.TypeInstant)

type ShatterSorceryBlue struct{}

func (ShatterSorceryBlue) ID() ids.CardID                     { return ids.ShatterSorceryBlue }
func (ShatterSorceryBlue) Name() string                       { return "Shatter Sorcery" }
func (ShatterSorceryBlue) DisplayName() string                { return "Shatter Sorcery [B]" }
func (ShatterSorceryBlue) Cost(card.GameEngine) int           { return 0 }
func (ShatterSorceryBlue) Pitch() int                         { return 3 }
func (ShatterSorceryBlue) Attack() int                        { return 0 }
func (ShatterSorceryBlue) Defense() int                       { return 0 }
func (ShatterSorceryBlue) Types(card.GameEngine) card.TypeSet { return shatterSorceryTypes }
func (ShatterSorceryBlue) GoAgain() bool                      { return false }
func (ShatterSorceryBlue) Unplayable()                        {}
