// Code generated by cardgen. DO NOT EDIT.

package registry

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card/cards"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

// cardsByID holds every implemented card variant, indexed by ids.CardID; index 0
// (Invalid) is nil. The deck-construction pool and every ID lookup read it.
var cardsByID = []Card{
	ids.InvalidCard: nil,

	ids.AdrenalineRushRed:    cards.AdrenalineRushRed{},
	ids.AdrenalineRushYellow: cards.AdrenalineRushYellow{},
	ids.AdrenalineRushBlue:   cards.AdrenalineRushBlue{},

	ids.AetherSlashRed:    cards.AetherSlashRed{},
	ids.AetherSlashYellow: cards.AetherSlashYellow{},
	ids.AetherSlashBlue:   cards.AetherSlashBlue{},

	ids.AmplifyTheArknightRed:    cards.AmplifyTheArknightRed{},
	ids.AmplifyTheArknightYellow: cards.AmplifyTheArknightYellow{},
	ids.AmplifyTheArknightBlue:   cards.AmplifyTheArknightBlue{},

	ids.ArcaneCussingRed:    cards.ArcaneCussingRed{},
	ids.ArcaneCussingYellow: cards.ArcaneCussingYellow{},
	ids.ArcaneCussingBlue:   cards.ArcaneCussingBlue{},

	ids.ArcanePolarityRed:    cards.ArcanePolarityRed{},
	ids.ArcanePolarityYellow: cards.ArcanePolarityYellow{},
	ids.ArcanePolarityBlue:   cards.ArcanePolarityBlue{},

	ids.ArcanicCrackleRed:    cards.ArcanicCrackleRed{},
	ids.ArcanicCrackleYellow: cards.ArcanicCrackleYellow{},
	ids.ArcanicCrackleBlue:   cards.ArcanicCrackleBlue{},

	ids.ArcanicSpikeRed:    cards.ArcanicSpikeRed{},
	ids.ArcanicSpikeYellow: cards.ArcanicSpikeYellow{},
	ids.ArcanicSpikeBlue:   cards.ArcanicSpikeBlue{},

	ids.BackAlleyBreaklineRed:    cards.BackAlleyBreaklineRed{},
	ids.BackAlleyBreaklineYellow: cards.BackAlleyBreaklineYellow{},
	ids.BackAlleyBreaklineBlue:   cards.BackAlleyBreaklineBlue{},

	ids.BarragingBrawnhideRed:    cards.BarragingBrawnhideRed{},
	ids.BarragingBrawnhideYellow: cards.BarragingBrawnhideYellow{},
	ids.BarragingBrawnhideBlue:   cards.BarragingBrawnhideBlue{},

	ids.BattlefrontBastionRed:    cards.BattlefrontBastionRed{},
	ids.BattlefrontBastionYellow: cards.BattlefrontBastionYellow{},
	ids.BattlefrontBastionBlue:   cards.BattlefrontBastionBlue{},

	ids.BladeFlashBlue: cards.BladeFlashBlue{},

	ids.BlanchRed:    cards.BlanchRed{},
	ids.BlanchYellow: cards.BlanchYellow{},
	ids.BlanchBlue:   cards.BlanchBlue{},

	ids.BlessingOfOccultRed:    cards.BlessingOfOccultRed{},
	ids.BlessingOfOccultYellow: cards.BlessingOfOccultYellow{},
	ids.BlessingOfOccultBlue:   cards.BlessingOfOccultBlue{},

	ids.BloodspillInvocationRed:    cards.BloodspillInvocationRed{},
	ids.BloodspillInvocationYellow: cards.BloodspillInvocationYellow{},
	ids.BloodspillInvocationBlue:   cards.BloodspillInvocationBlue{},

	ids.BlowForABlowRed: cards.BlowForABlowRed{},

	ids.BlusterBuffRed: cards.BlusterBuffRed{},

	ids.BrandishRed:    cards.BrandishRed{},
	ids.BrandishYellow: cards.BrandishYellow{},
	ids.BrandishBlue:   cards.BrandishBlue{},

	ids.BrothersInArmsRed:    cards.BrothersInArmsRed{},
	ids.BrothersInArmsYellow: cards.BrothersInArmsYellow{},
	ids.BrothersInArmsBlue:   cards.BrothersInArmsBlue{},

	ids.BrushOffRed:    cards.BrushOffRed{},
	ids.BrushOffYellow: cards.BrushOffYellow{},
	ids.BrushOffBlue:   cards.BrushOffBlue{},

	ids.BrutalAssaultRed:    cards.BrutalAssaultRed{},
	ids.BrutalAssaultYellow: cards.BrutalAssaultYellow{},
	ids.BrutalAssaultBlue:   cards.BrutalAssaultBlue{},

	ids.CadaverousContrabandRed:    cards.CadaverousContrabandRed{},
	ids.CadaverousContrabandYellow: cards.CadaverousContrabandYellow{},
	ids.CadaverousContrabandBlue:   cards.CadaverousContrabandBlue{},

	ids.CalmingBreezeRed: cards.CalmingBreezeRed{},

	ids.CaptainsCallRed:    cards.CaptainsCallRed{},
	ids.CaptainsCallYellow: cards.CaptainsCallYellow{},
	ids.CaptainsCallBlue:   cards.CaptainsCallBlue{},

	ids.ChestPuffRed: cards.ChestPuffRed{},

	ids.ClearwaterElixirRed: cards.ClearwaterElixirRed{},

	ids.ComeToFightRed:    cards.ComeToFightRed{},
	ids.ComeToFightYellow: cards.ComeToFightYellow{},
	ids.ComeToFightBlue:   cards.ComeToFightBlue{},

	ids.CondemnToSlaughterRed:    cards.CondemnToSlaughterRed{},
	ids.CondemnToSlaughterYellow: cards.CondemnToSlaughterYellow{},
	ids.CondemnToSlaughterBlue:   cards.CondemnToSlaughterBlue{},

	ids.ConsumingVolitionRed:    cards.ConsumingVolitionRed{},
	ids.ConsumingVolitionYellow: cards.ConsumingVolitionYellow{},
	ids.ConsumingVolitionBlue:   cards.ConsumingVolitionBlue{},

	ids.CrackedBaubleYellow: cards.CrackedBaubleYellow{},

	ids.CrashDownTheGatesRed:    cards.CrashDownTheGatesRed{},
	ids.CrashDownTheGatesYellow: cards.CrashDownTheGatesYellow{},
	ids.CrashDownTheGatesBlue:   cards.CrashDownTheGatesBlue{},

	ids.CriticalStrikeRed:    cards.CriticalStrikeRed{},
	ids.CriticalStrikeYellow: cards.CriticalStrikeYellow{},
	ids.CriticalStrikeBlue:   cards.CriticalStrikeBlue{},

	ids.CutDownToSizeRed:    cards.CutDownToSizeRed{},
	ids.CutDownToSizeYellow: cards.CutDownToSizeYellow{},
	ids.CutDownToSizeBlue:   cards.CutDownToSizeBlue{},

	ids.DeathlyDuetRed:    cards.DeathlyDuetRed{},
	ids.DeathlyDuetYellow: cards.DeathlyDuetYellow{},
	ids.DeathlyDuetBlue:   cards.DeathlyDuetBlue{},

	ids.DemolitionCrewRed:    cards.DemolitionCrewRed{},
	ids.DemolitionCrewYellow: cards.DemolitionCrewYellow{},
	ids.DemolitionCrewBlue:   cards.DemolitionCrewBlue{},

	ids.DestructiveDeliberationRed:    cards.DestructiveDeliberationRed{},
	ids.DestructiveDeliberationYellow: cards.DestructiveDeliberationYellow{},
	ids.DestructiveDeliberationBlue:   cards.DestructiveDeliberationBlue{},

	ids.DodgeBlue: cards.DodgeBlue{},

	ids.DragDownRed:    cards.DragDownRed{},
	ids.DragDownYellow: cards.DragDownYellow{},
	ids.DragDownBlue:   cards.DragDownBlue{},

	ids.DrawnToTheDarkDimensionRed:    cards.DrawnToTheDarkDimensionRed{},
	ids.DrawnToTheDarkDimensionYellow: cards.DrawnToTheDarkDimensionYellow{},
	ids.DrawnToTheDarkDimensionBlue:   cards.DrawnToTheDarkDimensionBlue{},

	ids.DrowningDireRed:    cards.DrowningDireRed{},
	ids.DrowningDireYellow: cards.DrowningDireYellow{},
	ids.DrowningDireBlue:   cards.DrowningDireBlue{},

	ids.EirinasPrayerRed:    cards.EirinasPrayerRed{},
	ids.EirinasPrayerYellow: cards.EirinasPrayerYellow{},
	ids.EirinasPrayerBlue:   cards.EirinasPrayerBlue{},

	ids.EmissaryOfMoonRed: cards.EmissaryOfMoonRed{},

	ids.EmissaryOfTidesRed: cards.EmissaryOfTidesRed{},

	ids.EmissaryOfWindRed: cards.EmissaryOfWindRed{},

	ids.EnchantingMelodyRed:    cards.EnchantingMelodyRed{},
	ids.EnchantingMelodyYellow: cards.EnchantingMelodyYellow{},
	ids.EnchantingMelodyBlue:   cards.EnchantingMelodyBlue{},

	ids.EvasiveLeapRed:    cards.EvasiveLeapRed{},
	ids.EvasiveLeapYellow: cards.EvasiveLeapYellow{},
	ids.EvasiveLeapBlue:   cards.EvasiveLeapBlue{},

	ids.EvenBiggerThanThatRed:    cards.EvenBiggerThanThatRed{},
	ids.EvenBiggerThanThatYellow: cards.EvenBiggerThanThatYellow{},
	ids.EvenBiggerThanThatBlue:   cards.EvenBiggerThanThatBlue{},

	ids.ExposedBlue: cards.ExposedBlue{},

	ids.FactFindingMissionRed:    cards.FactFindingMissionRed{},
	ids.FactFindingMissionYellow: cards.FactFindingMissionYellow{},
	ids.FactFindingMissionBlue:   cards.FactFindingMissionBlue{},

	ids.FateForeseenRed:    cards.FateForeseenRed{},
	ids.FateForeseenYellow: cards.FateForeseenYellow{},
	ids.FateForeseenBlue:   cards.FateForeseenBlue{},

	ids.FeistyLocalsRed:    cards.FeistyLocalsRed{},
	ids.FeistyLocalsYellow: cards.FeistyLocalsYellow{},
	ids.FeistyLocalsBlue:   cards.FeistyLocalsBlue{},

	ids.FerventForerunnerRed:    cards.FerventForerunnerRed{},
	ids.FerventForerunnerYellow: cards.FerventForerunnerYellow{},
	ids.FerventForerunnerBlue:   cards.FerventForerunnerBlue{},

	ids.FiddlersGreenRed:    cards.FiddlersGreenRed{},
	ids.FiddlersGreenYellow: cards.FiddlersGreenYellow{},
	ids.FiddlersGreenBlue:   cards.FiddlersGreenBlue{},

	ids.FlexRed:    cards.FlexRed{},
	ids.FlexYellow: cards.FlexYellow{},
	ids.FlexBlue:   cards.FlexBlue{},

	ids.FlockOfTheFeatherWalkersRed:    cards.FlockOfTheFeatherWalkersRed{},
	ids.FlockOfTheFeatherWalkersYellow: cards.FlockOfTheFeatherWalkersYellow{},
	ids.FlockOfTheFeatherWalkersBlue:   cards.FlockOfTheFeatherWalkersBlue{},

	ids.FlyingHighRed:    cards.FlyingHighRed{},
	ids.FlyingHighYellow: cards.FlyingHighYellow{},
	ids.FlyingHighBlue:   cards.FlyingHighBlue{},

	ids.ForceSightRed:    cards.ForceSightRed{},
	ids.ForceSightYellow: cards.ForceSightYellow{},
	ids.ForceSightBlue:   cards.ForceSightBlue{},

	ids.FreewheelingRenegadesRed:    cards.FreewheelingRenegadesRed{},
	ids.FreewheelingRenegadesYellow: cards.FreewheelingRenegadesYellow{},
	ids.FreewheelingRenegadesBlue:   cards.FreewheelingRenegadesBlue{},

	ids.FrontlineScoutRed:    cards.FrontlineScoutRed{},
	ids.FrontlineScoutYellow: cards.FrontlineScoutYellow{},
	ids.FrontlineScoutBlue:   cards.FrontlineScoutBlue{},

	ids.FyendalsFightingSpiritRed:    cards.FyendalsFightingSpiritRed{},
	ids.FyendalsFightingSpiritYellow: cards.FyendalsFightingSpiritYellow{},
	ids.FyendalsFightingSpiritBlue:   cards.FyendalsFightingSpiritBlue{},

	ids.GravekeepingRed:    cards.GravekeepingRed{},
	ids.GravekeepingYellow: cards.GravekeepingYellow{},
	ids.GravekeepingBlue:   cards.GravekeepingBlue{},

	ids.HandBehindThePenRed: cards.HandBehindThePenRed{},

	ids.HealingBalmRed:    cards.HealingBalmRed{},
	ids.HealingBalmYellow: cards.HealingBalmYellow{},
	ids.HealingBalmBlue:   cards.HealingBalmBlue{},

	ids.HighStrikerRed:    cards.HighStrikerRed{},
	ids.HighStrikerYellow: cards.HighStrikerYellow{},
	ids.HighStrikerBlue:   cards.HighStrikerBlue{},

	ids.HitTheHighNotesRed:    cards.HitTheHighNotesRed{},
	ids.HitTheHighNotesYellow: cards.HitTheHighNotesYellow{},
	ids.HitTheHighNotesBlue:   cards.HitTheHighNotesBlue{},

	ids.HocusPocusRed:    cards.HocusPocusRed{},
	ids.HocusPocusYellow: cards.HocusPocusYellow{},
	ids.HocusPocusBlue:   cards.HocusPocusBlue{},

	ids.HumbleRed:    cards.HumbleRed{},
	ids.HumbleYellow: cards.HumbleYellow{},
	ids.HumbleBlue:   cards.HumbleBlue{},

	ids.ImperialSealOfCommandRed: cards.ImperialSealOfCommandRed{},

	ids.InfectiousHostRed:    cards.InfectiousHostRed{},
	ids.InfectiousHostYellow: cards.InfectiousHostYellow{},
	ids.InfectiousHostBlue:   cards.InfectiousHostBlue{},

	ids.JackBeNimbleRed: cards.JackBeNimbleRed{},

	ids.JackBeQuickRed: cards.JackBeQuickRed{},

	ids.LayLowYellow: cards.LayLowYellow{},

	ids.LeadTheChargeRed:    cards.LeadTheChargeRed{},
	ids.LeadTheChargeYellow: cards.LeadTheChargeYellow{},
	ids.LeadTheChargeBlue:   cards.LeadTheChargeBlue{},

	ids.LifeForALifeRed:    cards.LifeForALifeRed{},
	ids.LifeForALifeYellow: cards.LifeForALifeYellow{},
	ids.LifeForALifeBlue:   cards.LifeForALifeBlue{},

	ids.LookTuffRed: cards.LookTuffRed{},

	ids.LookingForAScrapRed:    cards.LookingForAScrapRed{},
	ids.LookingForAScrapYellow: cards.LookingForAScrapYellow{},
	ids.LookingForAScrapBlue:   cards.LookingForAScrapBlue{},

	ids.LungingPressBlue: cards.LungingPressBlue{},

	ids.MaleficIncantationRed:    cards.MaleficIncantationRed{},
	ids.MaleficIncantationYellow: cards.MaleficIncantationYellow{},
	ids.MaleficIncantationBlue:   cards.MaleficIncantationBlue{},

	ids.MauvrionSkiesRed:    cards.MauvrionSkiesRed{},
	ids.MauvrionSkiesYellow: cards.MauvrionSkiesYellow{},
	ids.MauvrionSkiesBlue:   cards.MauvrionSkiesBlue{},

	ids.MeatAndGreetRed:    cards.MeatAndGreetRed{},
	ids.MeatAndGreetYellow: cards.MeatAndGreetYellow{},
	ids.MeatAndGreetBlue:   cards.MeatAndGreetBlue{},

	ids.MemorialGroundRed:    cards.MemorialGroundRed{},
	ids.MemorialGroundYellow: cards.MemorialGroundYellow{},
	ids.MemorialGroundBlue:   cards.MemorialGroundBlue{},

	ids.MinnowismRed:    cards.MinnowismRed{},
	ids.MinnowismYellow: cards.MinnowismYellow{},
	ids.MinnowismBlue:   cards.MinnowismBlue{},

	ids.MoneyOrYourLifeRed:    cards.MoneyOrYourLifeRed{},
	ids.MoneyOrYourLifeYellow: cards.MoneyOrYourLifeYellow{},
	ids.MoneyOrYourLifeBlue:   cards.MoneyOrYourLifeBlue{},

	ids.MoneyWhereYaMouthIsRed:    cards.MoneyWhereYaMouthIsRed{},
	ids.MoneyWhereYaMouthIsYellow: cards.MoneyWhereYaMouthIsYellow{},
	ids.MoneyWhereYaMouthIsBlue:   cards.MoneyWhereYaMouthIsBlue{},

	ids.MoonWishRed:    cards.MoonWishRed{},
	ids.MoonWishYellow: cards.MoonWishYellow{},
	ids.MoonWishBlue:   cards.MoonWishBlue{},

	ids.MuscleMuttYellow: cards.MuscleMuttYellow{},

	ids.NimbleStrikeRed:    cards.NimbleStrikeRed{},
	ids.NimbleStrikeYellow: cards.NimbleStrikeYellow{},
	ids.NimbleStrikeBlue:   cards.NimbleStrikeBlue{},

	ids.NimblismRed:    cards.NimblismRed{},
	ids.NimblismYellow: cards.NimblismYellow{},
	ids.NimblismBlue:   cards.NimblismBlue{},

	ids.NipAtTheHeelsBlue: cards.NipAtTheHeelsBlue{},

	ids.OasisRespiteRed:    cards.OasisRespiteRed{},
	ids.OasisRespiteYellow: cards.OasisRespiteYellow{},
	ids.OasisRespiteBlue:   cards.OasisRespiteBlue{},

	ids.OathOfTheArknightRed:    cards.OathOfTheArknightRed{},
	ids.OathOfTheArknightYellow: cards.OathOfTheArknightYellow{},
	ids.OathOfTheArknightBlue:   cards.OathOfTheArknightBlue{},

	ids.OnAKnifeEdgeYellow: cards.OnAKnifeEdgeYellow{},

	ids.OnTheHorizonRed:    cards.OnTheHorizonRed{},
	ids.OnTheHorizonYellow: cards.OnTheHorizonYellow{},
	ids.OnTheHorizonBlue:   cards.OnTheHorizonBlue{},

	ids.OutMuscleRed:    cards.OutMuscleRed{},
	ids.OutMuscleYellow: cards.OutMuscleYellow{},
	ids.OutMuscleBlue:   cards.OutMuscleBlue{},

	ids.OutedRed: cards.OutedRed{},

	ids.OverloadRed:    cards.OverloadRed{},
	ids.OverloadYellow: cards.OverloadYellow{},
	ids.OverloadBlue:   cards.OverloadBlue{},

	ids.PeaceOfMindRed:    cards.PeaceOfMindRed{},
	ids.PeaceOfMindYellow: cards.PeaceOfMindYellow{},
	ids.PeaceOfMindBlue:   cards.PeaceOfMindBlue{},

	ids.PerformanceBonusRed:    cards.PerformanceBonusRed{},
	ids.PerformanceBonusYellow: cards.PerformanceBonusYellow{},
	ids.PerformanceBonusBlue:   cards.PerformanceBonusBlue{},

	ids.PickACardAnyCardRed:    cards.PickACardAnyCardRed{},
	ids.PickACardAnyCardYellow: cards.PickACardAnyCardYellow{},
	ids.PickACardAnyCardBlue:   cards.PickACardAnyCardBlue{},

	ids.PlunderRunRed:    cards.PlunderRunRed{},
	ids.PlunderRunYellow: cards.PlunderRunYellow{},
	ids.PlunderRunBlue:   cards.PlunderRunBlue{},

	ids.PoundForPoundRed:    cards.PoundForPoundRed{},
	ids.PoundForPoundYellow: cards.PoundForPoundYellow{},
	ids.PoundForPoundBlue:   cards.PoundForPoundBlue{},

	ids.PrimeTheCrowdRed:    cards.PrimeTheCrowdRed{},
	ids.PrimeTheCrowdYellow: cards.PrimeTheCrowdYellow{},
	ids.PrimeTheCrowdBlue:   cards.PrimeTheCrowdBlue{},

	ids.PublicBountyRed:    cards.PublicBountyRed{},
	ids.PublicBountyYellow: cards.PublicBountyYellow{},
	ids.PublicBountyBlue:   cards.PublicBountyBlue{},

	ids.PummelRed:    cards.PummelRed{},
	ids.PummelYellow: cards.PummelYellow{},
	ids.PummelBlue:   cards.PummelBlue{},

	ids.PunchAboveYourWeightRed:    cards.PunchAboveYourWeightRed{},
	ids.PunchAboveYourWeightYellow: cards.PunchAboveYourWeightYellow{},
	ids.PunchAboveYourWeightBlue:   cards.PunchAboveYourWeightBlue{},

	ids.PursueToTheEdgeOfOblivionRed: cards.PursueToTheEdgeOfOblivionRed{},

	ids.PursueToThePitsOfDespairRed: cards.PursueToThePitsOfDespairRed{},

	ids.PushThePointRed:    cards.PushThePointRed{},
	ids.PushThePointYellow: cards.PushThePointYellow{},
	ids.PushThePointBlue:   cards.PushThePointBlue{},

	ids.RagingOnslaughtRed:    cards.RagingOnslaughtRed{},
	ids.RagingOnslaughtYellow: cards.RagingOnslaughtYellow{},
	ids.RagingOnslaughtBlue:   cards.RagingOnslaughtBlue{},

	ids.RallyTheCoastGuardRed:    cards.RallyTheCoastGuardRed{},
	ids.RallyTheCoastGuardYellow: cards.RallyTheCoastGuardYellow{},
	ids.RallyTheCoastGuardBlue:   cards.RallyTheCoastGuardBlue{},

	ids.RallyTheRearguardRed:    cards.RallyTheRearguardRed{},
	ids.RallyTheRearguardYellow: cards.RallyTheRearguardYellow{},
	ids.RallyTheRearguardBlue:   cards.RallyTheRearguardBlue{},

	ids.RavenousRabbleRed:    cards.RavenousRabbleRed{},
	ids.RavenousRabbleYellow: cards.RavenousRabbleYellow{},
	ids.RavenousRabbleBlue:   cards.RavenousRabbleBlue{},

	ids.RazorReflexRed:    cards.RazorReflexRed{},
	ids.RazorReflexYellow: cards.RazorReflexYellow{},
	ids.RazorReflexBlue:   cards.RazorReflexBlue{},

	ids.ReadTheRunesRed:    cards.ReadTheRunesRed{},
	ids.ReadTheRunesYellow: cards.ReadTheRunesYellow{},
	ids.ReadTheRunesBlue:   cards.ReadTheRunesBlue{},

	ids.ReduceToRunechantRed:    cards.ReduceToRunechantRed{},
	ids.ReduceToRunechantYellow: cards.ReduceToRunechantYellow{},
	ids.ReduceToRunechantBlue:   cards.ReduceToRunechantBlue{},

	ids.ReekOfCorruptionRed:    cards.ReekOfCorruptionRed{},
	ids.ReekOfCorruptionYellow: cards.ReekOfCorruptionYellow{},
	ids.ReekOfCorruptionBlue:   cards.ReekOfCorruptionBlue{},

	ids.RegainComposureBlue: cards.RegainComposureBlue{},

	ids.RegurgitatingSlogRed:    cards.RegurgitatingSlogRed{},
	ids.RegurgitatingSlogYellow: cards.RegurgitatingSlogYellow{},
	ids.RegurgitatingSlogBlue:   cards.RegurgitatingSlogBlue{},

	ids.ReinforceTheLineRed:    cards.ReinforceTheLineRed{},
	ids.ReinforceTheLineYellow: cards.ReinforceTheLineYellow{},
	ids.ReinforceTheLineBlue:   cards.ReinforceTheLineBlue{},

	ids.RelentlessPursuitBlue: cards.RelentlessPursuitBlue{},

	ids.RestvineElixirRed: cards.RestvineElixirRed{},

	ids.RiftingRed:    cards.RiftingRed{},
	ids.RiftingYellow: cards.RiftingYellow{},
	ids.RiftingBlue:   cards.RiftingBlue{},

	ids.RightBehindYouRed:    cards.RightBehindYouRed{},
	ids.RightBehindYouYellow: cards.RightBehindYouYellow{},
	ids.RightBehindYouBlue:   cards.RightBehindYouBlue{},

	ids.RiseAboveRed:    cards.RiseAboveRed{},
	ids.RiseAboveYellow: cards.RiseAboveYellow{},
	ids.RiseAboveBlue:   cards.RiseAboveBlue{},

	ids.RuneFlashRed:    cards.RuneFlashRed{},
	ids.RuneFlashYellow: cards.RuneFlashYellow{},
	ids.RuneFlashBlue:   cards.RuneFlashBlue{},

	ids.RunebloodIncantationRed:    cards.RunebloodIncantationRed{},
	ids.RunebloodIncantationYellow: cards.RunebloodIncantationYellow{},
	ids.RunebloodIncantationBlue:   cards.RunebloodIncantationBlue{},

	ids.RuneragerSwarmRed:    cards.RuneragerSwarmRed{},
	ids.RuneragerSwarmYellow: cards.RuneragerSwarmYellow{},
	ids.RuneragerSwarmBlue:   cards.RuneragerSwarmBlue{},

	ids.RunicFellingsongRed:    cards.RunicFellingsongRed{},
	ids.RunicFellingsongYellow: cards.RunicFellingsongYellow{},
	ids.RunicFellingsongBlue:   cards.RunicFellingsongBlue{},

	ids.RunicReapingRed:    cards.RunicReapingRed{},
	ids.RunicReapingYellow: cards.RunicReapingYellow{},
	ids.RunicReapingBlue:   cards.RunicReapingBlue{},

	ids.SapwoodElixirRed: cards.SapwoodElixirRed{},

	ids.ScarForAScarRed:    cards.ScarForAScarRed{},
	ids.ScarForAScarYellow: cards.ScarForAScarYellow{},
	ids.ScarForAScarBlue:   cards.ScarForAScarBlue{},

	ids.ScourTheBattlescapeRed:    cards.ScourTheBattlescapeRed{},
	ids.ScourTheBattlescapeYellow: cards.ScourTheBattlescapeYellow{},
	ids.ScourTheBattlescapeBlue:   cards.ScourTheBattlescapeBlue{},

	ids.ScoutThePeripheryRed:    cards.ScoutThePeripheryRed{},
	ids.ScoutThePeripheryYellow: cards.ScoutThePeripheryYellow{},
	ids.ScoutThePeripheryBlue:   cards.ScoutThePeripheryBlue{},

	ids.SeekHorizonRed:    cards.SeekHorizonRed{},
	ids.SeekHorizonYellow: cards.SeekHorizonYellow{},
	ids.SeekHorizonBlue:   cards.SeekHorizonBlue{},

	ids.ShrillOfSkullformRed:    cards.ShrillOfSkullformRed{},
	ids.ShrillOfSkullformYellow: cards.ShrillOfSkullformYellow{},
	ids.ShrillOfSkullformBlue:   cards.ShrillOfSkullformBlue{},

	ids.SiftRed:    cards.SiftRed{},
	ids.SiftYellow: cards.SiftYellow{},
	ids.SiftBlue:   cards.SiftBlue{},

	ids.SigilOfCyclesBlue: cards.SigilOfCyclesBlue{},

	ids.SigilOfDeadwoodBlue: cards.SigilOfDeadwoodBlue{},

	ids.SigilOfFyendalBlue: cards.SigilOfFyendalBlue{},

	ids.SigilOfSilphidaeBlue: cards.SigilOfSilphidaeBlue{},

	ids.SigilOfSufferingRed:    cards.SigilOfSufferingRed{},
	ids.SigilOfSufferingYellow: cards.SigilOfSufferingYellow{},
	ids.SigilOfSufferingBlue:   cards.SigilOfSufferingBlue{},

	ids.SigilOfTheArknightBlue: cards.SigilOfTheArknightBlue{},

	ids.SingeingSteelbladeRed:    cards.SingeingSteelbladeRed{},
	ids.SingeingSteelbladeYellow: cards.SingeingSteelbladeYellow{},
	ids.SingeingSteelbladeBlue:   cards.SingeingSteelbladeBlue{},

	ids.SirensOfSafeHarborRed:    cards.SirensOfSafeHarborRed{},
	ids.SirensOfSafeHarborYellow: cards.SirensOfSafeHarborYellow{},
	ids.SirensOfSafeHarborBlue:   cards.SirensOfSafeHarborBlue{},

	ids.SkyFireLanternsRed:    cards.SkyFireLanternsRed{},
	ids.SkyFireLanternsYellow: cards.SkyFireLanternsYellow{},
	ids.SkyFireLanternsBlue:   cards.SkyFireLanternsBlue{},

	ids.SloggismRed:    cards.SloggismRed{},
	ids.SloggismYellow: cards.SloggismYellow{},
	ids.SloggismBlue:   cards.SloggismBlue{},

	ids.SmashUpRed: cards.SmashUpRed{},

	ids.SnatchRed:    cards.SnatchRed{},
	ids.SnatchYellow: cards.SnatchYellow{},
	ids.SnatchBlue:   cards.SnatchBlue{},

	ids.SoundTheAlarmRed: cards.SoundTheAlarmRed{},

	ids.SpellbladeAssaultRed:    cards.SpellbladeAssaultRed{},
	ids.SpellbladeAssaultYellow: cards.SpellbladeAssaultYellow{},
	ids.SpellbladeAssaultBlue:   cards.SpellbladeAssaultBlue{},

	ids.SpellbladeStrikeRed:    cards.SpellbladeStrikeRed{},
	ids.SpellbladeStrikeYellow: cards.SpellbladeStrikeYellow{},
	ids.SpellbladeStrikeBlue:   cards.SpellbladeStrikeBlue{},

	ids.SplinteringDeadwoodRed:    cards.SplinteringDeadwoodRed{},
	ids.SplinteringDeadwoodYellow: cards.SplinteringDeadwoodYellow{},
	ids.SplinteringDeadwoodBlue:   cards.SplinteringDeadwoodBlue{},

	ids.SpringLoadRed:    cards.SpringLoadRed{},
	ids.SpringLoadYellow: cards.SpringLoadYellow{},
	ids.SpringLoadBlue:   cards.SpringLoadBlue{},

	ids.SpringboardSomersaultYellow: cards.SpringboardSomersaultYellow{},

	ids.StartingStakeYellow: cards.StartingStakeYellow{},

	ids.StonyWoottonhogRed:    cards.StonyWoottonhogRed{},
	ids.StonyWoottonhogYellow: cards.StonyWoottonhogYellow{},
	ids.StonyWoottonhogBlue:   cards.StonyWoottonhogBlue{},

	ids.StrategicPlanningRed:    cards.StrategicPlanningRed{},
	ids.StrategicPlanningYellow: cards.StrategicPlanningYellow{},
	ids.StrategicPlanningBlue:   cards.StrategicPlanningBlue{},

	ids.StrikeGoldRed:    cards.StrikeGoldRed{},
	ids.StrikeGoldYellow: cards.StrikeGoldYellow{},
	ids.StrikeGoldBlue:   cards.StrikeGoldBlue{},

	ids.SunKissRed:    cards.SunKissRed{},
	ids.SunKissYellow: cards.SunKissYellow{},
	ids.SunKissBlue:   cards.SunKissBlue{},

	ids.SurgingMilitiaRed:    cards.SurgingMilitiaRed{},
	ids.SurgingMilitiaYellow: cards.SurgingMilitiaYellow{},
	ids.SurgingMilitiaBlue:   cards.SurgingMilitiaBlue{},

	ids.SutcliffesResearchNotesRed:    cards.SutcliffesResearchNotesRed{},
	ids.SutcliffesResearchNotesYellow: cards.SutcliffesResearchNotesYellow{},
	ids.SutcliffesResearchNotesBlue:   cards.SutcliffesResearchNotesBlue{},

	ids.TalismanOfRecompenseYellow: cards.TalismanOfRecompenseYellow{},

	ids.TestOfStrengthRed: cards.TestOfStrengthRed{},

	ids.ThrustRed: cards.ThrustRed{},

	ids.TipOffRed:    cards.TipOffRed{},
	ids.TipOffYellow: cards.TipOffYellow{},
	ids.TipOffBlue:   cards.TipOffBlue{},

	ids.TitaniumBaubleBlue: cards.TitaniumBaubleBlue{},

	ids.TongueTiedRed: cards.TongueTiedRed{},

	ids.ToughenUpBlue: cards.ToughenUpBlue{},

	ids.TradeInRed:    cards.TradeInRed{},
	ids.TradeInYellow: cards.TradeInYellow{},
	ids.TradeInBlue:   cards.TradeInBlue{},

	ids.TremorOfIArathaelRed:    cards.TremorOfIArathaelRed{},
	ids.TremorOfIArathaelYellow: cards.TremorOfIArathaelYellow{},
	ids.TremorOfIArathaelBlue:   cards.TremorOfIArathaelBlue{},

	ids.TrotAlongBlue: cards.TrotAlongBlue{},

	ids.UnmovableRed:    cards.UnmovableRed{},
	ids.UnmovableYellow: cards.UnmovableYellow{},
	ids.UnmovableBlue:   cards.UnmovableBlue{},

	ids.VantagePointRed:    cards.VantagePointRed{},
	ids.VantagePointYellow: cards.VantagePointYellow{},
	ids.VantagePointBlue:   cards.VantagePointBlue{},

	ids.VexingMaliceRed:    cards.VexingMaliceRed{},
	ids.VexingMaliceYellow: cards.VexingMaliceYellow{},
	ids.VexingMaliceBlue:   cards.VexingMaliceBlue{},

	ids.VigorRushRed:    cards.VigorRushRed{},
	ids.VigorRushYellow: cards.VigorRushYellow{},
	ids.VigorRushBlue:   cards.VigorRushBlue{},

	ids.VisitTheBlacksmithBlue: cards.VisitTheBlacksmithBlue{},

	ids.WageGoldRed:    cards.WageGoldRed{},
	ids.WageGoldYellow: cards.WageGoldYellow{},
	ids.WageGoldBlue:   cards.WageGoldBlue{},

	ids.WalkThePlankRed:    cards.WalkThePlankRed{},
	ids.WalkThePlankYellow: cards.WalkThePlankYellow{},
	ids.WalkThePlankBlue:   cards.WalkThePlankBlue{},

	ids.WarmongersRecitalRed:    cards.WarmongersRecitalRed{},
	ids.WarmongersRecitalYellow: cards.WarmongersRecitalYellow{},
	ids.WarmongersRecitalBlue:   cards.WarmongersRecitalBlue{},

	ids.WaterTheSeedsRed:    cards.WaterTheSeedsRed{},
	ids.WaterTheSeedsYellow: cards.WaterTheSeedsYellow{},
	ids.WaterTheSeedsBlue:   cards.WaterTheSeedsBlue{},

	ids.WeepingBattlegroundRed:    cards.WeepingBattlegroundRed{},
	ids.WeepingBattlegroundYellow: cards.WeepingBattlegroundYellow{},
	ids.WeepingBattlegroundBlue:   cards.WeepingBattlegroundBlue{},

	ids.WhisperOfTheOracleRed:    cards.WhisperOfTheOracleRed{},
	ids.WhisperOfTheOracleYellow: cards.WhisperOfTheOracleYellow{},
	ids.WhisperOfTheOracleBlue:   cards.WhisperOfTheOracleBlue{},

	ids.WoundedBullRed:    cards.WoundedBullRed{},
	ids.WoundedBullYellow: cards.WoundedBullYellow{},
	ids.WoundedBullBlue:   cards.WoundedBullBlue{},

	ids.WoundingBlowRed:    cards.WoundingBlowRed{},
	ids.WoundingBlowYellow: cards.WoundingBlowYellow{},
	ids.WoundingBlowBlue:   cards.WoundingBlowBlue{},

	ids.WreckHavocRed:    cards.WreckHavocRed{},
	ids.WreckHavocYellow: cards.WreckHavocYellow{},
	ids.WreckHavocBlue:   cards.WreckHavocBlue{},

	ids.YintiYantiRed:    cards.YintiYantiRed{},
	ids.YintiYantiYellow: cards.YintiYantiYellow{},
	ids.YintiYantiBlue:   cards.YintiYantiBlue{},

	ids.ZealousBeltingRed:    cards.ZealousBeltingRed{},
	ids.ZealousBeltingYellow: cards.ZealousBeltingYellow{},
	ids.ZealousBeltingBlue:   cards.ZealousBeltingBlue{},
}
