// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var emissaryOfMoonTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type EmissaryOfMoonRed struct{}

func (EmissaryOfMoonRed) ID() ids.CardID                     { return ids.EmissaryOfMoonRed }
func (EmissaryOfMoonRed) Name() string                       { return "Emissary of Moon" }
func (EmissaryOfMoonRed) DisplayName() string                { return "Emissary of Moon [R]" }
func (EmissaryOfMoonRed) Cost(card.GameEngine) int           { return 0 }
func (EmissaryOfMoonRed) Pitch() int                         { return 1 }
func (EmissaryOfMoonRed) Attack() int                        { return 4 }
func (EmissaryOfMoonRed) Defense() int                       { return 2 }
func (EmissaryOfMoonRed) Types(card.GameEngine) card.TypeSet { return emissaryOfMoonTypes }
func (EmissaryOfMoonRed) GoAgain(card.GameEngine) bool       { return false }
func (EmissaryOfMoonRed) NotImplemented()                    {}
