// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var rallyTheCoastGuardTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type RallyTheCoastGuardRed struct{}

func (RallyTheCoastGuardRed) ID() ids.CardID                     { return ids.RallyTheCoastGuardRed }
func (RallyTheCoastGuardRed) Name() string                       { return "Rally the Coast Guard" }
func (RallyTheCoastGuardRed) DisplayName() string                { return "Rally the Coast Guard [R]" }
func (RallyTheCoastGuardRed) Cost(card.GameEngine) int           { return 3 }
func (RallyTheCoastGuardRed) Pitch() int                         { return 1 }
func (RallyTheCoastGuardRed) Attack() int                        { return 7 }
func (RallyTheCoastGuardRed) Defense() int                       { return 2 }
func (RallyTheCoastGuardRed) Types(card.GameEngine) card.TypeSet { return rallyTheCoastGuardTypes }
func (RallyTheCoastGuardRed) GoAgain(card.GameEngine) bool       { return false }
func (RallyTheCoastGuardRed) NotImplemented()                    {}

type RallyTheCoastGuardYellow struct{}

func (RallyTheCoastGuardYellow) ID() ids.CardID                     { return ids.RallyTheCoastGuardYellow }
func (RallyTheCoastGuardYellow) Name() string                       { return "Rally the Coast Guard" }
func (RallyTheCoastGuardYellow) DisplayName() string                { return "Rally the Coast Guard [Y]" }
func (RallyTheCoastGuardYellow) Cost(card.GameEngine) int           { return 3 }
func (RallyTheCoastGuardYellow) Pitch() int                         { return 2 }
func (RallyTheCoastGuardYellow) Attack() int                        { return 6 }
func (RallyTheCoastGuardYellow) Defense() int                       { return 2 }
func (RallyTheCoastGuardYellow) Types(card.GameEngine) card.TypeSet { return rallyTheCoastGuardTypes }
func (RallyTheCoastGuardYellow) GoAgain(card.GameEngine) bool       { return false }
func (RallyTheCoastGuardYellow) NotImplemented()                    {}

type RallyTheCoastGuardBlue struct{}

func (RallyTheCoastGuardBlue) ID() ids.CardID                     { return ids.RallyTheCoastGuardBlue }
func (RallyTheCoastGuardBlue) Name() string                       { return "Rally the Coast Guard" }
func (RallyTheCoastGuardBlue) DisplayName() string                { return "Rally the Coast Guard [B]" }
func (RallyTheCoastGuardBlue) Cost(card.GameEngine) int           { return 3 }
func (RallyTheCoastGuardBlue) Pitch() int                         { return 3 }
func (RallyTheCoastGuardBlue) Attack() int                        { return 5 }
func (RallyTheCoastGuardBlue) Defense() int                       { return 2 }
func (RallyTheCoastGuardBlue) Types(card.GameEngine) card.TypeSet { return rallyTheCoastGuardTypes }
func (RallyTheCoastGuardBlue) GoAgain(card.GameEngine) bool       { return false }
func (RallyTheCoastGuardBlue) NotImplemented()                    {}
