// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var talismanOfCremationTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type TalismanOfCremationBlue struct{}

func (TalismanOfCremationBlue) ID() ids.CardID                     { return ids.TalismanOfCremationBlue }
func (TalismanOfCremationBlue) Name() string                       { return "Talisman of Cremation" }
func (TalismanOfCremationBlue) DisplayName() string                { return "Talisman of Cremation [B]" }
func (TalismanOfCremationBlue) Cost(card.GameEngine) int           { return 0 }
func (TalismanOfCremationBlue) Pitch() int                         { return 3 }
func (TalismanOfCremationBlue) Attack() int                        { return 0 }
func (TalismanOfCremationBlue) Defense() int                       { return 0 }
func (TalismanOfCremationBlue) Types(card.GameEngine) card.TypeSet { return talismanOfCremationTypes }
func (TalismanOfCremationBlue) GoAgain(card.GameEngine) bool       { return true }
func (TalismanOfCremationBlue) NotImplemented()                    {}
