// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var hocusPocusTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction, card.TypeAttack)

type HocusPocusRed struct{}

func (HocusPocusRed) ID() ids.CardID                     { return ids.HocusPocusRed }
func (HocusPocusRed) Name() string                       { return "Hocus Pocus" }
func (HocusPocusRed) DisplayName() string                { return "Hocus Pocus [R]" }
func (HocusPocusRed) Cost(card.GameEngine) int           { return 0 }
func (HocusPocusRed) Pitch() int                         { return 1 }
func (HocusPocusRed) Attack() int                        { return 3 }
func (HocusPocusRed) Defense() int                       { return 3 }
func (HocusPocusRed) Types(card.GameEngine) card.TypeSet { return hocusPocusTypes }
func (HocusPocusRed) GoAgain(card.GameEngine) bool       { return false }

type HocusPocusYellow struct{}

func (HocusPocusYellow) ID() ids.CardID                     { return ids.HocusPocusYellow }
func (HocusPocusYellow) Name() string                       { return "Hocus Pocus" }
func (HocusPocusYellow) DisplayName() string                { return "Hocus Pocus [Y]" }
func (HocusPocusYellow) Cost(card.GameEngine) int           { return 0 }
func (HocusPocusYellow) Pitch() int                         { return 2 }
func (HocusPocusYellow) Attack() int                        { return 2 }
func (HocusPocusYellow) Defense() int                       { return 3 }
func (HocusPocusYellow) Types(card.GameEngine) card.TypeSet { return hocusPocusTypes }
func (HocusPocusYellow) GoAgain(card.GameEngine) bool       { return false }

type HocusPocusBlue struct{}

func (HocusPocusBlue) ID() ids.CardID                     { return ids.HocusPocusBlue }
func (HocusPocusBlue) Name() string                       { return "Hocus Pocus" }
func (HocusPocusBlue) DisplayName() string                { return "Hocus Pocus [B]" }
func (HocusPocusBlue) Cost(card.GameEngine) int           { return 0 }
func (HocusPocusBlue) Pitch() int                         { return 3 }
func (HocusPocusBlue) Attack() int                        { return 1 }
func (HocusPocusBlue) Defense() int                       { return 3 }
func (HocusPocusBlue) Types(card.GameEngine) card.TypeSet { return hocusPocusTypes }
func (HocusPocusBlue) GoAgain(card.GameEngine) bool       { return false }
