// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var nipAtTheHeelsTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAttackReaction)

type NipAtTheHeelsBlue struct{}

func (NipAtTheHeelsBlue) ID() ids.CardID                     { return ids.NipAtTheHeelsBlue }
func (NipAtTheHeelsBlue) Name() string                       { return "Nip at the Heels" }
func (NipAtTheHeelsBlue) DisplayName() string                { return "Nip at the Heels [B]" }
func (NipAtTheHeelsBlue) Cost(card.GameEngine) int           { return 0 }
func (NipAtTheHeelsBlue) Pitch() int                         { return 3 }
func (NipAtTheHeelsBlue) Attack() int                        { return 0 }
func (NipAtTheHeelsBlue) Defense() int                       { return 3 }
func (NipAtTheHeelsBlue) Types(card.GameEngine) card.TypeSet { return nipAtTheHeelsTypes }
func (NipAtTheHeelsBlue) GoAgain(card.GameEngine) bool       { return false }
