// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var outMuscleTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type OutMuscleRed struct{}

func (OutMuscleRed) ID() ids.CardID                     { return ids.OutMuscleRed }
func (OutMuscleRed) Name() string                       { return "Out Muscle" }
func (OutMuscleRed) DisplayName() string                { return "Out Muscle [R]" }
func (OutMuscleRed) Cost(card.GameEngine) int           { return 3 }
func (OutMuscleRed) Pitch() int                         { return 1 }
func (OutMuscleRed) Attack() int                        { return 6 }
func (OutMuscleRed) Defense() int                       { return 2 }
func (OutMuscleRed) Types(card.GameEngine) card.TypeSet { return outMuscleTypes }
func (OutMuscleRed) GoAgain(card.GameEngine) bool       { return false }

type OutMuscleYellow struct{}

func (OutMuscleYellow) ID() ids.CardID                     { return ids.OutMuscleYellow }
func (OutMuscleYellow) Name() string                       { return "Out Muscle" }
func (OutMuscleYellow) DisplayName() string                { return "Out Muscle [Y]" }
func (OutMuscleYellow) Cost(card.GameEngine) int           { return 3 }
func (OutMuscleYellow) Pitch() int                         { return 2 }
func (OutMuscleYellow) Attack() int                        { return 5 }
func (OutMuscleYellow) Defense() int                       { return 2 }
func (OutMuscleYellow) Types(card.GameEngine) card.TypeSet { return outMuscleTypes }
func (OutMuscleYellow) GoAgain(card.GameEngine) bool       { return false }

type OutMuscleBlue struct{}

func (OutMuscleBlue) ID() ids.CardID                     { return ids.OutMuscleBlue }
func (OutMuscleBlue) Name() string                       { return "Out Muscle" }
func (OutMuscleBlue) DisplayName() string                { return "Out Muscle [B]" }
func (OutMuscleBlue) Cost(card.GameEngine) int           { return 3 }
func (OutMuscleBlue) Pitch() int                         { return 3 }
func (OutMuscleBlue) Attack() int                        { return 4 }
func (OutMuscleBlue) Defense() int                       { return 2 }
func (OutMuscleBlue) Types(card.GameEngine) card.TypeSet { return outMuscleTypes }
func (OutMuscleBlue) GoAgain(card.GameEngine) bool       { return false }
