// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var overloadTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type OverloadRed struct{}

func (OverloadRed) ID() ids.CardID                     { return ids.OverloadRed }
func (OverloadRed) Name() string                       { return "Overload" }
func (OverloadRed) DisplayName() string                { return "Overload [R]" }
func (OverloadRed) Cost(card.GameEngine) int           { return 0 }
func (OverloadRed) Pitch() int                         { return 1 }
func (OverloadRed) Attack() int                        { return 3 }
func (OverloadRed) Defense() int                       { return 2 }
func (OverloadRed) Types(card.GameEngine) card.TypeSet { return overloadTypes }
func (OverloadRed) GoAgain(card.GameEngine) bool       { return false }

type OverloadYellow struct{}

func (OverloadYellow) ID() ids.CardID                     { return ids.OverloadYellow }
func (OverloadYellow) Name() string                       { return "Overload" }
func (OverloadYellow) DisplayName() string                { return "Overload [Y]" }
func (OverloadYellow) Cost(card.GameEngine) int           { return 0 }
func (OverloadYellow) Pitch() int                         { return 2 }
func (OverloadYellow) Attack() int                        { return 2 }
func (OverloadYellow) Defense() int                       { return 2 }
func (OverloadYellow) Types(card.GameEngine) card.TypeSet { return overloadTypes }
func (OverloadYellow) GoAgain(card.GameEngine) bool       { return false }

type OverloadBlue struct{}

func (OverloadBlue) ID() ids.CardID                     { return ids.OverloadBlue }
func (OverloadBlue) Name() string                       { return "Overload" }
func (OverloadBlue) DisplayName() string                { return "Overload [B]" }
func (OverloadBlue) Cost(card.GameEngine) int           { return 0 }
func (OverloadBlue) Pitch() int                         { return 3 }
func (OverloadBlue) Attack() int                        { return 1 }
func (OverloadBlue) Defense() int                       { return 2 }
func (OverloadBlue) Types(card.GameEngine) card.TypeSet { return overloadTypes }
func (OverloadBlue) GoAgain(card.GameEngine) bool       { return false }
