// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var peaceOfMindTypes = card.NewTypeSet(card.TypeGeneric, card.TypeInstant)

type PeaceOfMindRed struct{}

func (PeaceOfMindRed) ID() ids.CardID                     { return ids.PeaceOfMindRed }
func (PeaceOfMindRed) Name() string                       { return "Peace of Mind" }
func (PeaceOfMindRed) DisplayName() string                { return "Peace of Mind [R]" }
func (PeaceOfMindRed) Cost(card.GameEngine) int           { return 2 }
func (PeaceOfMindRed) Pitch() int                         { return 1 }
func (PeaceOfMindRed) Attack() int                        { return 0 }
func (PeaceOfMindRed) Defense() int                       { return 4 }
func (PeaceOfMindRed) Types(card.GameEngine) card.TypeSet { return peaceOfMindTypes }
func (PeaceOfMindRed) GoAgain(card.GameEngine) bool       { return false }

type PeaceOfMindYellow struct{}

func (PeaceOfMindYellow) ID() ids.CardID                     { return ids.PeaceOfMindYellow }
func (PeaceOfMindYellow) Name() string                       { return "Peace of Mind" }
func (PeaceOfMindYellow) DisplayName() string                { return "Peace of Mind [Y]" }
func (PeaceOfMindYellow) Cost(card.GameEngine) int           { return 2 }
func (PeaceOfMindYellow) Pitch() int                         { return 2 }
func (PeaceOfMindYellow) Attack() int                        { return 0 }
func (PeaceOfMindYellow) Defense() int                       { return 3 }
func (PeaceOfMindYellow) Types(card.GameEngine) card.TypeSet { return peaceOfMindTypes }
func (PeaceOfMindYellow) GoAgain(card.GameEngine) bool       { return false }

type PeaceOfMindBlue struct{}

func (PeaceOfMindBlue) ID() ids.CardID                     { return ids.PeaceOfMindBlue }
func (PeaceOfMindBlue) Name() string                       { return "Peace of Mind" }
func (PeaceOfMindBlue) DisplayName() string                { return "Peace of Mind [B]" }
func (PeaceOfMindBlue) Cost(card.GameEngine) int           { return 2 }
func (PeaceOfMindBlue) Pitch() int                         { return 3 }
func (PeaceOfMindBlue) Attack() int                        { return 0 }
func (PeaceOfMindBlue) Defense() int                       { return 2 }
func (PeaceOfMindBlue) Types(card.GameEngine) card.TypeSet { return peaceOfMindTypes }
func (PeaceOfMindBlue) GoAgain(card.GameEngine) bool       { return false }
