// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var sunKissTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type SunKissRed struct{}

func (SunKissRed) ID() ids.CardID                     { return ids.SunKissRed }
func (SunKissRed) Name() string                       { return "Sun Kiss" }
func (SunKissRed) DisplayName() string                { return "Sun Kiss [R]" }
func (SunKissRed) Cost(card.GameEngine) int           { return 0 }
func (SunKissRed) Pitch() int                         { return 1 }
func (SunKissRed) Attack() int                        { return 0 }
func (SunKissRed) Defense() int                       { return 2 }
func (SunKissRed) Types(card.GameEngine) card.TypeSet { return sunKissTypes }
func (SunKissRed) GoAgain(card.GameEngine) bool       { return false }

type SunKissYellow struct{}

func (SunKissYellow) ID() ids.CardID                     { return ids.SunKissYellow }
func (SunKissYellow) Name() string                       { return "Sun Kiss" }
func (SunKissYellow) DisplayName() string                { return "Sun Kiss [Y]" }
func (SunKissYellow) Cost(card.GameEngine) int           { return 0 }
func (SunKissYellow) Pitch() int                         { return 2 }
func (SunKissYellow) Attack() int                        { return 0 }
func (SunKissYellow) Defense() int                       { return 2 }
func (SunKissYellow) Types(card.GameEngine) card.TypeSet { return sunKissTypes }
func (SunKissYellow) GoAgain(card.GameEngine) bool       { return false }

type SunKissBlue struct{}

func (SunKissBlue) ID() ids.CardID                     { return ids.SunKissBlue }
func (SunKissBlue) Name() string                       { return "Sun Kiss" }
func (SunKissBlue) DisplayName() string                { return "Sun Kiss [B]" }
func (SunKissBlue) Cost(card.GameEngine) int           { return 0 }
func (SunKissBlue) Pitch() int                         { return 3 }
func (SunKissBlue) Attack() int                        { return 0 }
func (SunKissBlue) Defense() int                       { return 2 }
func (SunKissBlue) Types(card.GameEngine) card.TypeSet { return sunKissTypes }
func (SunKissBlue) GoAgain(card.GameEngine) bool       { return false }
