// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/v2/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var sutcliffeSResearchNotesTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction)

type SutcliffesResearchNotesRed struct{}

func (SutcliffesResearchNotesRed) ID() ids.CardID           { return ids.SutcliffesResearchNotesRed }
func (SutcliffesResearchNotesRed) Name() string             { return "Sutcliffe's Research Notes" }
func (SutcliffesResearchNotesRed) DisplayName() string      { return "Sutcliffe's Research Notes [R]" }
func (SutcliffesResearchNotesRed) Cost(card.GameEngine) int { return 1 }
func (SutcliffesResearchNotesRed) Pitch() int               { return 1 }
func (SutcliffesResearchNotesRed) Attack() int              { return 0 }
func (SutcliffesResearchNotesRed) Defense() int             { return 2 }
func (SutcliffesResearchNotesRed) Types(card.GameEngine) card.TypeSet {
	return sutcliffeSResearchNotesTypes
}
func (SutcliffesResearchNotesRed) GoAgain(card.GameEngine) bool { return true }

type SutcliffesResearchNotesYellow struct{}

func (SutcliffesResearchNotesYellow) ID() ids.CardID           { return ids.SutcliffesResearchNotesYellow }
func (SutcliffesResearchNotesYellow) Name() string             { return "Sutcliffe's Research Notes" }
func (SutcliffesResearchNotesYellow) DisplayName() string      { return "Sutcliffe's Research Notes [Y]" }
func (SutcliffesResearchNotesYellow) Cost(card.GameEngine) int { return 1 }
func (SutcliffesResearchNotesYellow) Pitch() int               { return 2 }
func (SutcliffesResearchNotesYellow) Attack() int              { return 0 }
func (SutcliffesResearchNotesYellow) Defense() int             { return 2 }
func (SutcliffesResearchNotesYellow) Types(card.GameEngine) card.TypeSet {
	return sutcliffeSResearchNotesTypes
}
func (SutcliffesResearchNotesYellow) GoAgain(card.GameEngine) bool { return true }

type SutcliffesResearchNotesBlue struct{}

func (SutcliffesResearchNotesBlue) ID() ids.CardID           { return ids.SutcliffesResearchNotesBlue }
func (SutcliffesResearchNotesBlue) Name() string             { return "Sutcliffe's Research Notes" }
func (SutcliffesResearchNotesBlue) DisplayName() string      { return "Sutcliffe's Research Notes [B]" }
func (SutcliffesResearchNotesBlue) Cost(card.GameEngine) int { return 1 }
func (SutcliffesResearchNotesBlue) Pitch() int               { return 3 }
func (SutcliffesResearchNotesBlue) Attack() int              { return 0 }
func (SutcliffesResearchNotesBlue) Defense() int             { return 2 }
func (SutcliffesResearchNotesBlue) Types(card.GameEngine) card.TypeSet {
	return sutcliffeSResearchNotesTypes
}
func (SutcliffesResearchNotesBlue) GoAgain(card.GameEngine) bool { return true }
