// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var vexingMaliceTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction, card.TypeAttack)

type VexingMaliceRed struct{}

func (VexingMaliceRed) ID() ids.CardID                     { return ids.VexingMaliceRed }
func (VexingMaliceRed) Name() string                       { return "Vexing Malice" }
func (VexingMaliceRed) DisplayName() string                { return "Vexing Malice [R]" }
func (VexingMaliceRed) Cost(card.GameEngine) int           { return 1 }
func (VexingMaliceRed) Pitch() int                         { return 1 }
func (VexingMaliceRed) Attack() int                        { return 3 }
func (VexingMaliceRed) Defense() int                       { return 3 }
func (VexingMaliceRed) Types(card.GameEngine) card.TypeSet { return vexingMaliceTypes }
func (VexingMaliceRed) GoAgain(card.GameEngine) bool       { return false }

type VexingMaliceYellow struct{}

func (VexingMaliceYellow) ID() ids.CardID                     { return ids.VexingMaliceYellow }
func (VexingMaliceYellow) Name() string                       { return "Vexing Malice" }
func (VexingMaliceYellow) DisplayName() string                { return "Vexing Malice [Y]" }
func (VexingMaliceYellow) Cost(card.GameEngine) int           { return 1 }
func (VexingMaliceYellow) Pitch() int                         { return 2 }
func (VexingMaliceYellow) Attack() int                        { return 2 }
func (VexingMaliceYellow) Defense() int                       { return 3 }
func (VexingMaliceYellow) Types(card.GameEngine) card.TypeSet { return vexingMaliceTypes }
func (VexingMaliceYellow) GoAgain(card.GameEngine) bool       { return false }

type VexingMaliceBlue struct{}

func (VexingMaliceBlue) ID() ids.CardID                     { return ids.VexingMaliceBlue }
func (VexingMaliceBlue) Name() string                       { return "Vexing Malice" }
func (VexingMaliceBlue) DisplayName() string                { return "Vexing Malice [B]" }
func (VexingMaliceBlue) Cost(card.GameEngine) int           { return 1 }
func (VexingMaliceBlue) Pitch() int                         { return 3 }
func (VexingMaliceBlue) Attack() int                        { return 1 }
func (VexingMaliceBlue) Defense() int                       { return 3 }
func (VexingMaliceBlue) Types(card.GameEngine) card.TypeSet { return vexingMaliceTypes }
func (VexingMaliceBlue) GoAgain(card.GameEngine) bool       { return false }
