package card

// ID uniquely identifies a printed card. The zero value (Invalid) is reserved so zero-valued
// IDs in other data structures can be detected as "unset".
//
// IDs are stable within a build but NOT a persistence format: adding or removing cards may
// renumber existing entries. Treat IDs as opaque in-process handles.
//
// Each pitch variant (Red / Yellow / Blue) is a distinct card and gets its own ID. Weapons get
// IDs too so every Card implementation has a unique, non-zero identifier.
type ID uint16

// Invalid is the sentinel zero value. Valid IDs start at 1.
const Invalid ID = 0

// Runeblade card IDs. Ordered alphabetically by card name, Red → Yellow → Blue within each family.
// Sigil of Deadwood only has a Blue variant (no R/Y printings).
const (
	AetherSlashRed ID = iota + 1
	AetherSlashYellow
	AetherSlashBlue
	AmplifyTheArknightRed
	AmplifyTheArknightYellow
	AmplifyTheArknightBlue
	ArcaneCussingRed
	ArcaneCussingYellow
	ArcaneCussingBlue
	ArcanicCrackleRed
	ArcanicCrackleYellow
	ArcanicCrackleBlue
	ArcanicSpikeRed
	ArcanicSpikeYellow
	ArcanicSpikeBlue
	BlessingOfOccultRed
	BlessingOfOccultYellow
	BlessingOfOccultBlue
	BloodspillInvocationRed
	BloodspillInvocationYellow
	BloodspillInvocationBlue
	CondemnToSlaughterRed
	CondemnToSlaughterYellow
	CondemnToSlaughterBlue
	ConsumingVolitionRed
	ConsumingVolitionYellow
	ConsumingVolitionBlue
	DeathlyDuetRed
	DeathlyDuetYellow
	DeathlyDuetBlue
	DrawnToTheDarkDimensionRed
	DrawnToTheDarkDimensionYellow
	DrawnToTheDarkDimensionBlue
	DrowningDireRed
	DrowningDireYellow
	DrowningDireBlue
	HitTheHighNotesRed
	HitTheHighNotesYellow
	HitTheHighNotesBlue
	HocusPocusRed
	HocusPocusYellow
	HocusPocusBlue
	MaleficIncantationRed
	MaleficIncantationYellow
	MaleficIncantationBlue
	MauvrionSkiesRed
	MauvrionSkiesYellow
	MauvrionSkiesBlue
	MeatAndGreetRed
	MeatAndGreetYellow
	MeatAndGreetBlue
	OathOfTheArknightRed
	OathOfTheArknightYellow
	OathOfTheArknightBlue
	ReadTheRunesRed
	ReadTheRunesYellow
	ReadTheRunesBlue
	ReduceToRunechantRed
	ReduceToRunechantYellow
	ReduceToRunechantBlue
	ReekOfCorruptionRed
	ReekOfCorruptionYellow
	ReekOfCorruptionBlue
	RuneFlashRed
	RuneFlashYellow
	RuneFlashBlue
	RunebloodIncantationRed
	RunebloodIncantationYellow
	RunebloodIncantationBlue
	RuneragerSwarmRed
	RuneragerSwarmYellow
	RuneragerSwarmBlue
	RunicFellingsongRed
	RunicFellingsongYellow
	RunicFellingsongBlue
	RunicReapingRed
	RunicReapingYellow
	RunicReapingBlue
	ShrillOfSkullformRed
	ShrillOfSkullformYellow
	ShrillOfSkullformBlue
	SigilOfDeadwoodBlue
	SigilOfSilphidaeBlue
	SigilOfSufferingRed
	SigilOfSufferingYellow
	SigilOfSufferingBlue
	SigilOfTheArknightBlue
	SingeingSteelbladeRed
	SingeingSteelbladeYellow
	SingeingSteelbladeBlue
	SkyFireLanternsRed
	SkyFireLanternsYellow
	SkyFireLanternsBlue
	SpellbladeAssaultRed
	SpellbladeAssaultYellow
	SpellbladeAssaultBlue
	SpellbladeStrikeRed
	SpellbladeStrikeYellow
	SpellbladeStrikeBlue
	SplinteringDeadwoodRed
	SplinteringDeadwoodYellow
	SplinteringDeadwoodBlue
	SutcliffesResearchNotesRed
	SutcliffesResearchNotesYellow
	SutcliffesResearchNotesBlue
	VantagePointRed
	VantagePointYellow
	VantagePointBlue
	VexingMaliceRed
	VexingMaliceYellow
	VexingMaliceBlue
	WeepingBattlegroundRed
	WeepingBattlegroundYellow
	WeepingBattlegroundBlue

	// Generic card IDs. Ordered alphabetically by card name, Red → Yellow → Blue within each family.
	AdrenalineRushRed
	AdrenalineRushYellow
	AdrenalineRushBlue
	AmuletOfAssertivenessYellow
	AmuletOfEchoesBlue
	AmuletOfHavencallBlue
	AmuletOfIgnitionYellow
	AmuletOfInterventionBlue
	AmuletOfOblationBlue
	ArcanePolarityRed
	ArcanePolarityYellow
	ArcanePolarityBlue
	BackAlleyBreaklineRed
	BackAlleyBreaklineYellow
	BackAlleyBreaklineBlue
	BarragingBrawnhideRed
	BarragingBrawnhideYellow
	BarragingBrawnhideBlue
	BattlefrontBastionRed
	BattlefrontBastionYellow
	BattlefrontBastionBlue
	BelittleRed
	BelittleYellow
	BelittleBlue
	BladeFlashBlue
	BlanchRed
	BlanchYellow
	BlanchBlue
	BlowForABlowRed
	BlusterBuffRed
	BrandishRed
	BrandishYellow
	BrandishBlue
	BrothersInArmsRed
	BrothersInArmsYellow
	BrothersInArmsBlue
	BrushOffRed
	BrushOffYellow
	BrushOffBlue
	BrutalAssaultRed
	BrutalAssaultYellow
	BrutalAssaultBlue
	CadaverousContrabandRed
	CadaverousContrabandYellow
	CadaverousContrabandBlue
	CalmingBreezeRed
	CaptainsCallRed
	CaptainsCallYellow
	CaptainsCallBlue
	CashInYellow
	ChestPuffRed
	ClapEmInIronsBlue
	ClarityPotionBlue
	ClearwaterElixirRed
	ComeToFightRed
	ComeToFightYellow
	ComeToFightBlue
	CountYourBlessingsRed
	CountYourBlessingsYellow
	CountYourBlessingsBlue
	CrackedBaubleYellow
	CrashDownTheGatesRed
	CrashDownTheGatesYellow
	CrashDownTheGatesBlue
	CriticalStrikeRed
	CriticalStrikeYellow
	CriticalStrikeBlue
	CutDownToSizeRed
	CutDownToSizeYellow
	CutDownToSizeBlue
	DemolitionCrewRed
	DemolitionCrewYellow
	DemolitionCrewBlue
	DestructiveDeliberationRed
	DestructiveDeliberationYellow
	DestructiveDeliberationBlue
	DestructiveTendenciesBlue
	DodgeBlue
	DownButNotOutRed
	DownButNotOutYellow
	DownButNotOutBlue
	DragDownRed
	DragDownYellow
	DragDownBlue
	DroneOfBrutalityRed
	DroneOfBrutalityYellow
	DroneOfBrutalityBlue
	EirinasPrayerRed
	EirinasPrayerYellow
	EirinasPrayerBlue
	EmissaryOfMoonRed
	EmissaryOfTidesRed
	EmissaryOfWindRed
	EnchantingMelodyRed
	EnchantingMelodyYellow
	EnchantingMelodyBlue
	EnergyPotionBlue
	EvasiveLeapRed
	EvasiveLeapYellow
	EvasiveLeapBlue
	EvenBiggerThanThatRed
	EvenBiggerThanThatYellow
	EvenBiggerThanThatBlue
	ExposedBlue
	FactFindingMissionRed
	FactFindingMissionYellow
	FactFindingMissionBlue
	FateForeseenRed
	FateForeseenYellow
	FateForeseenBlue
	FeistyLocalsRed
	FeistyLocalsYellow
	FeistyLocalsBlue
	FerventForerunnerRed
	FerventForerunnerYellow
	FerventForerunnerBlue
	FiddlersGreenRed
	FiddlersGreenYellow
	FiddlersGreenBlue
	FlexRed
	FlexYellow
	FlexBlue
	FlockOfTheFeatherWalkersRed
	FlockOfTheFeatherWalkersYellow
	FlockOfTheFeatherWalkersBlue
	FlyingHighRed
	FlyingHighYellow
	FlyingHighBlue
	FoolsGoldYellow
	ForceSightRed
	ForceSightYellow
	ForceSightBlue
	FreewheelingRenegadesRed
	FreewheelingRenegadesYellow
	FreewheelingRenegadesBlue
	FrontlineScoutRed
	FrontlineScoutYellow
	FrontlineScoutBlue
	FyendalsFightingSpiritRed
	FyendalsFightingSpiritYellow
	FyendalsFightingSpiritBlue
	GravekeepingRed
	GravekeepingYellow
	GravekeepingBlue
	HandBehindThePenRed
	HealingBalmRed
	HealingBalmYellow
	HealingBalmBlue
	HealingPotionBlue
	HighStrikerRed
	HighStrikerYellow
	HighStrikerBlue
	HumbleRed
	HumbleYellow
	HumbleBlue
	ImperialSealOfCommandRed
	InfectiousHostRed
	InfectiousHostYellow
	InfectiousHostBlue
	JackBeNimbleRed
	JackBeQuickRed
	LayLowYellow
	LeadTheChargeRed
	LeadTheChargeYellow
	LeadTheChargeBlue
	LifeForALifeRed
	LifeForALifeYellow
	LifeForALifeBlue
	LifeOfThePartyRed
	LifeOfThePartyYellow
	LifeOfThePartyBlue
	LookingForAScrapRed
	LookingForAScrapYellow
	LookingForAScrapBlue
	LookTuffRed
	LungingPressBlue
	MemorialGroundRed
	MemorialGroundYellow
	MemorialGroundBlue
	MinnowismRed
	MinnowismYellow
	MinnowismBlue
	MoneyOrYourLifeRed
	MoneyOrYourLifeYellow
	MoneyOrYourLifeBlue
	MoneyWhereYaMouthIsRed
	MoneyWhereYaMouthIsYellow
	MoneyWhereYaMouthIsBlue
	MoonWishRed
	MoonWishYellow
	MoonWishBlue
	MuscleMuttYellow
	NimbleStrikeRed
	NimbleStrikeYellow
	NimbleStrikeBlue
	NimblismRed
	NimblismYellow
	NimblismBlue
	NimbyRed
	NimbyYellow
	NimbyBlue
	NipAtTheHeelsBlue
	OasisRespiteRed
	OasisRespiteYellow
	OasisRespiteBlue
	OnAKnifeEdgeYellow
	OnTheHorizonRed
	OnTheHorizonYellow
	OnTheHorizonBlue
	OutedRed
	OutMuscleRed
	OutMuscleYellow
	OutMuscleBlue
	OverloadRed
	OverloadYellow
	OverloadBlue
	PeaceOfMindRed
	PeaceOfMindYellow
	PeaceOfMindBlue
	PerformanceBonusRed
	PerformanceBonusYellow
	PerformanceBonusBlue
	PickACardAnyCardRed
	PickACardAnyCardYellow
	PickACardAnyCardBlue
	PilferTheTombBlue
	PlunderRunRed
	PlunderRunYellow
	PlunderRunBlue
	PotionOfDejaVuBlue
	PotionOfIronhideBlue
	PotionOfLuckBlue
	PotionOfSeeingBlue
	PotionOfStrengthBlue
	PoundForPoundRed
	PoundForPoundYellow
	PoundForPoundBlue
	PrimeTheCrowdRed
	PrimeTheCrowdYellow
	PrimeTheCrowdBlue
	PromiseOfPlentyRed
	PromiseOfPlentyYellow
	PromiseOfPlentyBlue
	PublicBountyRed
	PublicBountyYellow
	PublicBountyBlue
	PummelRed
	PummelYellow
	PummelBlue
	PunchAboveYourWeightRed
	PunchAboveYourWeightYellow
	PunchAboveYourWeightBlue
	PursueToTheEdgeOfOblivionRed
	PursueToThePitsOfDespairRed
	PushThePointRed
	PushThePointYellow
	PushThePointBlue
	PutInContextBlue
	RagingOnslaughtRed
	RagingOnslaughtYellow
	RagingOnslaughtBlue
	RallyTheCoastGuardRed
	RallyTheCoastGuardYellow
	RallyTheCoastGuardBlue
	RallyTheRearguardRed
	RallyTheRearguardYellow
	RallyTheRearguardBlue
	RansackAndRazeBlue
	RavenousRabbleRed
	RavenousRabbleYellow
	RavenousRabbleBlue
	RazorReflexRed
	RazorReflexYellow
	RazorReflexBlue
	RegainComposureBlue
	RegurgitatingSlogRed
	RegurgitatingSlogYellow
	RegurgitatingSlogBlue
	ReinforceTheLineRed
	ReinforceTheLineYellow
	ReinforceTheLineBlue
	RelentlessPursuitBlue
	RestvineElixirRed
	RiftingRed
	RiftingYellow
	RiftingBlue
	RightBehindYouRed
	RightBehindYouYellow
	RightBehindYouBlue
	RiseAboveRed
	RiseAboveYellow
	RiseAboveBlue
	SapwoodElixirRed
	ScarForAScarRed
	ScarForAScarYellow
	ScarForAScarBlue
	ScourTheBattlescapeRed
	ScourTheBattlescapeYellow
	ScourTheBattlescapeBlue
	ScoutThePeripheryRed
	ScoutThePeripheryYellow
	ScoutThePeripheryBlue
	SeekHorizonRed
	SeekHorizonYellow
	SeekHorizonBlue
	ShatterSorceryBlue
	SiftRed
	SiftYellow
	SiftBlue
	SigilOfCyclesBlue
	SigilOfFyendalBlue
	SigilOfProtectionRed
	SigilOfProtectionYellow
	SigilOfProtectionBlue
	SigilOfSolaceRed
	SigilOfSolaceYellow
	SigilOfSolaceBlue
	SinkBelowRed
	SinkBelowYellow
	SinkBelowBlue
	SirensOfSafeHarborRed
	SirensOfSafeHarborYellow
	SirensOfSafeHarborBlue
	SloggismRed
	SloggismYellow
	SloggismBlue
	SmashingGoodTimeRed
	SmashingGoodTimeYellow
	SmashingGoodTimeBlue
	SmashUpRed
	SnatchRed
	SnatchYellow
	SnatchBlue
	SoundTheAlarmRed
	SpringboardSomersaultYellow
	SpringLoadRed
	SpringLoadYellow
	SpringLoadBlue
	StartingStakeYellow
	StonyWoottonhogRed
	StonyWoottonhogYellow
	StonyWoottonhogBlue
	StrategicPlanningRed
	StrategicPlanningYellow
	StrategicPlanningBlue
	StrikeGoldRed
	StrikeGoldYellow
	StrikeGoldBlue
	SunKissRed
	SunKissYellow
	SunKissBlue
	SurgingMilitiaRed
	SurgingMilitiaYellow
	SurgingMilitiaBlue
	TalismanOfBalanceBlue
	TalismanOfCremationBlue
	TalismanOfDousingYellow
	TalismanOfFeatherfootYellow
	TalismanOfRecompenseYellow
	TalismanOfTithesBlue
	TalismanOfWarfareYellow
	TestOfStrengthRed
	ThrustRed
	TimesnapPotionBlue
	TipOffRed
	TipOffYellow
	TipOffBlue
	TitaniumBaubleBlue
	TitForTatBlue
	TongueTiedRed
	ToughenUpBlue
	TradeInRed
	TradeInYellow
	TradeInBlue
	TremorOfIArathaelRed
	TremorOfIArathaelYellow
	TremorOfIArathaelBlue
	TrotAlongBlue
	UnmovableRed
	UnmovableYellow
	UnmovableBlue
	VigorRushRed
	VigorRushYellow
	VigorRushBlue
	VisitTheBlacksmithBlue
	WageGoldRed
	WageGoldYellow
	WageGoldBlue
	WalkThePlankRed
	WalkThePlankYellow
	WalkThePlankBlue
	WarmongersRecitalRed
	WarmongersRecitalYellow
	WarmongersRecitalBlue
	WaterTheSeedsRed
	WaterTheSeedsYellow
	WaterTheSeedsBlue
	WhisperOfTheOracleRed
	WhisperOfTheOracleYellow
	WhisperOfTheOracleBlue
	WoundedBullRed
	WoundedBullYellow
	WoundedBullBlue
	WoundingBlowRed
	WoundingBlowYellow
	WoundingBlowBlue
	WreckHavocRed
	WreckHavocYellow
	WreckHavocBlue
	YintiYantiRed
	YintiYantiYellow
	YintiYantiBlue
	ZealousBeltingRed
	ZealousBeltingYellow
	ZealousBeltingBlue

	// Weapon IDs. Weapons aren't in the card registry (decks don't hold weapons) but each gets a
	// unique ID so every Card implementation has a non-zero ID.
	NebulaBladeID
	ReapingBladeID
	ScepterOfPainID
	TalisharID

	// Test-only synthetic card IDs. Registered so hand.Best's cache key lookup doesn't panic on
	// them. Not real FaB cards and must not appear in production decks.
	FakeRedAttack
	FakeBlueAttack
	FakeYellowAttack
	FakeDrawCantrip
	FakeCostlyDraw
	FakeCostlyAttack
	FakePitchOneDR
	FakeHugeAttack
)
