// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var battlefrontBastionTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type BattlefrontBastionRed struct{}

func (BattlefrontBastionRed) ID() ids.CardID           { return ids.BattlefrontBastionRed }
func (BattlefrontBastionRed) Name() string             { return "Battlefront Bastion" }
func (BattlefrontBastionRed) DisplayName() string      { return "Battlefront Bastion [R]" }
func (BattlefrontBastionRed) Cost(card.GameEngine) int { return 3 }
func (BattlefrontBastionRed) Pitch() int               { return 1 }
func (BattlefrontBastionRed) Attack() int              { return 7 }
func (BattlefrontBastionRed) Defense() int             { return 2 }
func (BattlefrontBastionRed) Types() card.TypeSet      { return battlefrontBastionTypes }
func (BattlefrontBastionRed) GoAgain() bool            { return false }

type BattlefrontBastionYellow struct{}

func (BattlefrontBastionYellow) ID() ids.CardID           { return ids.BattlefrontBastionYellow }
func (BattlefrontBastionYellow) Name() string             { return "Battlefront Bastion" }
func (BattlefrontBastionYellow) DisplayName() string      { return "Battlefront Bastion [Y]" }
func (BattlefrontBastionYellow) Cost(card.GameEngine) int { return 3 }
func (BattlefrontBastionYellow) Pitch() int               { return 2 }
func (BattlefrontBastionYellow) Attack() int              { return 6 }
func (BattlefrontBastionYellow) Defense() int             { return 2 }
func (BattlefrontBastionYellow) Types() card.TypeSet      { return battlefrontBastionTypes }
func (BattlefrontBastionYellow) GoAgain() bool            { return false }

type BattlefrontBastionBlue struct{}

func (BattlefrontBastionBlue) ID() ids.CardID           { return ids.BattlefrontBastionBlue }
func (BattlefrontBastionBlue) Name() string             { return "Battlefront Bastion" }
func (BattlefrontBastionBlue) DisplayName() string      { return "Battlefront Bastion [B]" }
func (BattlefrontBastionBlue) Cost(card.GameEngine) int { return 3 }
func (BattlefrontBastionBlue) Pitch() int               { return 3 }
func (BattlefrontBastionBlue) Attack() int              { return 5 }
func (BattlefrontBastionBlue) Defense() int             { return 2 }
func (BattlefrontBastionBlue) Types() card.TypeSet      { return battlefrontBastionTypes }
func (BattlefrontBastionBlue) GoAgain() bool            { return false }
