// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var blowForABlowTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type BlowForABlowRed struct{}

func (BlowForABlowRed) ID() ids.CardID          { return ids.BlowForABlowRed }
func (BlowForABlowRed) Name() string            { return "Blow for a Blow" }
func (BlowForABlowRed) DisplayName() string     { return "Blow for a Blow [R]" }
func (BlowForABlowRed) Cost(sim.GameEngine) int { return 2 }
func (BlowForABlowRed) Pitch() int              { return 1 }
func (BlowForABlowRed) Attack() int             { return 4 }
func (BlowForABlowRed) Defense() int            { return 2 }
func (BlowForABlowRed) Types() card.TypeSet     { return blowForABlowTypes }
