// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var dodgeTypes = card.NewTypeSet(card.TypeGeneric, card.TypeDefenseReaction)

type DodgeBlue struct{}

func (DodgeBlue) ID() ids.CardID          { return ids.DodgeBlue }
func (DodgeBlue) Name() string            { return "Dodge" }
func (DodgeBlue) DisplayName() string     { return "Dodge [B]" }
func (DodgeBlue) Cost(*sim.TurnState) int { return 0 }
func (DodgeBlue) Pitch() int              { return 3 }
func (DodgeBlue) Attack() int             { return 0 }
func (DodgeBlue) Defense() int            { return 2 }
func (DodgeBlue) Types() card.TypeSet     { return dodgeTypes }
func (DodgeBlue) GoAgain() bool           { return false }
