// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var fateForeseenTypes = card.NewTypeSet(card.TypeGeneric, card.TypeDefenseReaction)

type FateForeseenRed struct{}

func (FateForeseenRed) ID() ids.CardID          { return ids.FateForeseenRed }
func (FateForeseenRed) Name() string            { return "Fate Foreseen" }
func (FateForeseenRed) DisplayName() string     { return "Fate Foreseen [R]" }
func (FateForeseenRed) Cost(*sim.TurnState) int { return 0 }
func (FateForeseenRed) Pitch() int              { return 1 }
func (FateForeseenRed) Attack() int             { return 0 }
func (FateForeseenRed) Defense() int            { return 4 }
func (FateForeseenRed) Types() card.TypeSet     { return fateForeseenTypes }
func (FateForeseenRed) GoAgain() bool           { return false }
func (FateForeseenRed) NotSilverAgeLegal()      {}

type FateForeseenYellow struct{}

func (FateForeseenYellow) ID() ids.CardID          { return ids.FateForeseenYellow }
func (FateForeseenYellow) Name() string            { return "Fate Foreseen" }
func (FateForeseenYellow) DisplayName() string     { return "Fate Foreseen [Y]" }
func (FateForeseenYellow) Cost(*sim.TurnState) int { return 0 }
func (FateForeseenYellow) Pitch() int              { return 2 }
func (FateForeseenYellow) Attack() int             { return 0 }
func (FateForeseenYellow) Defense() int            { return 3 }
func (FateForeseenYellow) Types() card.TypeSet     { return fateForeseenTypes }
func (FateForeseenYellow) GoAgain() bool           { return false }
func (FateForeseenYellow) NotSilverAgeLegal()      {}

type FateForeseenBlue struct{}

func (FateForeseenBlue) ID() ids.CardID          { return ids.FateForeseenBlue }
func (FateForeseenBlue) Name() string            { return "Fate Foreseen" }
func (FateForeseenBlue) DisplayName() string     { return "Fate Foreseen [B]" }
func (FateForeseenBlue) Cost(*sim.TurnState) int { return 0 }
func (FateForeseenBlue) Pitch() int              { return 3 }
func (FateForeseenBlue) Attack() int             { return 0 }
func (FateForeseenBlue) Defense() int            { return 2 }
func (FateForeseenBlue) Types() card.TypeSet     { return fateForeseenTypes }
func (FateForeseenBlue) GoAgain() bool           { return false }
func (FateForeseenBlue) NotSilverAgeLegal()      {}
