// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var jackBeNimbleTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type JackBeNimbleRed struct{}

func (JackBeNimbleRed) ID() ids.CardID          { return ids.JackBeNimbleRed }
func (JackBeNimbleRed) Name() string            { return "Jack Be Nimble" }
func (JackBeNimbleRed) DisplayName() string     { return "Jack Be Nimble [R]" }
func (JackBeNimbleRed) Cost(sim.GameEngine) int { return 0 }
func (JackBeNimbleRed) Pitch() int              { return 1 }
func (JackBeNimbleRed) Attack() int             { return 3 }
func (JackBeNimbleRed) Defense() int            { return 3 }
func (JackBeNimbleRed) Types() card.TypeSet     { return jackBeNimbleTypes }
func (JackBeNimbleRed) GoAgain() bool           { return false }
