// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var memorialGroundTypes = card.NewTypeSet(card.TypeGeneric, card.TypeInstant)

type MemorialGroundRed struct{}

func (MemorialGroundRed) ID() ids.CardID                     { return ids.MemorialGroundRed }
func (MemorialGroundRed) Name() string                       { return "Memorial Ground" }
func (MemorialGroundRed) DisplayName() string                { return "Memorial Ground [R]" }
func (MemorialGroundRed) Cost(card.GameEngine) int           { return 0 }
func (MemorialGroundRed) Pitch() int                         { return 1 }
func (MemorialGroundRed) Attack() int                        { return 0 }
func (MemorialGroundRed) Defense() int                       { return 0 }
func (MemorialGroundRed) Types(card.GameEngine) card.TypeSet { return memorialGroundTypes }
func (MemorialGroundRed) GoAgain() bool                      { return false }

type MemorialGroundYellow struct{}

func (MemorialGroundYellow) ID() ids.CardID                     { return ids.MemorialGroundYellow }
func (MemorialGroundYellow) Name() string                       { return "Memorial Ground" }
func (MemorialGroundYellow) DisplayName() string                { return "Memorial Ground [Y]" }
func (MemorialGroundYellow) Cost(card.GameEngine) int           { return 0 }
func (MemorialGroundYellow) Pitch() int                         { return 2 }
func (MemorialGroundYellow) Attack() int                        { return 0 }
func (MemorialGroundYellow) Defense() int                       { return 0 }
func (MemorialGroundYellow) Types(card.GameEngine) card.TypeSet { return memorialGroundTypes }
func (MemorialGroundYellow) GoAgain() bool                      { return false }

type MemorialGroundBlue struct{}

func (MemorialGroundBlue) ID() ids.CardID                     { return ids.MemorialGroundBlue }
func (MemorialGroundBlue) Name() string                       { return "Memorial Ground" }
func (MemorialGroundBlue) DisplayName() string                { return "Memorial Ground [B]" }
func (MemorialGroundBlue) Cost(card.GameEngine) int           { return 0 }
func (MemorialGroundBlue) Pitch() int                         { return 3 }
func (MemorialGroundBlue) Attack() int                        { return 0 }
func (MemorialGroundBlue) Defense() int                       { return 0 }
func (MemorialGroundBlue) Types(card.GameEngine) card.TypeSet { return memorialGroundTypes }
func (MemorialGroundBlue) GoAgain() bool                      { return false }
