// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var muscleMuttTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type MuscleMuttYellow struct{}

func (MuscleMuttYellow) ID() ids.CardID          { return ids.MuscleMuttYellow }
func (MuscleMuttYellow) Name() string            { return "Muscle Mutt" }
func (MuscleMuttYellow) DisplayName() string     { return "Muscle Mutt [Y]" }
func (MuscleMuttYellow) Cost(sim.GameEngine) int { return 3 }
func (MuscleMuttYellow) Pitch() int              { return 2 }
func (MuscleMuttYellow) Attack() int             { return 6 }
func (MuscleMuttYellow) Defense() int            { return 2 }
func (MuscleMuttYellow) Types() card.TypeSet     { return muscleMuttTypes }
func (MuscleMuttYellow) GoAgain() bool           { return false }
