// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var nimblismTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type NimblismRed struct{}

func (NimblismRed) ID() ids.CardID           { return ids.NimblismRed }
func (NimblismRed) Name() string             { return "Nimblism" }
func (NimblismRed) DisplayName() string      { return "Nimblism [R]" }
func (NimblismRed) Cost(card.GameEngine) int { return 0 }
func (NimblismRed) Pitch() int               { return 1 }
func (NimblismRed) Attack() int              { return 0 }
func (NimblismRed) Defense() int             { return 2 }
func (NimblismRed) Types() card.TypeSet      { return nimblismTypes }
func (NimblismRed) GoAgain() bool            { return true }

type NimblismYellow struct{}

func (NimblismYellow) ID() ids.CardID           { return ids.NimblismYellow }
func (NimblismYellow) Name() string             { return "Nimblism" }
func (NimblismYellow) DisplayName() string      { return "Nimblism [Y]" }
func (NimblismYellow) Cost(card.GameEngine) int { return 0 }
func (NimblismYellow) Pitch() int               { return 2 }
func (NimblismYellow) Attack() int              { return 0 }
func (NimblismYellow) Defense() int             { return 2 }
func (NimblismYellow) Types() card.TypeSet      { return nimblismTypes }
func (NimblismYellow) GoAgain() bool            { return true }

type NimblismBlue struct{}

func (NimblismBlue) ID() ids.CardID           { return ids.NimblismBlue }
func (NimblismBlue) Name() string             { return "Nimblism" }
func (NimblismBlue) DisplayName() string      { return "Nimblism [B]" }
func (NimblismBlue) Cost(card.GameEngine) int { return 0 }
func (NimblismBlue) Pitch() int               { return 3 }
func (NimblismBlue) Attack() int              { return 0 }
func (NimblismBlue) Defense() int             { return 2 }
func (NimblismBlue) Types() card.TypeSet      { return nimblismTypes }
func (NimblismBlue) GoAgain() bool            { return true }
