// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var oasisRespiteTypes = card.NewTypeSet(card.TypeGeneric, card.TypeInstant)

type OasisRespiteRed struct{}

func (OasisRespiteRed) ID() ids.CardID                     { return ids.OasisRespiteRed }
func (OasisRespiteRed) Name() string                       { return "Oasis Respite" }
func (OasisRespiteRed) DisplayName() string                { return "Oasis Respite [R]" }
func (OasisRespiteRed) Cost(card.GameEngine) int           { return 1 }
func (OasisRespiteRed) Pitch() int                         { return 1 }
func (OasisRespiteRed) Attack() int                        { return 0 }
func (OasisRespiteRed) Defense() int                       { return 4 }
func (OasisRespiteRed) Types(card.GameEngine) card.TypeSet { return oasisRespiteTypes }
func (OasisRespiteRed) GoAgain(card.GameEngine) bool       { return false }

type OasisRespiteYellow struct{}

func (OasisRespiteYellow) ID() ids.CardID                     { return ids.OasisRespiteYellow }
func (OasisRespiteYellow) Name() string                       { return "Oasis Respite" }
func (OasisRespiteYellow) DisplayName() string                { return "Oasis Respite [Y]" }
func (OasisRespiteYellow) Cost(card.GameEngine) int           { return 1 }
func (OasisRespiteYellow) Pitch() int                         { return 2 }
func (OasisRespiteYellow) Attack() int                        { return 0 }
func (OasisRespiteYellow) Defense() int                       { return 3 }
func (OasisRespiteYellow) Types(card.GameEngine) card.TypeSet { return oasisRespiteTypes }
func (OasisRespiteYellow) GoAgain(card.GameEngine) bool       { return false }

type OasisRespiteBlue struct{}

func (OasisRespiteBlue) ID() ids.CardID                     { return ids.OasisRespiteBlue }
func (OasisRespiteBlue) Name() string                       { return "Oasis Respite" }
func (OasisRespiteBlue) DisplayName() string                { return "Oasis Respite [B]" }
func (OasisRespiteBlue) Cost(card.GameEngine) int           { return 1 }
func (OasisRespiteBlue) Pitch() int                         { return 3 }
func (OasisRespiteBlue) Attack() int                        { return 0 }
func (OasisRespiteBlue) Defense() int                       { return 2 }
func (OasisRespiteBlue) Types(card.GameEngine) card.TypeSet { return oasisRespiteTypes }
func (OasisRespiteBlue) GoAgain(card.GameEngine) bool       { return false }
