// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var outedTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type OutedRed struct{}

func (OutedRed) ID() ids.CardID          { return ids.OutedRed }
func (OutedRed) Name() string            { return "Outed" }
func (OutedRed) DisplayName() string     { return "Outed [R]" }
func (OutedRed) Cost(sim.GameEngine) int { return 0 }
func (OutedRed) Pitch() int              { return 1 }
func (OutedRed) Attack() int             { return 3 }
func (OutedRed) Defense() int            { return 0 }
func (OutedRed) Types() card.TypeSet     { return outedTypes }
func (OutedRed) GoAgain() bool           { return true }
