// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var plunderRunTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type PlunderRunRed struct{}

func (PlunderRunRed) ID() ids.CardID                     { return ids.PlunderRunRed }
func (PlunderRunRed) Name() string                       { return "Plunder Run" }
func (PlunderRunRed) DisplayName() string                { return "Plunder Run [R]" }
func (PlunderRunRed) Cost(card.GameEngine) int           { return 0 }
func (PlunderRunRed) Pitch() int                         { return 1 }
func (PlunderRunRed) Attack() int                        { return 0 }
func (PlunderRunRed) Defense() int                       { return 2 }
func (PlunderRunRed) Types(card.GameEngine) card.TypeSet { return plunderRunTypes }
func (PlunderRunRed) GoAgain() bool                      { return true }
func (PlunderRunRed) NotSilverAgeLegal()                 {}

type PlunderRunYellow struct{}

func (PlunderRunYellow) ID() ids.CardID                     { return ids.PlunderRunYellow }
func (PlunderRunYellow) Name() string                       { return "Plunder Run" }
func (PlunderRunYellow) DisplayName() string                { return "Plunder Run [Y]" }
func (PlunderRunYellow) Cost(card.GameEngine) int           { return 0 }
func (PlunderRunYellow) Pitch() int                         { return 2 }
func (PlunderRunYellow) Attack() int                        { return 0 }
func (PlunderRunYellow) Defense() int                       { return 2 }
func (PlunderRunYellow) Types(card.GameEngine) card.TypeSet { return plunderRunTypes }
func (PlunderRunYellow) GoAgain() bool                      { return true }
func (PlunderRunYellow) NotSilverAgeLegal()                 {}

type PlunderRunBlue struct{}

func (PlunderRunBlue) ID() ids.CardID                     { return ids.PlunderRunBlue }
func (PlunderRunBlue) Name() string                       { return "Plunder Run" }
func (PlunderRunBlue) DisplayName() string                { return "Plunder Run [B]" }
func (PlunderRunBlue) Cost(card.GameEngine) int           { return 0 }
func (PlunderRunBlue) Pitch() int                         { return 3 }
func (PlunderRunBlue) Attack() int                        { return 0 }
func (PlunderRunBlue) Defense() int                       { return 2 }
func (PlunderRunBlue) Types(card.GameEngine) card.TypeSet { return plunderRunTypes }
func (PlunderRunBlue) GoAgain() bool                      { return true }
func (PlunderRunBlue) NotSilverAgeLegal()                 {}
