// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var poundForPoundTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type PoundForPoundRed struct{}

func (PoundForPoundRed) ID() ids.CardID           { return ids.PoundForPoundRed }
func (PoundForPoundRed) Name() string             { return "Pound for Pound" }
func (PoundForPoundRed) DisplayName() string      { return "Pound for Pound [R]" }
func (PoundForPoundRed) Cost(card.GameEngine) int { return 3 }
func (PoundForPoundRed) Pitch() int               { return 1 }
func (PoundForPoundRed) Attack() int              { return 6 }
func (PoundForPoundRed) Defense() int             { return 2 }
func (PoundForPoundRed) Types() card.TypeSet      { return poundForPoundTypes }
func (PoundForPoundRed) GoAgain() bool            { return false }

type PoundForPoundYellow struct{}

func (PoundForPoundYellow) ID() ids.CardID           { return ids.PoundForPoundYellow }
func (PoundForPoundYellow) Name() string             { return "Pound for Pound" }
func (PoundForPoundYellow) DisplayName() string      { return "Pound for Pound [Y]" }
func (PoundForPoundYellow) Cost(card.GameEngine) int { return 3 }
func (PoundForPoundYellow) Pitch() int               { return 2 }
func (PoundForPoundYellow) Attack() int              { return 5 }
func (PoundForPoundYellow) Defense() int             { return 2 }
func (PoundForPoundYellow) Types() card.TypeSet      { return poundForPoundTypes }
func (PoundForPoundYellow) GoAgain() bool            { return false }

type PoundForPoundBlue struct{}

func (PoundForPoundBlue) ID() ids.CardID           { return ids.PoundForPoundBlue }
func (PoundForPoundBlue) Name() string             { return "Pound for Pound" }
func (PoundForPoundBlue) DisplayName() string      { return "Pound for Pound [B]" }
func (PoundForPoundBlue) Cost(card.GameEngine) int { return 3 }
func (PoundForPoundBlue) Pitch() int               { return 3 }
func (PoundForPoundBlue) Attack() int              { return 4 }
func (PoundForPoundBlue) Defense() int             { return 2 }
func (PoundForPoundBlue) Types() card.TypeSet      { return poundForPoundTypes }
func (PoundForPoundBlue) GoAgain() bool            { return false }
