// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var pursueToTheEdgeOfOblivionTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type PursueToTheEdgeOfOblivionRed struct{}

func (PursueToTheEdgeOfOblivionRed) ID() ids.CardID           { return ids.PursueToTheEdgeOfOblivionRed }
func (PursueToTheEdgeOfOblivionRed) Name() string             { return "Pursue to the Edge of Oblivion" }
func (PursueToTheEdgeOfOblivionRed) DisplayName() string      { return "Pursue to the Edge of Oblivion [R]" }
func (PursueToTheEdgeOfOblivionRed) Cost(card.GameEngine) int { return 0 }
func (PursueToTheEdgeOfOblivionRed) Pitch() int               { return 1 }
func (PursueToTheEdgeOfOblivionRed) Attack() int              { return 4 }
func (PursueToTheEdgeOfOblivionRed) Defense() int             { return 3 }
func (PursueToTheEdgeOfOblivionRed) Types(card.GameEngine) card.TypeSet {
	return pursueToTheEdgeOfOblivionTypes
}
func (PursueToTheEdgeOfOblivionRed) GoAgain() bool { return false }
