// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var rightBehindYouTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type RightBehindYouRed struct{}

func (RightBehindYouRed) ID() ids.CardID           { return ids.RightBehindYouRed }
func (RightBehindYouRed) Name() string             { return "Right Behind You" }
func (RightBehindYouRed) DisplayName() string      { return "Right Behind You [R]" }
func (RightBehindYouRed) Cost(card.GameEngine) int { return 3 }
func (RightBehindYouRed) Pitch() int               { return 1 }
func (RightBehindYouRed) Attack() int              { return 7 }
func (RightBehindYouRed) Defense() int             { return 2 }
func (RightBehindYouRed) Types() card.TypeSet      { return rightBehindYouTypes }
func (RightBehindYouRed) GoAgain() bool            { return false }

type RightBehindYouYellow struct{}

func (RightBehindYouYellow) ID() ids.CardID           { return ids.RightBehindYouYellow }
func (RightBehindYouYellow) Name() string             { return "Right Behind You" }
func (RightBehindYouYellow) DisplayName() string      { return "Right Behind You [Y]" }
func (RightBehindYouYellow) Cost(card.GameEngine) int { return 3 }
func (RightBehindYouYellow) Pitch() int               { return 2 }
func (RightBehindYouYellow) Attack() int              { return 6 }
func (RightBehindYouYellow) Defense() int             { return 2 }
func (RightBehindYouYellow) Types() card.TypeSet      { return rightBehindYouTypes }
func (RightBehindYouYellow) GoAgain() bool            { return false }

type RightBehindYouBlue struct{}

func (RightBehindYouBlue) ID() ids.CardID           { return ids.RightBehindYouBlue }
func (RightBehindYouBlue) Name() string             { return "Right Behind You" }
func (RightBehindYouBlue) DisplayName() string      { return "Right Behind You [B]" }
func (RightBehindYouBlue) Cost(card.GameEngine) int { return 3 }
func (RightBehindYouBlue) Pitch() int               { return 3 }
func (RightBehindYouBlue) Attack() int              { return 5 }
func (RightBehindYouBlue) Defense() int             { return 2 }
func (RightBehindYouBlue) Types() card.TypeSet      { return rightBehindYouTypes }
func (RightBehindYouBlue) GoAgain() bool            { return false }
