// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var sigilOfFyendalTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAura)

type SigilOfFyendalBlue struct{}

func (SigilOfFyendalBlue) ID() ids.CardID          { return ids.SigilOfFyendalBlue }
func (SigilOfFyendalBlue) Name() string            { return "Sigil of Fyendal" }
func (SigilOfFyendalBlue) DisplayName() string     { return "Sigil of Fyendal [B]" }
func (SigilOfFyendalBlue) Cost(*sim.TurnState) int { return 0 }
func (SigilOfFyendalBlue) Pitch() int              { return 3 }
func (SigilOfFyendalBlue) Attack() int             { return 0 }
func (SigilOfFyendalBlue) Defense() int            { return 2 }
func (SigilOfFyendalBlue) Types() card.TypeSet     { return sigilOfFyendalTypes }
func (SigilOfFyendalBlue) GoAgain() bool           { return true }
