// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var skyFireLanternsTypes = card.NewTypeSet(card.TypeRuneblade, card.TypeAction)

type SkyFireLanternsRed struct{}

func (SkyFireLanternsRed) ID() ids.CardID                     { return ids.SkyFireLanternsRed }
func (SkyFireLanternsRed) Name() string                       { return "Sky Fire Lanterns" }
func (SkyFireLanternsRed) DisplayName() string                { return "Sky Fire Lanterns [R]" }
func (SkyFireLanternsRed) Cost(card.GameEngine) int           { return 0 }
func (SkyFireLanternsRed) Pitch() int                         { return 1 }
func (SkyFireLanternsRed) Attack() int                        { return 0 }
func (SkyFireLanternsRed) Defense() int                       { return 2 }
func (SkyFireLanternsRed) Types(card.GameEngine) card.TypeSet { return skyFireLanternsTypes }
func (SkyFireLanternsRed) GoAgain(card.GameEngine) bool       { return true }

type SkyFireLanternsYellow struct{}

func (SkyFireLanternsYellow) ID() ids.CardID                     { return ids.SkyFireLanternsYellow }
func (SkyFireLanternsYellow) Name() string                       { return "Sky Fire Lanterns" }
func (SkyFireLanternsYellow) DisplayName() string                { return "Sky Fire Lanterns [Y]" }
func (SkyFireLanternsYellow) Cost(card.GameEngine) int           { return 0 }
func (SkyFireLanternsYellow) Pitch() int                         { return 2 }
func (SkyFireLanternsYellow) Attack() int                        { return 0 }
func (SkyFireLanternsYellow) Defense() int                       { return 2 }
func (SkyFireLanternsYellow) Types(card.GameEngine) card.TypeSet { return skyFireLanternsTypes }
func (SkyFireLanternsYellow) GoAgain(card.GameEngine) bool       { return true }

type SkyFireLanternsBlue struct{}

func (SkyFireLanternsBlue) ID() ids.CardID                     { return ids.SkyFireLanternsBlue }
func (SkyFireLanternsBlue) Name() string                       { return "Sky Fire Lanterns" }
func (SkyFireLanternsBlue) DisplayName() string                { return "Sky Fire Lanterns [B]" }
func (SkyFireLanternsBlue) Cost(card.GameEngine) int           { return 0 }
func (SkyFireLanternsBlue) Pitch() int                         { return 3 }
func (SkyFireLanternsBlue) Attack() int                        { return 0 }
func (SkyFireLanternsBlue) Defense() int                       { return 2 }
func (SkyFireLanternsBlue) Types(card.GameEngine) card.TypeSet { return skyFireLanternsTypes }
func (SkyFireLanternsBlue) GoAgain(card.GameEngine) bool       { return true }
