// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var snatchTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type SnatchRed struct{}

func (SnatchRed) ID() ids.CardID          { return ids.SnatchRed }
func (SnatchRed) Name() string            { return "Snatch" }
func (SnatchRed) DisplayName() string     { return "Snatch [R]" }
func (SnatchRed) Cost(*sim.TurnState) int { return 0 }
func (SnatchRed) Pitch() int              { return 1 }
func (SnatchRed) Attack() int             { return 4 }
func (SnatchRed) Defense() int            { return 2 }
func (SnatchRed) Types() card.TypeSet     { return snatchTypes }
func (SnatchRed) GoAgain() bool           { return false }

type SnatchYellow struct{}

func (SnatchYellow) ID() ids.CardID          { return ids.SnatchYellow }
func (SnatchYellow) Name() string            { return "Snatch" }
func (SnatchYellow) DisplayName() string     { return "Snatch [Y]" }
func (SnatchYellow) Cost(*sim.TurnState) int { return 0 }
func (SnatchYellow) Pitch() int              { return 2 }
func (SnatchYellow) Attack() int             { return 3 }
func (SnatchYellow) Defense() int            { return 2 }
func (SnatchYellow) Types() card.TypeSet     { return snatchTypes }
func (SnatchYellow) GoAgain() bool           { return false }

type SnatchBlue struct{}

func (SnatchBlue) ID() ids.CardID          { return ids.SnatchBlue }
func (SnatchBlue) Name() string            { return "Snatch" }
func (SnatchBlue) DisplayName() string     { return "Snatch [B]" }
func (SnatchBlue) Cost(*sim.TurnState) int { return 0 }
func (SnatchBlue) Pitch() int              { return 3 }
func (SnatchBlue) Attack() int             { return 2 }
func (SnatchBlue) Defense() int            { return 2 }
func (SnatchBlue) Types() card.TypeSet     { return snatchTypes }
func (SnatchBlue) GoAgain() bool           { return false }
