// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var startingStakeTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type StartingStakeYellow struct{}

func (StartingStakeYellow) ID() ids.CardID                     { return ids.StartingStakeYellow }
func (StartingStakeYellow) Name() string                       { return "Starting Stake" }
func (StartingStakeYellow) DisplayName() string                { return "Starting Stake [Y]" }
func (StartingStakeYellow) Cost(card.GameEngine) int           { return 0 }
func (StartingStakeYellow) Pitch() int                         { return 2 }
func (StartingStakeYellow) Attack() int                        { return 0 }
func (StartingStakeYellow) Defense() int                       { return 3 }
func (StartingStakeYellow) Types(card.GameEngine) card.TypeSet { return startingStakeTypes }
func (StartingStakeYellow) GoAgain() bool                      { return false }
