// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/v2/card"
)

var waterTheSeedsTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type WaterTheSeedsRed struct{}

func (WaterTheSeedsRed) ID() ids.CardID                     { return ids.WaterTheSeedsRed }
func (WaterTheSeedsRed) Name() string                       { return "Water the Seeds" }
func (WaterTheSeedsRed) DisplayName() string                { return "Water the Seeds [R]" }
func (WaterTheSeedsRed) Cost(card.GameEngine) int           { return 1 }
func (WaterTheSeedsRed) Pitch() int                         { return 1 }
func (WaterTheSeedsRed) Attack() int                        { return 3 }
func (WaterTheSeedsRed) Defense() int                       { return 2 }
func (WaterTheSeedsRed) Types(card.GameEngine) card.TypeSet { return waterTheSeedsTypes }
func (WaterTheSeedsRed) GoAgain(card.GameEngine) bool       { return true }

type WaterTheSeedsYellow struct{}

func (WaterTheSeedsYellow) ID() ids.CardID                     { return ids.WaterTheSeedsYellow }
func (WaterTheSeedsYellow) Name() string                       { return "Water the Seeds" }
func (WaterTheSeedsYellow) DisplayName() string                { return "Water the Seeds [Y]" }
func (WaterTheSeedsYellow) Cost(card.GameEngine) int           { return 1 }
func (WaterTheSeedsYellow) Pitch() int                         { return 2 }
func (WaterTheSeedsYellow) Attack() int                        { return 2 }
func (WaterTheSeedsYellow) Defense() int                       { return 2 }
func (WaterTheSeedsYellow) Types(card.GameEngine) card.TypeSet { return waterTheSeedsTypes }
func (WaterTheSeedsYellow) GoAgain(card.GameEngine) bool       { return true }

type WaterTheSeedsBlue struct{}

func (WaterTheSeedsBlue) ID() ids.CardID                     { return ids.WaterTheSeedsBlue }
func (WaterTheSeedsBlue) Name() string                       { return "Water the Seeds" }
func (WaterTheSeedsBlue) DisplayName() string                { return "Water the Seeds [B]" }
func (WaterTheSeedsBlue) Cost(card.GameEngine) int           { return 1 }
func (WaterTheSeedsBlue) Pitch() int                         { return 3 }
func (WaterTheSeedsBlue) Attack() int                        { return 1 }
func (WaterTheSeedsBlue) Defense() int                       { return 2 }
func (WaterTheSeedsBlue) Types(card.GameEngine) card.TypeSet { return waterTheSeedsTypes }
func (WaterTheSeedsBlue) GoAgain(card.GameEngine) bool       { return true }
