// Code generated by cardgen. DO NOT EDIT.

package cards

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/registry/ids"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/sim"
)

var zealousBeltingTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type ZealousBeltingRed struct{}

func (ZealousBeltingRed) ID() ids.CardID          { return ids.ZealousBeltingRed }
func (ZealousBeltingRed) Name() string            { return "Zealous Belting" }
func (ZealousBeltingRed) DisplayName() string     { return "Zealous Belting [R]" }
func (ZealousBeltingRed) Cost(*sim.TurnState) int { return 2 }
func (ZealousBeltingRed) Pitch() int              { return 1 }
func (ZealousBeltingRed) Attack() int             { return 5 }
func (ZealousBeltingRed) Defense() int            { return 2 }
func (ZealousBeltingRed) Types() card.TypeSet     { return zealousBeltingTypes }
func (ZealousBeltingRed) GoAgain() bool           { return false }

type ZealousBeltingYellow struct{}

func (ZealousBeltingYellow) ID() ids.CardID          { return ids.ZealousBeltingYellow }
func (ZealousBeltingYellow) Name() string            { return "Zealous Belting" }
func (ZealousBeltingYellow) DisplayName() string     { return "Zealous Belting [Y]" }
func (ZealousBeltingYellow) Cost(*sim.TurnState) int { return 2 }
func (ZealousBeltingYellow) Pitch() int              { return 2 }
func (ZealousBeltingYellow) Attack() int             { return 4 }
func (ZealousBeltingYellow) Defense() int            { return 2 }
func (ZealousBeltingYellow) Types() card.TypeSet     { return zealousBeltingTypes }
func (ZealousBeltingYellow) GoAgain() bool           { return false }

type ZealousBeltingBlue struct{}

func (ZealousBeltingBlue) ID() ids.CardID          { return ids.ZealousBeltingBlue }
func (ZealousBeltingBlue) Name() string            { return "Zealous Belting" }
func (ZealousBeltingBlue) DisplayName() string     { return "Zealous Belting [B]" }
func (ZealousBeltingBlue) Cost(*sim.TurnState) int { return 2 }
func (ZealousBeltingBlue) Pitch() int              { return 3 }
func (ZealousBeltingBlue) Attack() int             { return 3 }
func (ZealousBeltingBlue) Defense() int            { return 2 }
func (ZealousBeltingBlue) Types() card.TypeSet     { return zealousBeltingTypes }
func (ZealousBeltingBlue) GoAgain() bool           { return false }
