// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var amuletOfInterventionTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type AmuletOfInterventionBlue struct{}

func (AmuletOfInterventionBlue) ID() ids.CardID                     { return ids.AmuletOfInterventionBlue }
func (AmuletOfInterventionBlue) Name() string                       { return "Amulet of Intervention" }
func (AmuletOfInterventionBlue) DisplayName() string                { return "Amulet of Intervention [B]" }
func (AmuletOfInterventionBlue) Rarity() string                     { return "Rare" }
func (AmuletOfInterventionBlue) Cost() int                          { return 0 }
func (AmuletOfInterventionBlue) Pitch() int                         { return 3 }
func (AmuletOfInterventionBlue) Attack() int                        { return 0 }
func (AmuletOfInterventionBlue) Defense() int                       { return 0 }
func (AmuletOfInterventionBlue) Types(card.GameEngine) card.TypeSet { return amuletOfInterventionTypes }
func (AmuletOfInterventionBlue) GoAgain(card.GameEngine) bool       { return true }
func (AmuletOfInterventionBlue) Unplayable()                        {}
