// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var amuletOfOblationTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeItem)

type AmuletOfOblationBlue struct{}

func (AmuletOfOblationBlue) ID() ids.CardID                     { return ids.AmuletOfOblationBlue }
func (AmuletOfOblationBlue) Name() string                       { return "Amulet of Oblation" }
func (AmuletOfOblationBlue) DisplayName() string                { return "Amulet of Oblation [B]" }
func (AmuletOfOblationBlue) Cost(card.GameEngine) int           { return 0 }
func (AmuletOfOblationBlue) Pitch() int                         { return 3 }
func (AmuletOfOblationBlue) Attack() int                        { return 0 }
func (AmuletOfOblationBlue) Defense() int                       { return 0 }
func (AmuletOfOblationBlue) Types(card.GameEngine) card.TypeSet { return amuletOfOblationTypes }
func (AmuletOfOblationBlue) GoAgain(card.GameEngine) bool       { return true }
func (AmuletOfOblationBlue) Unplayable()                        {}
