// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var belittleTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type BelittleRed struct{}

func (BelittleRed) ID() ids.CardID                     { return ids.BelittleRed }
func (BelittleRed) Name() string                       { return "Belittle" }
func (BelittleRed) DisplayName() string                { return "Belittle [R]" }
func (BelittleRed) Cost() int                          { return 1 }
func (BelittleRed) Pitch() int                         { return 1 }
func (BelittleRed) Attack() int                        { return 3 }
func (BelittleRed) Defense() int                       { return 2 }
func (BelittleRed) Types(card.GameEngine) card.TypeSet { return belittleTypes }
func (BelittleRed) GoAgain(card.GameEngine) bool       { return true }
func (BelittleRed) NotSilverAgeLegal()                 {}
func (BelittleRed) Unplayable()                        {}

type BelittleYellow struct{}

func (BelittleYellow) ID() ids.CardID                     { return ids.BelittleYellow }
func (BelittleYellow) Name() string                       { return "Belittle" }
func (BelittleYellow) DisplayName() string                { return "Belittle [Y]" }
func (BelittleYellow) Cost() int                          { return 1 }
func (BelittleYellow) Pitch() int                         { return 2 }
func (BelittleYellow) Attack() int                        { return 2 }
func (BelittleYellow) Defense() int                       { return 2 }
func (BelittleYellow) Types(card.GameEngine) card.TypeSet { return belittleTypes }
func (BelittleYellow) GoAgain(card.GameEngine) bool       { return true }
func (BelittleYellow) NotSilverAgeLegal()                 {}
func (BelittleYellow) Unplayable()                        {}

type BelittleBlue struct{}

func (BelittleBlue) ID() ids.CardID                     { return ids.BelittleBlue }
func (BelittleBlue) Name() string                       { return "Belittle" }
func (BelittleBlue) DisplayName() string                { return "Belittle [B]" }
func (BelittleBlue) Cost() int                          { return 1 }
func (BelittleBlue) Pitch() int                         { return 3 }
func (BelittleBlue) Attack() int                        { return 1 }
func (BelittleBlue) Defense() int                       { return 2 }
func (BelittleBlue) Types(card.GameEngine) card.TypeSet { return belittleTypes }
func (BelittleBlue) GoAgain(card.GameEngine) bool       { return true }
func (BelittleBlue) NotSilverAgeLegal()                 {}
func (BelittleBlue) Unplayable()                        {}
