// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var droneOfBrutalityTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type DroneOfBrutalityRed struct{}

func (DroneOfBrutalityRed) ID() ids.CardID                     { return ids.DroneOfBrutalityRed }
func (DroneOfBrutalityRed) Name() string                       { return "Drone of Brutality" }
func (DroneOfBrutalityRed) DisplayName() string                { return "Drone of Brutality [R]" }
func (DroneOfBrutalityRed) Rarity() string                     { return "Rare" }
func (DroneOfBrutalityRed) Cost() int                          { return 2 }
func (DroneOfBrutalityRed) Pitch() int                         { return 1 }
func (DroneOfBrutalityRed) Attack() int                        { return 6 }
func (DroneOfBrutalityRed) Defense() int                       { return 2 }
func (DroneOfBrutalityRed) Types(card.GameEngine) card.TypeSet { return droneOfBrutalityTypes }
func (DroneOfBrutalityRed) GoAgain(card.GameEngine) bool       { return false }
func (DroneOfBrutalityRed) Unplayable()                        {}

type DroneOfBrutalityYellow struct{}

func (DroneOfBrutalityYellow) ID() ids.CardID                     { return ids.DroneOfBrutalityYellow }
func (DroneOfBrutalityYellow) Name() string                       { return "Drone of Brutality" }
func (DroneOfBrutalityYellow) DisplayName() string                { return "Drone of Brutality [Y]" }
func (DroneOfBrutalityYellow) Rarity() string                     { return "Rare" }
func (DroneOfBrutalityYellow) Cost() int                          { return 2 }
func (DroneOfBrutalityYellow) Pitch() int                         { return 2 }
func (DroneOfBrutalityYellow) Attack() int                        { return 5 }
func (DroneOfBrutalityYellow) Defense() int                       { return 2 }
func (DroneOfBrutalityYellow) Types(card.GameEngine) card.TypeSet { return droneOfBrutalityTypes }
func (DroneOfBrutalityYellow) GoAgain(card.GameEngine) bool       { return false }
func (DroneOfBrutalityYellow) Unplayable()                        {}

type DroneOfBrutalityBlue struct{}

func (DroneOfBrutalityBlue) ID() ids.CardID                     { return ids.DroneOfBrutalityBlue }
func (DroneOfBrutalityBlue) Name() string                       { return "Drone of Brutality" }
func (DroneOfBrutalityBlue) DisplayName() string                { return "Drone of Brutality [B]" }
func (DroneOfBrutalityBlue) Rarity() string                     { return "Rare" }
func (DroneOfBrutalityBlue) Cost() int                          { return 2 }
func (DroneOfBrutalityBlue) Pitch() int                         { return 3 }
func (DroneOfBrutalityBlue) Attack() int                        { return 4 }
func (DroneOfBrutalityBlue) Defense() int                       { return 2 }
func (DroneOfBrutalityBlue) Types(card.GameEngine) card.TypeSet { return droneOfBrutalityTypes }
func (DroneOfBrutalityBlue) GoAgain(card.GameEngine) bool       { return false }
func (DroneOfBrutalityBlue) Unplayable()                        {}
