// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var putInContextTypes = card.NewTypeSet(card.TypeGeneric, card.TypeDefenseReaction)

type PutInContextBlue struct{}

func (PutInContextBlue) ID() ids.CardID                     { return ids.PutInContextBlue }
func (PutInContextBlue) Name() string                       { return "Put in Context" }
func (PutInContextBlue) DisplayName() string                { return "Put in Context [B]" }
func (PutInContextBlue) Rarity() string                     { return "Common" }
func (PutInContextBlue) Cost() int                          { return 0 }
func (PutInContextBlue) Pitch() int                         { return 3 }
func (PutInContextBlue) Attack() int                        { return 0 }
func (PutInContextBlue) Defense() int                       { return 3 }
func (PutInContextBlue) Types(card.GameEngine) card.TypeSet { return putInContextTypes }
func (PutInContextBlue) GoAgain(card.GameEngine) bool       { return false }
func (PutInContextBlue) Unplayable()                        {}
