// Code generated by cardgen. DO NOT EDIT.

package unplayable

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var sinkBelowTypes = card.NewTypeSet()

type SinkBelowRed struct{}

func (SinkBelowRed) ID() ids.CardID                     { return ids.SinkBelowRed }
func (SinkBelowRed) Name() string                       { return "Sink Below" }
func (SinkBelowRed) DisplayName() string                { return "Sink Below [R]" }
func (SinkBelowRed) Rarity() string                     { return "Common" }
func (SinkBelowRed) Cost() int                          { return 0 }
func (SinkBelowRed) Pitch() int                         { return 1 }
func (SinkBelowRed) Attack() int                        { return 0 }
func (SinkBelowRed) Defense() int                       { return 4 }
func (SinkBelowRed) Types(card.GameEngine) card.TypeSet { return sinkBelowTypes }
func (SinkBelowRed) GoAgain(card.GameEngine) bool       { return false }
func (SinkBelowRed) Unplayable()                        {}

type SinkBelowYellow struct{}

func (SinkBelowYellow) ID() ids.CardID                     { return ids.SinkBelowYellow }
func (SinkBelowYellow) Name() string                       { return "Sink Below" }
func (SinkBelowYellow) DisplayName() string                { return "Sink Below [Y]" }
func (SinkBelowYellow) Rarity() string                     { return "Common" }
func (SinkBelowYellow) Cost() int                          { return 0 }
func (SinkBelowYellow) Pitch() int                         { return 2 }
func (SinkBelowYellow) Attack() int                        { return 0 }
func (SinkBelowYellow) Defense() int                       { return 3 }
func (SinkBelowYellow) Types(card.GameEngine) card.TypeSet { return sinkBelowTypes }
func (SinkBelowYellow) GoAgain(card.GameEngine) bool       { return false }
func (SinkBelowYellow) Unplayable()                        {}

type SinkBelowBlue struct{}

func (SinkBelowBlue) ID() ids.CardID                     { return ids.SinkBelowBlue }
func (SinkBelowBlue) Name() string                       { return "Sink Below" }
func (SinkBelowBlue) DisplayName() string                { return "Sink Below [B]" }
func (SinkBelowBlue) Rarity() string                     { return "Common" }
func (SinkBelowBlue) Cost() int                          { return 0 }
func (SinkBelowBlue) Pitch() int                         { return 3 }
func (SinkBelowBlue) Attack() int                        { return 0 }
func (SinkBelowBlue) Defense() int                       { return 2 }
func (SinkBelowBlue) Types(card.GameEngine) card.TypeSet { return sinkBelowTypes }
func (SinkBelowBlue) GoAgain(card.GameEngine) bool       { return false }
func (SinkBelowBlue) Unplayable()                        {}
