// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var soundTheAlarmTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type SoundTheAlarmRed struct{}

func (SoundTheAlarmRed) ID() ids.CardID                     { return ids.SoundTheAlarmRed }
func (SoundTheAlarmRed) Name() string                       { return "Sound the Alarm" }
func (SoundTheAlarmRed) DisplayName() string                { return "Sound the Alarm [R]" }
func (SoundTheAlarmRed) Cost(card.GameEngine) int           { return 1 }
func (SoundTheAlarmRed) Pitch() int                         { return 1 }
func (SoundTheAlarmRed) Attack() int                        { return 5 }
func (SoundTheAlarmRed) Defense() int                       { return 3 }
func (SoundTheAlarmRed) Types(card.GameEngine) card.TypeSet { return soundTheAlarmTypes }
func (SoundTheAlarmRed) GoAgain(card.GameEngine) bool       { return false }
func (SoundTheAlarmRed) NotImplemented()                    {}
