// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var visitTheBlacksmithTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction)

type VisitTheBlacksmithBlue struct{}

func (VisitTheBlacksmithBlue) ID() ids.CardID                     { return ids.VisitTheBlacksmithBlue }
func (VisitTheBlacksmithBlue) Name() string                       { return "Visit the Blacksmith" }
func (VisitTheBlacksmithBlue) DisplayName() string                { return "Visit the Blacksmith [B]" }
func (VisitTheBlacksmithBlue) Cost(card.GameEngine) int           { return 0 }
func (VisitTheBlacksmithBlue) Pitch() int                         { return 3 }
func (VisitTheBlacksmithBlue) Attack() int                        { return 0 }
func (VisitTheBlacksmithBlue) Defense() int                       { return 2 }
func (VisitTheBlacksmithBlue) Types(card.GameEngine) card.TypeSet { return visitTheBlacksmithTypes }
func (VisitTheBlacksmithBlue) GoAgain(card.GameEngine) bool       { return true }
func (VisitTheBlacksmithBlue) NotImplemented()                    {}
