// Code generated by cardgen. DO NOT EDIT.

package notimplemented

import (
	"github.com/tim-chaplin/fab-deck-optimizer/internal/card"
	"github.com/tim-chaplin/fab-deck-optimizer/internal/ids"
)

var walkThePlankTypes = card.NewTypeSet(card.TypeGeneric, card.TypeAction, card.TypeAttack)

type WalkThePlankRed struct{}

func (WalkThePlankRed) ID() ids.CardID                     { return ids.WalkThePlankRed }
func (WalkThePlankRed) Name() string                       { return "Walk the Plank" }
func (WalkThePlankRed) DisplayName() string                { return "Walk the Plank [R]" }
func (WalkThePlankRed) Cost(card.GameEngine) int           { return 3 }
func (WalkThePlankRed) Pitch() int                         { return 1 }
func (WalkThePlankRed) Attack() int                        { return 7 }
func (WalkThePlankRed) Defense() int                       { return 2 }
func (WalkThePlankRed) Types(card.GameEngine) card.TypeSet { return walkThePlankTypes }
func (WalkThePlankRed) GoAgain(card.GameEngine) bool       { return false }
func (WalkThePlankRed) NotImplemented()                    {}

type WalkThePlankYellow struct{}

func (WalkThePlankYellow) ID() ids.CardID                     { return ids.WalkThePlankYellow }
func (WalkThePlankYellow) Name() string                       { return "Walk the Plank" }
func (WalkThePlankYellow) DisplayName() string                { return "Walk the Plank [Y]" }
func (WalkThePlankYellow) Cost(card.GameEngine) int           { return 3 }
func (WalkThePlankYellow) Pitch() int                         { return 2 }
func (WalkThePlankYellow) Attack() int                        { return 6 }
func (WalkThePlankYellow) Defense() int                       { return 2 }
func (WalkThePlankYellow) Types(card.GameEngine) card.TypeSet { return walkThePlankTypes }
func (WalkThePlankYellow) GoAgain(card.GameEngine) bool       { return false }
func (WalkThePlankYellow) NotImplemented()                    {}

type WalkThePlankBlue struct{}

func (WalkThePlankBlue) ID() ids.CardID                     { return ids.WalkThePlankBlue }
func (WalkThePlankBlue) Name() string                       { return "Walk the Plank" }
func (WalkThePlankBlue) DisplayName() string                { return "Walk the Plank [B]" }
func (WalkThePlankBlue) Cost(card.GameEngine) int           { return 3 }
func (WalkThePlankBlue) Pitch() int                         { return 3 }
func (WalkThePlankBlue) Attack() int                        { return 5 }
func (WalkThePlankBlue) Defense() int                       { return 2 }
func (WalkThePlankBlue) Types(card.GameEngine) card.TypeSet { return walkThePlankTypes }
func (WalkThePlankBlue) GoAgain(card.GameEngine) bool       { return false }
func (WalkThePlankBlue) NotImplemented()                    {}
